[move]
index = 195
name = "MOVE_PERISH_SONG"
type = "TYPE_NORMAL"
quality = "EFFECT_STATUS_INFLICTING"
category = "SPLIT_STATUS"
power = 0
accuracy = "MUST_HIT"
base_pp = 5
priority = 0
critical_hit_stage = 0
flinch_rate = 0
animation_id = 114
recoil = 0
heal = 0
target = "TARGET_ALL"
padding = 21331
flags = ["FLAG_SOUND_MOVE", "FLAG_HITS_NON_ADJACENT_OPPONENTS", "FLAG_HITS_THROUGH_SUBSTITUTE"]

[move.hits]
minimum = 0
maximum = 0

[move.inflict]
status = 20
chance = 0
duration = 2
turn_min = 4
turn_max = 4

[[move.stat_changes]]
stat = "STATUS_NONE"
stages = 0
chance = 0

[[move.stat_changes]]
stat = "STATUS_NONE"
stages = 0
chance = 0

[[move.stat_changes]]
stat = "STATUS_NONE"
stages = 0
chance = 0
