[move]
index = 203
name = "MOVE_ENDURE"
type = "TYPE_NORMAL"
quality = "EFFECT_OTHERS"
category = "SPLIT_STATUS"
power = 0
accuracy = "MUST_HIT"
base_pp = 10
priority = 4
critical_hit_stage = 0
flinch_rate = 0
animation_id = 116
recoil = 0
heal = 0
target = "TARGET_USER"
padding = 21331
flags = []

[move.hits]
minimum = 0
maximum = 0

[move.inflict]
status = "INFLICT_DURATION_NONE"
chance = 0
duration = 0
turn_min = 0
turn_max = 0

[[move.stat_changes]]
stat = "STATUS_NONE"
stages = 0
chance = 0

[[move.stat_changes]]
stat = "STATUS_NONE"
stages = 0
chance = 0

[[move.stat_changes]]
stat = "STATUS_NONE"
stages = 0
chance = 0
