[move]
index = 215
name = "MOVE_HEAL_BELL"
type = "TYPE_NORMAL"
quality = "EFFECT_OTHERS"
category = "SPLIT_STATUS"
power = 0
accuracy = "MUST_HIT"
base_pp = 5
priority = 0
critical_hit_stage = 0
flinch_rate = 0
animation_id = 102
recoil = 0
heal = 0
target = "TARGET_FRIEND_ALL"
padding = 21331
flags = ["FLAG_STOLEN_BY_SNATCH", "FLAG_SOUND_MOVE"]

[move.hits]
minimum = 0
maximum = 0

[move.inflict]
status = "INFLICT_DURATION_NONE"
chance = 0
duration = 0
turn_min = 0
turn_max = 0

[[move.stat_changes]]
stat = "STATUS_NONE"
stages = 0
chance = 0

[[move.stat_changes]]
stat = "STATUS_NONE"
stages = 0
chance = 0

[[move.stat_changes]]
stat = "STATUS_NONE"
stages = 0
chance = 0
