[move]
index = 340
name = "MOVE_BOUNCE"
type = "TYPE_FLYING"
quality = "EFFECT_CHANCE_TO_INFLICT_STATUS"
category = "SPLIT_PHYSICAL"
power = 85
accuracy = 85
base_pp = 5
priority = 0
critical_hit_stage = 0
flinch_rate = 0
animation_id = 263
recoil = 0
heal = 0
target = "TARGET_OTHER_SELECT"
padding = 21331
flags = ["FLAG_CONTACT", "FLAG_REQUIRES_CHARGE", "FLAG_BLOCKED_BY_PROTECT", "FLAG_COPIED_BY_MIRROR_MOVE", "FLAG_GROUNDED_BY_GRAVITY", "FLAG_HITS_NON_ADJACENT_OPPONENTS"]

[move.hits]
minimum = 0
maximum = 0

[move.inflict]
status = "INFLICT_DURATION_PERMANENT"
chance = 30
duration = 1
turn_min = 0
turn_max = 0

[[move.stat_changes]]
stat = "STATUS_NONE"
stages = 0
chance = 0

[[move.stat_changes]]
stat = "STATUS_NONE"
stages = 0
chance = 0

[[move.stat_changes]]
stat = "STATUS_NONE"
stages = 0
chance = 0
