[move]
index = 472
name = "MOVE_WONDER_ROOM"
type = "TYPE_PSYCHIC"
quality = "EFFECT_FIELD_EFFCT"
category = "SPLIT_STATUS"
power = 0
accuracy = "MUST_HIT"
base_pp = 10
priority = -7
critical_hit_stage = 0
flinch_rate = 0
animation_id = 281
recoil = 0
heal = 0
target = "TARGET_FIELD"
padding = 21331
flags = ["FLAG_COPIED_BY_MIRROR_MOVE"]

[move.hits]
minimum = 0
maximum = 0

[move.inflict]
status = "INFLICT_DURATION_NONE"
chance = 0
duration = 0
turn_min = 0
turn_max = 0

[[move.stat_changes]]
stat = "STATUS_NONE"
stages = 0
chance = 0

[[move.stat_changes]]
stat = "STATUS_NONE"
stages = 0
chance = 0

[[move.stat_changes]]
stat = "STATUS_NONE"
stages = 0
chance = 0
