[item]
index = 48
name = "ITEM_CARBOS"
price = 980
held_effect = 0
held_argument = 0
natural_gift_effect = 0
fling_effect = 0
fling_power = 30
natural_gift_power = 0
packed = 159
effect_field = 1
effect_battle = 0
has_battle_stats = 1
item_class = 0
consumable = 0
sort_index = 56

[item.battle_stats]
cure_inflict = 0
boost = [0, 0, 0, 0]
function_flags = 7232
ev_hp = 0
ev_attack = 0
ev_defense = 0
ev_speed = 10
ev_special_attack = 0
ev_special_defense = 0
heal_amount = 0
pp_gain = 0
friendship_1 = 5
friendship_2 = 3
friendship_3 = 2
field_1f = 0
field_20 = 0
