[item]
index = 234
name = "ITEM_LEFTOVERS"
price = 20
held_effect = 69
held_argument = 10
natural_gift_effect = 0
fling_effect = 0
fling_power = 10
natural_gift_power = 0
packed = 31
effect_field = 0
effect_battle = 0
has_battle_stats = 0
item_class = 1
consumable = 0
sort_index = 67

[item.battle_stats]
cure_inflict = 0
boost = [0, 0, 0, 0]
function_flags = 0
ev_hp = 0
ev_attack = 0
ev_defense = 0
ev_speed = 0
ev_special_attack = 0
ev_special_defense = 0
heal_amount = 0
pp_gain = 0
friendship_1 = 0
friendship_2 = 0
friendship_3 = 0
field_1f = 0
field_20 = 0
