[evolutions]
index = 13
species = "SPECIES_WEEDLE"

[[evolutions.entries]]
slot = 0
method = "METHOD_LEVELUP"
parameter = 7
target_species = "SPECIES_KAKUNA"

[[evolutions.entries]]
slot = 1
method = "METHOD_NONE"
parameter = 0
target_species = "SPECIES_NONE"

[[evolutions.entries]]
slot = 2
method = "METHOD_NONE"
parameter = 0
target_species = "SPECIES_NONE"

[[evolutions.entries]]
slot = 3
method = "METHOD_NONE"
parameter = 0
target_species = "SPECIES_NONE"

[[evolutions.entries]]
slot = 4
method = "METHOD_NONE"
parameter = 0
target_species = "SPECIES_NONE"

[[evolutions.entries]]
slot = 5
method = "METHOD_NONE"
parameter = 0
target_species = "SPECIES_NONE"

[[evolutions.entries]]
slot = 6
method = "METHOD_NONE"
parameter = 0
target_species = "SPECIES_NONE"
