[evolutions]
index = 165
species = "SPECIES_LEDYBA"

[[evolutions.entries]]
slot = 0
method = "METHOD_LEVELUP"
parameter = 18
target_species = "SPECIES_LEDIAN"

[[evolutions.entries]]
slot = 1
method = "METHOD_NONE"
parameter = 0
target_species = "SPECIES_NONE"

[[evolutions.entries]]
slot = 2
method = "METHOD_NONE"
parameter = 0
target_species = "SPECIES_NONE"

[[evolutions.entries]]
slot = 3
method = "METHOD_NONE"
parameter = 0
target_species = "SPECIES_NONE"

[[evolutions.entries]]
slot = 4
method = "METHOD_NONE"
parameter = 0
target_species = "SPECIES_NONE"

[[evolutions.entries]]
slot = 5
method = "METHOD_NONE"
parameter = 0
target_species = "SPECIES_NONE"

[[evolutions.entries]]
slot = 6
method = "METHOD_NONE"
parameter = 0
target_species = "SPECIES_NONE"
