[evolutions]
index = 236
species = "SPECIES_TYROGUE"

[[evolutions.entries]]
slot = 0
method = "METHOD_LEVELUP_DEF_OVER_ATK"
parameter = 20
target_species = "SPECIES_HITMONCHAN"

[[evolutions.entries]]
slot = 1
method = "METHOD_LEVELUP_ATK_OVER_DEF"
parameter = 20
target_species = "SPECIES_HITMONLEE"

[[evolutions.entries]]
slot = 2
method = "METHOD_LEVELUP_ATK_EQU_DEF"
parameter = 20
target_species = "SPECIES_HITMONTOP"

[[evolutions.entries]]
slot = 3
method = "METHOD_NONE"
parameter = 0
target_species = "SPECIES_NONE"

[[evolutions.entries]]
slot = 4
method = "METHOD_NONE"
parameter = 0
target_species = "SPECIES_NONE"

[[evolutions.entries]]
slot = 5
method = "METHOD_NONE"
parameter = 0
target_species = "SPECIES_NONE"

[[evolutions.entries]]
slot = 6
method = "METHOD_NONE"
parameter = 0
target_species = "SPECIES_NONE"
