[evolutions]
index = 318
species = "SPECIES_CARVANHA"

[[evolutions.entries]]
slot = 0
method = "METHOD_LEVELUP"
parameter = 30
target_species = "SPECIES_SHARPEDO"

[[evolutions.entries]]
slot = 1
method = "METHOD_NONE"
parameter = 0
target_species = "SPECIES_NONE"

[[evolutions.entries]]
slot = 2
method = "METHOD_NONE"
parameter = 0
target_species = "SPECIES_NONE"

[[evolutions.entries]]
slot = 3
method = "METHOD_NONE"
parameter = 0
target_species = "SPECIES_NONE"

[[evolutions.entries]]
slot = 4
method = "METHOD_NONE"
parameter = 0
target_species = "SPECIES_NONE"

[[evolutions.entries]]
slot = 5
method = "METHOD_NONE"
parameter = 0
target_species = "SPECIES_NONE"

[[evolutions.entries]]
slot = 6
method = "METHOD_NONE"
parameter = 0
target_species = "SPECIES_NONE"
