[evolutions]
index = 349
species = "SPECIES_FEEBAS"

[[evolutions.entries]]
slot = 0
method = "METHOD_BEAUTY"
parameter = 170
target_species = "SPECIES_MILOTIC"

[[evolutions.entries]]
slot = 1
method = "METHOD_TRADE_ITEM"
parameter = 537
target_species = "SPECIES_MILOTIC"

[[evolutions.entries]]
slot = 2
method = "METHOD_NONE"
parameter = 0
target_species = "SPECIES_NONE"

[[evolutions.entries]]
slot = 3
method = "METHOD_NONE"
parameter = 0
target_species = "SPECIES_NONE"

[[evolutions.entries]]
slot = 4
method = "METHOD_NONE"
parameter = 0
target_species = "SPECIES_NONE"

[[evolutions.entries]]
slot = 5
method = "METHOD_NONE"
parameter = 0
target_species = "SPECIES_NONE"

[[evolutions.entries]]
slot = 6
method = "METHOD_NONE"
parameter = 0
target_species = "SPECIES_NONE"
