[learnset]
index = 1
species = "SPECIES_BULBASAUR"

[[learnset.entries]]
slot = 0
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_GROWL"
level = 3

[[learnset.entries]]
slot = 2
move = "MOVE_LEECH_SEED"
level = 7

[[learnset.entries]]
slot = 3
move = "MOVE_VINE_WHIP"
level = 9

[[learnset.entries]]
slot = 4
move = "MOVE_POISONPOWDER"
level = 13

[[learnset.entries]]
slot = 5
move = "MOVE_SLEEP_POWDER"
level = 13

[[learnset.entries]]
slot = 6
move = "MOVE_TAKE_DOWN"
level = 15

[[learnset.entries]]
slot = 7
move = "MOVE_RAZOR_LEAF"
level = 19

[[learnset.entries]]
slot = 8
move = "MOVE_SWEET_SCENT"
level = 21

[[learnset.entries]]
slot = 9
move = "MOVE_GROWTH"
level = 25

[[learnset.entries]]
slot = 10
move = "MOVE_DOUBLEEDGE"
level = 27

[[learnset.entries]]
slot = 11
move = "MOVE_WORRY_SEED"
level = 31

[[learnset.entries]]
slot = 12
move = "MOVE_SYNTHESIS"
level = 33

[[learnset.entries]]
slot = 13
move = "MOVE_SEED_BOMB"
level = 37
