[learnset]
index = 6
species = "SPECIES_CHARIZARD"

[[learnset.entries]]
slot = 0
move = "MOVE_DRAGON_CLAW"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_SHADOW_CLAW"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_AIR_SLASH"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_SCRATCH"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_GROWL"
level = 1

[[learnset.entries]]
slot = 5
move = "MOVE_EMBER"
level = 1

[[learnset.entries]]
slot = 6
move = "MOVE_SMOKESCREEN"
level = 1

[[learnset.entries]]
slot = 7
move = "MOVE_EMBER"
level = 7

[[learnset.entries]]
slot = 8
move = "MOVE_SMOKESCREEN"
level = 10

[[learnset.entries]]
slot = 9
move = "MOVE_DRAGON_RAGE"
level = 17

[[learnset.entries]]
slot = 10
move = "MOVE_SCARY_FACE"
level = 21

[[learnset.entries]]
slot = 11
move = "MOVE_FIRE_FANG"
level = 28

[[learnset.entries]]
slot = 12
move = "MOVE_FLAME_BURST"
level = 32

[[learnset.entries]]
slot = 13
move = "MOVE_WING_ATTACK"
level = 36

[[learnset.entries]]
slot = 14
move = "MOVE_SLASH"
level = 41

[[learnset.entries]]
slot = 15
move = "MOVE_FLAMETHROWER"
level = 47

[[learnset.entries]]
slot = 16
move = "MOVE_FIRE_SPIN"
level = 56

[[learnset.entries]]
slot = 17
move = "MOVE_INFERNO"
level = 62

[[learnset.entries]]
slot = 18
move = "MOVE_HEAT_WAVE"
level = 71

[[learnset.entries]]
slot = 19
move = "MOVE_FLARE_BLITZ"
level = 77
