[learnset]
index = 10
species = "SPECIES_CATERPIE"

[[learnset.entries]]
slot = 0
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_STRING_SHOT"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_BUG_BITE"
level = 15
