[learnset]
index = 18
species = "SPECIES_PIDGEOT"

[[learnset.entries]]
slot = 0
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_SANDATTACK"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_GUST"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_QUICK_ATTACK"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_SANDATTACK"
level = 5

[[learnset.entries]]
slot = 5
move = "MOVE_GUST"
level = 9

[[learnset.entries]]
slot = 6
move = "MOVE_QUICK_ATTACK"
level = 13

[[learnset.entries]]
slot = 7
move = "MOVE_WHIRLWIND"
level = 17

[[learnset.entries]]
slot = 8
move = "MOVE_TWISTER"
level = 22

[[learnset.entries]]
slot = 9
move = "MOVE_FEATHERDANCE"
level = 27

[[learnset.entries]]
slot = 10
move = "MOVE_AGILITY"
level = 32

[[learnset.entries]]
slot = 11
move = "MOVE_WING_ATTACK"
level = 38

[[learnset.entries]]
slot = 12
move = "MOVE_ROOST"
level = 44

[[learnset.entries]]
slot = 13
move = "MOVE_TAILWIND"
level = 50

[[learnset.entries]]
slot = 14
move = "MOVE_MIRROR_MOVE"
level = 56

[[learnset.entries]]
slot = 15
move = "MOVE_AIR_SLASH"
level = 62

[[learnset.entries]]
slot = 16
move = "MOVE_HURRICANE"
level = 68
