[learnset]
index = 23
species = "SPECIES_EKANS"

[[learnset.entries]]
slot = 0
move = "MOVE_WRAP"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_LEER"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_POISON_STING"
level = 4

[[learnset.entries]]
slot = 3
move = "MOVE_BITE"
level = 9

[[learnset.entries]]
slot = 4
move = "MOVE_GLARE"
level = 12

[[learnset.entries]]
slot = 5
move = "MOVE_SCREECH"
level = 17

[[learnset.entries]]
slot = 6
move = "MOVE_ACID"
level = 20

[[learnset.entries]]
slot = 7
move = "MOVE_STOCKPILE"
level = 25

[[learnset.entries]]
slot = 8
move = "MOVE_SWALLOW"
level = 25

[[learnset.entries]]
slot = 9
move = "MOVE_SPIT_UP"
level = 25

[[learnset.entries]]
slot = 10
move = "MOVE_ACID_SPRAY"
level = 28

[[learnset.entries]]
slot = 11
move = "MOVE_MUD_BOMB"
level = 33

[[learnset.entries]]
slot = 12
move = "MOVE_GASTRO_ACID"
level = 36

[[learnset.entries]]
slot = 13
move = "MOVE_HAZE"
level = 41

[[learnset.entries]]
slot = 14
move = "MOVE_COIL"
level = 44

[[learnset.entries]]
slot = 15
move = "MOVE_GUNK_SHOT"
level = 49
