[learnset]
index = 28
species = "SPECIES_SANDSLASH"

[[learnset.entries]]
slot = 0
move = "MOVE_SCRATCH"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_DEFENSE_CURL"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_SANDATTACK"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_POISON_STING"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_SANDATTACK"
level = 3

[[learnset.entries]]
slot = 5
move = "MOVE_POISON_STING"
level = 5

[[learnset.entries]]
slot = 6
move = "MOVE_ROLLOUT"
level = 7

[[learnset.entries]]
slot = 7
move = "MOVE_RAPID_SPIN"
level = 9

[[learnset.entries]]
slot = 8
move = "MOVE_SWIFT"
level = 11

[[learnset.entries]]
slot = 9
move = "MOVE_FURY_CUTTER"
level = 14

[[learnset.entries]]
slot = 10
move = "MOVE_MAGNITUDE"
level = 17

[[learnset.entries]]
slot = 11
move = "MOVE_FURY_SWIPES"
level = 20

[[learnset.entries]]
slot = 12
move = "MOVE_CRUSH_CLAW"
level = 22

[[learnset.entries]]
slot = 13
move = "MOVE_SAND_TOMB"
level = 23

[[learnset.entries]]
slot = 14
move = "MOVE_SLASH"
level = 26

[[learnset.entries]]
slot = 15
move = "MOVE_DIG"
level = 30

[[learnset.entries]]
slot = 16
move = "MOVE_GYRO_BALL"
level = 34

[[learnset.entries]]
slot = 17
move = "MOVE_SWORDS_DANCE"
level = 38

[[learnset.entries]]
slot = 18
move = "MOVE_SANDSTORM"
level = 42

[[learnset.entries]]
slot = 19
move = "MOVE_EARTHQUAKE"
level = 46
