[learnset]
index = 34
species = "SPECIES_NIDOKING"

[[learnset.entries]]
slot = 0
move = "MOVE_PECK"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_FOCUS_ENERGY"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_DOUBLE_KICK"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_POISON_STING"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_CHIP_AWAY"
level = 23

[[learnset.entries]]
slot = 5
move = "MOVE_THRASH"
level = 35

[[learnset.entries]]
slot = 6
move = "MOVE_EARTH_POWER"
level = 43

[[learnset.entries]]
slot = 7
move = "MOVE_MEGAHORN"
level = 58
