[learnset]
index = 36
species = "SPECIES_CLEFABLE"

[[learnset.entries]]
slot = 0
move = "MOVE_SING"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_DOUBLESLAP"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_MINIMIZE"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_METRONOME"
level = 1
