[learnset]
index = 40
species = "SPECIES_WIGGLYTUFF"

[[learnset.entries]]
slot = 0
move = "MOVE_SING"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_DISABLE"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_DEFENSE_CURL"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_DOUBLESLAP"
level = 1
