[learnset]
index = 42
species = "SPECIES_GOLBAT"

[[learnset.entries]]
slot = 0
move = "MOVE_SCREECH"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_LEECH_LIFE"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_SUPERSONIC"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_ASTONISH"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_SUPERSONIC"
level = 4

[[learnset.entries]]
slot = 5
move = "MOVE_ASTONISH"
level = 8

[[learnset.entries]]
slot = 6
move = "MOVE_BITE"
level = 12

[[learnset.entries]]
slot = 7
move = "MOVE_WING_ATTACK"
level = 15

[[learnset.entries]]
slot = 8
move = "MOVE_CONFUSE_RAY"
level = 19

[[learnset.entries]]
slot = 9
move = "MOVE_SWIFT"
level = 24

[[learnset.entries]]
slot = 10
move = "MOVE_AIR_CUTTER"
level = 28

[[learnset.entries]]
slot = 11
move = "MOVE_ACROBATICS"
level = 33

[[learnset.entries]]
slot = 12
move = "MOVE_MEAN_LOOK"
level = 38

[[learnset.entries]]
slot = 13
move = "MOVE_POISON_FANG"
level = 42

[[learnset.entries]]
slot = 14
move = "MOVE_HAZE"
level = 47

[[learnset.entries]]
slot = 15
move = "MOVE_AIR_SLASH"
level = 52
