[learnset]
index = 45
species = "SPECIES_VILEPLUME"

[[learnset.entries]]
slot = 0
move = "MOVE_MEGA_DRAIN"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_AROMATHERAPY"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_STUN_SPORE"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_POISONPOWDER"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_PETAL_DANCE"
level = 53

[[learnset.entries]]
slot = 5
move = "MOVE_SOLARBEAM"
level = 65
