[learnset]
index = 49
species = "SPECIES_VENOMOTH"

[[learnset.entries]]
slot = 0
move = "MOVE_SILVER_WIND"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_DISABLE"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_FORESIGHT"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_SUPERSONIC"
level = 1

[[learnset.entries]]
slot = 5
move = "MOVE_SUPERSONIC"
level = 5

[[learnset.entries]]
slot = 6
move = "MOVE_CONFUSION"
level = 11

[[learnset.entries]]
slot = 7
move = "MOVE_POISONPOWDER"
level = 13

[[learnset.entries]]
slot = 8
move = "MOVE_LEECH_LIFE"
level = 17

[[learnset.entries]]
slot = 9
move = "MOVE_STUN_SPORE"
level = 23

[[learnset.entries]]
slot = 10
move = "MOVE_PSYBEAM"
level = 25

[[learnset.entries]]
slot = 11
move = "MOVE_SLEEP_POWDER"
level = 29

[[learnset.entries]]
slot = 12
move = "MOVE_GUST"
level = 31

[[learnset.entries]]
slot = 13
move = "MOVE_SIGNAL_BEAM"
level = 37

[[learnset.entries]]
slot = 14
move = "MOVE_ZEN_HEADBUTT"
level = 41

[[learnset.entries]]
slot = 15
move = "MOVE_POISON_FANG"
level = 47

[[learnset.entries]]
slot = 16
move = "MOVE_PSYCHIC"
level = 55

[[learnset.entries]]
slot = 17
move = "MOVE_BUG_BUZZ"
level = 59

[[learnset.entries]]
slot = 18
move = "MOVE_QUIVER_DANCE"
level = 63
