[learnset]
index = 52
species = "SPECIES_MEOWTH"

[[learnset.entries]]
slot = 0
move = "MOVE_SCRATCH"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_GROWL"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_BITE"
level = 6

[[learnset.entries]]
slot = 3
move = "MOVE_FAKE_OUT"
level = 9

[[learnset.entries]]
slot = 4
move = "MOVE_FURY_SWIPES"
level = 14

[[learnset.entries]]
slot = 5
move = "MOVE_SCREECH"
level = 17

[[learnset.entries]]
slot = 6
move = "MOVE_FAINT_ATTACK"
level = 22

[[learnset.entries]]
slot = 7
move = "MOVE_TAUNT"
level = 25

[[learnset.entries]]
slot = 8
move = "MOVE_PAY_DAY"
level = 30

[[learnset.entries]]
slot = 9
move = "MOVE_SLASH"
level = 33

[[learnset.entries]]
slot = 10
move = "MOVE_NASTY_PLOT"
level = 38

[[learnset.entries]]
slot = 11
move = "MOVE_ASSURANCE"
level = 41

[[learnset.entries]]
slot = 12
move = "MOVE_CAPTIVATE"
level = 46

[[learnset.entries]]
slot = 13
move = "MOVE_NIGHT_SLASH"
level = 49

[[learnset.entries]]
slot = 14
move = "MOVE_FEINT"
level = 54
