[learnset]
index = 53
species = "SPECIES_PERSIAN"

[[learnset.entries]]
slot = 0
move = "MOVE_SWITCHEROO"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_SCRATCH"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_GROWL"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_BITE"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_FAKE_OUT"
level = 1

[[learnset.entries]]
slot = 5
move = "MOVE_BITE"
level = 6

[[learnset.entries]]
slot = 6
move = "MOVE_FAKE_OUT"
level = 9

[[learnset.entries]]
slot = 7
move = "MOVE_FURY_SWIPES"
level = 14

[[learnset.entries]]
slot = 8
move = "MOVE_SCREECH"
level = 17

[[learnset.entries]]
slot = 9
move = "MOVE_FAINT_ATTACK"
level = 22

[[learnset.entries]]
slot = 10
move = "MOVE_TAUNT"
level = 25

[[learnset.entries]]
slot = 11
move = "MOVE_SWIFT"
level = 28

[[learnset.entries]]
slot = 12
move = "MOVE_POWER_GEM"
level = 32

[[learnset.entries]]
slot = 13
move = "MOVE_SLASH"
level = 37

[[learnset.entries]]
slot = 14
move = "MOVE_NASTY_PLOT"
level = 44

[[learnset.entries]]
slot = 15
move = "MOVE_ASSURANCE"
level = 49

[[learnset.entries]]
slot = 16
move = "MOVE_CAPTIVATE"
level = 56

[[learnset.entries]]
slot = 17
move = "MOVE_NIGHT_SLASH"
level = 61

[[learnset.entries]]
slot = 18
move = "MOVE_FEINT"
level = 68
