[learnset]
index = 57
species = "SPECIES_PRIMEAPE"

[[learnset.entries]]
slot = 0
move = "MOVE_FLING"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_SCRATCH"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_LOW_KICK"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_LEER"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_FOCUS_ENERGY"
level = 1

[[learnset.entries]]
slot = 5
move = "MOVE_FURY_SWIPES"
level = 9

[[learnset.entries]]
slot = 6
move = "MOVE_KARATE_CHOP"
level = 13

[[learnset.entries]]
slot = 7
move = "MOVE_SEISMIC_TOSS"
level = 17

[[learnset.entries]]
slot = 8
move = "MOVE_SCREECH"
level = 21

[[learnset.entries]]
slot = 9
move = "MOVE_ASSURANCE"
level = 25

[[learnset.entries]]
slot = 10
move = "MOVE_RAGE"
level = 28

[[learnset.entries]]
slot = 11
move = "MOVE_SWAGGER"
level = 35

[[learnset.entries]]
slot = 12
move = "MOVE_CROSS_CHOP"
level = 41

[[learnset.entries]]
slot = 13
move = "MOVE_THRASH"
level = 47

[[learnset.entries]]
slot = 14
move = "MOVE_PUNISHMENT"
level = 53

[[learnset.entries]]
slot = 15
move = "MOVE_CLOSE_COMBAT"
level = 59

[[learnset.entries]]
slot = 16
move = "MOVE_FINAL_GAMBIT"
level = 63
