[learnset]
index = 59
species = "SPECIES_ARCANINE"

[[learnset.entries]]
slot = 0
move = "MOVE_THUNDER_FANG"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_BITE"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_ROAR"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_ODOR_SLEUTH"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_FIRE_FANG"
level = 1

[[learnset.entries]]
slot = 5
move = "MOVE_EXTREMESPEED"
level = 34
