[learnset]
index = 62
species = "SPECIES_POLIWRATH"

[[learnset.entries]]
slot = 0
move = "MOVE_BUBBLEBEAM"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_HYPNOSIS"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_DOUBLESLAP"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_SUBMISSION"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_DYNAMICPUNCH"
level = 32

[[learnset.entries]]
slot = 5
move = "MOVE_MIND_READER"
level = 43

[[learnset.entries]]
slot = 6
move = "MOVE_CIRCLE_THROW"
level = 53
