[learnset]
index = 64
species = "SPECIES_KADABRA"

[[learnset.entries]]
slot = 0
move = "MOVE_TELEPORT"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_KINESIS"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_CONFUSION"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_CONFUSION"
level = 16

[[learnset.entries]]
slot = 4
move = "MOVE_DISABLE"
level = 18

[[learnset.entries]]
slot = 5
move = "MOVE_MIRACLE_EYE"
level = 22

[[learnset.entries]]
slot = 6
move = "MOVE_ALLY_SWITCH"
level = 24

[[learnset.entries]]
slot = 7
move = "MOVE_PSYBEAM"
level = 28

[[learnset.entries]]
slot = 8
move = "MOVE_REFLECT"
level = 30

[[learnset.entries]]
slot = 9
move = "MOVE_TELEKINESIS"
level = 34

[[learnset.entries]]
slot = 10
move = "MOVE_RECOVER"
level = 36

[[learnset.entries]]
slot = 11
move = "MOVE_PSYCHO_CUT"
level = 40

[[learnset.entries]]
slot = 12
move = "MOVE_ROLE_PLAY"
level = 42

[[learnset.entries]]
slot = 13
move = "MOVE_PSYCHIC"
level = 46

[[learnset.entries]]
slot = 14
move = "MOVE_FUTURE_SIGHT"
level = 48

[[learnset.entries]]
slot = 15
move = "MOVE_TRICK"
level = 52
