[learnset]
index = 68
species = "SPECIES_MACHAMP"

[[learnset.entries]]
slot = 0
move = "MOVE_WIDE_GUARD"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_LOW_KICK"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_LEER"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_FOCUS_ENERGY"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_KARATE_CHOP"
level = 1

[[learnset.entries]]
slot = 5
move = "MOVE_FOCUS_ENERGY"
level = 7

[[learnset.entries]]
slot = 6
move = "MOVE_KARATE_CHOP"
level = 10

[[learnset.entries]]
slot = 7
move = "MOVE_LOW_SWEEP"
level = 13

[[learnset.entries]]
slot = 8
move = "MOVE_FORESIGHT"
level = 19

[[learnset.entries]]
slot = 9
move = "MOVE_SEISMIC_TOSS"
level = 22

[[learnset.entries]]
slot = 10
move = "MOVE_REVENGE"
level = 25

[[learnset.entries]]
slot = 11
move = "MOVE_VITAL_THROW"
level = 32

[[learnset.entries]]
slot = 12
move = "MOVE_SUBMISSION"
level = 36

[[learnset.entries]]
slot = 13
move = "MOVE_WAKEUP_SLAP"
level = 40

[[learnset.entries]]
slot = 14
move = "MOVE_CROSS_CHOP"
level = 44

[[learnset.entries]]
slot = 15
move = "MOVE_SCARY_FACE"
level = 51

[[learnset.entries]]
slot = 16
move = "MOVE_DYNAMICPUNCH"
level = 55
