[learnset]
index = 73
species = "SPECIES_TENTACRUEL"

[[learnset.entries]]
slot = 0
move = "MOVE_POISON_STING"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_SUPERSONIC"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_CONSTRICT"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_SUPERSONIC"
level = 5

[[learnset.entries]]
slot = 4
move = "MOVE_CONSTRICT"
level = 8

[[learnset.entries]]
slot = 5
move = "MOVE_ACID"
level = 12

[[learnset.entries]]
slot = 6
move = "MOVE_TOXIC_SPIKES"
level = 15

[[learnset.entries]]
slot = 7
move = "MOVE_BUBBLEBEAM"
level = 19

[[learnset.entries]]
slot = 8
move = "MOVE_WRAP"
level = 22

[[learnset.entries]]
slot = 9
move = "MOVE_ACID_SPRAY"
level = 26

[[learnset.entries]]
slot = 10
move = "MOVE_BARRIER"
level = 29

[[learnset.entries]]
slot = 11
move = "MOVE_WATER_PULSE"
level = 34

[[learnset.entries]]
slot = 12
move = "MOVE_POISON_JAB"
level = 38

[[learnset.entries]]
slot = 13
move = "MOVE_SCREECH"
level = 43

[[learnset.entries]]
slot = 14
move = "MOVE_HEX"
level = 47

[[learnset.entries]]
slot = 15
move = "MOVE_HYDRO_PUMP"
level = 52

[[learnset.entries]]
slot = 16
move = "MOVE_SLUDGE_WAVE"
level = 56

[[learnset.entries]]
slot = 17
move = "MOVE_WRING_OUT"
level = 61
