[learnset]
index = 74
species = "SPECIES_GEODUDE"

[[learnset.entries]]
slot = 0
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_DEFENSE_CURL"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_MUD_SPORT"
level = 4

[[learnset.entries]]
slot = 3
move = "MOVE_ROCK_POLISH"
level = 8

[[learnset.entries]]
slot = 4
move = "MOVE_ROCK_THROW"
level = 11

[[learnset.entries]]
slot = 5
move = "MOVE_MAGNITUDE"
level = 15

[[learnset.entries]]
slot = 6
move = "MOVE_ROLLOUT"
level = 18

[[learnset.entries]]
slot = 7
move = "MOVE_ROCK_BLAST"
level = 22

[[learnset.entries]]
slot = 8
move = "MOVE_SMACK_DOWN"
level = 25

[[learnset.entries]]
slot = 9
move = "MOVE_SELFDESTRUCT"
level = 29

[[learnset.entries]]
slot = 10
move = "MOVE_BULLDOZE"
level = 32

[[learnset.entries]]
slot = 11
move = "MOVE_STEALTH_ROCK"
level = 36

[[learnset.entries]]
slot = 12
move = "MOVE_EARTHQUAKE"
level = 39

[[learnset.entries]]
slot = 13
move = "MOVE_EXPLOSION"
level = 43

[[learnset.entries]]
slot = 14
move = "MOVE_DOUBLEEDGE"
level = 46

[[learnset.entries]]
slot = 15
move = "MOVE_STONE_EDGE"
level = 50
