[learnset]
index = 84
species = "SPECIES_DODUO"

[[learnset.entries]]
slot = 0
move = "MOVE_PECK"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_GROWL"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_QUICK_ATTACK"
level = 5

[[learnset.entries]]
slot = 3
move = "MOVE_RAGE"
level = 10

[[learnset.entries]]
slot = 4
move = "MOVE_FURY_ATTACK"
level = 14

[[learnset.entries]]
slot = 5
move = "MOVE_PURSUIT"
level = 19

[[learnset.entries]]
slot = 6
move = "MOVE_UPROAR"
level = 23

[[learnset.entries]]
slot = 7
move = "MOVE_ACUPRESSURE"
level = 28

[[learnset.entries]]
slot = 8
move = "MOVE_DOUBLE_HIT"
level = 32

[[learnset.entries]]
slot = 9
move = "MOVE_AGILITY"
level = 37

[[learnset.entries]]
slot = 10
move = "MOVE_DRILL_PECK"
level = 41

[[learnset.entries]]
slot = 11
move = "MOVE_ENDEAVOR"
level = 46

[[learnset.entries]]
slot = 12
move = "MOVE_THRASH"
level = 50
