[learnset]
index = 91
species = "SPECIES_CLOYSTER"

[[learnset.entries]]
slot = 0
move = "MOVE_TOXIC_SPIKES"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_WITHDRAW"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_SUPERSONIC"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_PROTECT"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_AURORA_BEAM"
level = 1

[[learnset.entries]]
slot = 5
move = "MOVE_SPIKE_CANNON"
level = 13

[[learnset.entries]]
slot = 6
move = "MOVE_SPIKES"
level = 28

[[learnset.entries]]
slot = 7
move = "MOVE_ICICLE_CRASH"
level = 52
