[learnset]
index = 94
species = "SPECIES_GENGAR"

[[learnset.entries]]
slot = 0
move = "MOVE_HYPNOSIS"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_LICK"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_SPITE"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_SPITE"
level = 5

[[learnset.entries]]
slot = 4
move = "MOVE_MEAN_LOOK"
level = 8

[[learnset.entries]]
slot = 5
move = "MOVE_CURSE"
level = 12

[[learnset.entries]]
slot = 6
move = "MOVE_NIGHT_SHADE"
level = 15

[[learnset.entries]]
slot = 7
move = "MOVE_CONFUSE_RAY"
level = 19

[[learnset.entries]]
slot = 8
move = "MOVE_SUCKER_PUNCH"
level = 22

[[learnset.entries]]
slot = 9
move = "MOVE_SHADOW_PUNCH"
level = 25

[[learnset.entries]]
slot = 10
move = "MOVE_PAYBACK"
level = 28

[[learnset.entries]]
slot = 11
move = "MOVE_SHADOW_BALL"
level = 33

[[learnset.entries]]
slot = 12
move = "MOVE_DREAM_EATER"
level = 39

[[learnset.entries]]
slot = 13
move = "MOVE_DARK_PULSE"
level = 44

[[learnset.entries]]
slot = 14
move = "MOVE_DESTINY_BOND"
level = 50

[[learnset.entries]]
slot = 15
move = "MOVE_HEX"
level = 55

[[learnset.entries]]
slot = 16
move = "MOVE_NIGHTMARE"
level = 61
