[learnset]
index = 95
species = "SPECIES_ONIX"

[[learnset.entries]]
slot = 0
move = "MOVE_MUD_SPORT"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_HARDEN"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_BIND"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_CURSE"
level = 4

[[learnset.entries]]
slot = 5
move = "MOVE_ROCK_THROW"
level = 7

[[learnset.entries]]
slot = 6
move = "MOVE_RAGE"
level = 10

[[learnset.entries]]
slot = 7
move = "MOVE_ROCK_TOMB"
level = 13

[[learnset.entries]]
slot = 8
move = "MOVE_STEALTH_ROCK"
level = 16

[[learnset.entries]]
slot = 9
move = "MOVE_ROCK_POLISH"
level = 19

[[learnset.entries]]
slot = 10
move = "MOVE_SMACK_DOWN"
level = 22

[[learnset.entries]]
slot = 11
move = "MOVE_DRAGONBREATH"
level = 25

[[learnset.entries]]
slot = 12
move = "MOVE_SLAM"
level = 28

[[learnset.entries]]
slot = 13
move = "MOVE_SCREECH"
level = 31

[[learnset.entries]]
slot = 14
move = "MOVE_ROCK_SLIDE"
level = 34

[[learnset.entries]]
slot = 15
move = "MOVE_SAND_TOMB"
level = 37

[[learnset.entries]]
slot = 16
move = "MOVE_IRON_TAIL"
level = 40

[[learnset.entries]]
slot = 17
move = "MOVE_DIG"
level = 43

[[learnset.entries]]
slot = 18
move = "MOVE_STONE_EDGE"
level = 46

[[learnset.entries]]
slot = 19
move = "MOVE_DOUBLEEDGE"
level = 49

[[learnset.entries]]
slot = 20
move = "MOVE_SANDSTORM"
level = 52
