[learnset]
index = 96
species = "SPECIES_DROWZEE"

[[learnset.entries]]
slot = 0
move = "MOVE_POUND"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_HYPNOSIS"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_DISABLE"
level = 5

[[learnset.entries]]
slot = 3
move = "MOVE_CONFUSION"
level = 9

[[learnset.entries]]
slot = 4
move = "MOVE_HEADBUTT"
level = 13

[[learnset.entries]]
slot = 5
move = "MOVE_POISON_GAS"
level = 17

[[learnset.entries]]
slot = 6
move = "MOVE_MEDITATE"
level = 21

[[learnset.entries]]
slot = 7
move = "MOVE_PSYBEAM"
level = 25

[[learnset.entries]]
slot = 8
move = "MOVE_HEADBUTT"
level = 29

[[learnset.entries]]
slot = 9
move = "MOVE_PSYCH_UP"
level = 33

[[learnset.entries]]
slot = 10
move = "MOVE_SYNCHRONOISE"
level = 37

[[learnset.entries]]
slot = 11
move = "MOVE_ZEN_HEADBUTT"
level = 41

[[learnset.entries]]
slot = 12
move = "MOVE_SWAGGER"
level = 45

[[learnset.entries]]
slot = 13
move = "MOVE_PSYCHIC"
level = 49

[[learnset.entries]]
slot = 14
move = "MOVE_NASTY_PLOT"
level = 53

[[learnset.entries]]
slot = 15
move = "MOVE_PSYSHOCK"
level = 57

[[learnset.entries]]
slot = 16
move = "MOVE_FUTURE_SIGHT"
level = 61
