[learnset]
index = 99
species = "SPECIES_KINGLER"

[[learnset.entries]]
slot = 0
move = "MOVE_WIDE_GUARD"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_MUD_SPORT"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_BUBBLE"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_VICEGRIP"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_LEER"
level = 1

[[learnset.entries]]
slot = 5
move = "MOVE_VICEGRIP"
level = 5

[[learnset.entries]]
slot = 6
move = "MOVE_LEER"
level = 9

[[learnset.entries]]
slot = 7
move = "MOVE_HARDEN"
level = 11

[[learnset.entries]]
slot = 8
move = "MOVE_BUBBLEBEAM"
level = 15

[[learnset.entries]]
slot = 9
move = "MOVE_MUD_SHOT"
level = 19

[[learnset.entries]]
slot = 10
move = "MOVE_METAL_CLAW"
level = 21

[[learnset.entries]]
slot = 11
move = "MOVE_STOMP"
level = 25

[[learnset.entries]]
slot = 12
move = "MOVE_PROTECT"
level = 32

[[learnset.entries]]
slot = 13
move = "MOVE_GUILLOTINE"
level = 37

[[learnset.entries]]
slot = 14
move = "MOVE_SLAM"
level = 44

[[learnset.entries]]
slot = 15
move = "MOVE_BRINE"
level = 51

[[learnset.entries]]
slot = 16
move = "MOVE_CRABHAMMER"
level = 56

[[learnset.entries]]
slot = 17
move = "MOVE_FLAIL"
level = 63
