[learnset]
index = 101
species = "SPECIES_ELECTRODE"

[[learnset.entries]]
slot = 0
move = "MOVE_CHARGE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_SONICBOOM"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_SPARK"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_TACKLE"
level = 5

[[learnset.entries]]
slot = 5
move = "MOVE_SONICBOOM"
level = 8

[[learnset.entries]]
slot = 6
move = "MOVE_SPARK"
level = 12

[[learnset.entries]]
slot = 7
move = "MOVE_ROLLOUT"
level = 15

[[learnset.entries]]
slot = 8
move = "MOVE_SCREECH"
level = 19

[[learnset.entries]]
slot = 9
move = "MOVE_CHARGE_BEAM"
level = 22

[[learnset.entries]]
slot = 10
move = "MOVE_LIGHT_SCREEN"
level = 26

[[learnset.entries]]
slot = 11
move = "MOVE_ELECTRO_BALL"
level = 29

[[learnset.entries]]
slot = 12
move = "MOVE_SELFDESTRUCT"
level = 35

[[learnset.entries]]
slot = 13
move = "MOVE_SWIFT"
level = 40

[[learnset.entries]]
slot = 14
move = "MOVE_MAGNET_RISE"
level = 46

[[learnset.entries]]
slot = 15
move = "MOVE_GYRO_BALL"
level = 51

[[learnset.entries]]
slot = 16
move = "MOVE_EXPLOSION"
level = 57

[[learnset.entries]]
slot = 17
move = "MOVE_MIRROR_COAT"
level = 62
