[learnset]
index = 102
species = "SPECIES_EXEGGCUTE"

[[learnset.entries]]
slot = 0
move = "MOVE_BARRAGE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_UPROAR"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_HYPNOSIS"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_REFLECT"
level = 7

[[learnset.entries]]
slot = 4
move = "MOVE_LEECH_SEED"
level = 11

[[learnset.entries]]
slot = 5
move = "MOVE_BULLET_SEED"
level = 17

[[learnset.entries]]
slot = 6
move = "MOVE_STUN_SPORE"
level = 19

[[learnset.entries]]
slot = 7
move = "MOVE_POISONPOWDER"
level = 21

[[learnset.entries]]
slot = 8
move = "MOVE_SLEEP_POWDER"
level = 23

[[learnset.entries]]
slot = 9
move = "MOVE_CONFUSION"
level = 27

[[learnset.entries]]
slot = 10
move = "MOVE_WORRY_SEED"
level = 33

[[learnset.entries]]
slot = 11
move = "MOVE_NATURAL_GIFT"
level = 37

[[learnset.entries]]
slot = 12
move = "MOVE_SOLARBEAM"
level = 43

[[learnset.entries]]
slot = 13
move = "MOVE_EXTRASENSORY"
level = 47

[[learnset.entries]]
slot = 14
move = "MOVE_BESTOW"
level = 53
