[learnset]
index = 103
species = "SPECIES_EXEGGUTOR"

[[learnset.entries]]
slot = 0
move = "MOVE_SEED_BOMB"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_BARRAGE"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_HYPNOSIS"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_CONFUSION"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_STOMP"
level = 1

[[learnset.entries]]
slot = 5
move = "MOVE_PSYSHOCK"
level = 17

[[learnset.entries]]
slot = 6
move = "MOVE_EGG_BOMB"
level = 27

[[learnset.entries]]
slot = 7
move = "MOVE_WOOD_HAMMER"
level = 37

[[learnset.entries]]
slot = 8
move = "MOVE_LEAF_STORM"
level = 47
