[learnset]
index = 105
species = "SPECIES_MAROWAK"

[[learnset.entries]]
slot = 0
move = "MOVE_GROWL"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_TAIL_WHIP"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_BONE_CLUB"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_HEADBUTT"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_TAIL_WHIP"
level = 3

[[learnset.entries]]
slot = 5
move = "MOVE_BONE_CLUB"
level = 7

[[learnset.entries]]
slot = 6
move = "MOVE_HEADBUTT"
level = 11

[[learnset.entries]]
slot = 7
move = "MOVE_LEER"
level = 13

[[learnset.entries]]
slot = 8
move = "MOVE_FOCUS_ENERGY"
level = 17

[[learnset.entries]]
slot = 9
move = "MOVE_BONEMERANG"
level = 21

[[learnset.entries]]
slot = 10
move = "MOVE_RAGE"
level = 23

[[learnset.entries]]
slot = 11
move = "MOVE_FALSE_SWIPE"
level = 27

[[learnset.entries]]
slot = 12
move = "MOVE_THRASH"
level = 33

[[learnset.entries]]
slot = 13
move = "MOVE_FLING"
level = 37

[[learnset.entries]]
slot = 14
move = "MOVE_BONE_RUSH"
level = 43

[[learnset.entries]]
slot = 15
move = "MOVE_ENDEAVOR"
level = 49

[[learnset.entries]]
slot = 16
move = "MOVE_DOUBLEEDGE"
level = 53

[[learnset.entries]]
slot = 17
move = "MOVE_RETALIATE"
level = 59
