[learnset]
index = 117
species = "SPECIES_SEADRA"

[[learnset.entries]]
slot = 0
move = "MOVE_BUBBLE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_SMOKESCREEN"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_LEER"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_WATER_GUN"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_SMOKESCREEN"
level = 4

[[learnset.entries]]
slot = 5
move = "MOVE_LEER"
level = 8

[[learnset.entries]]
slot = 6
move = "MOVE_WATER_GUN"
level = 11

[[learnset.entries]]
slot = 7
move = "MOVE_FOCUS_ENERGY"
level = 14

[[learnset.entries]]
slot = 8
move = "MOVE_BUBBLEBEAM"
level = 18

[[learnset.entries]]
slot = 9
move = "MOVE_AGILITY"
level = 23

[[learnset.entries]]
slot = 10
move = "MOVE_TWISTER"
level = 26

[[learnset.entries]]
slot = 11
move = "MOVE_BRINE"
level = 30

[[learnset.entries]]
slot = 12
move = "MOVE_HYDRO_PUMP"
level = 40

[[learnset.entries]]
slot = 13
move = "MOVE_DRAGON_DANCE"
level = 48

[[learnset.entries]]
slot = 14
move = "MOVE_DRAGON_PULSE"
level = 57
