[learnset]
index = 121
species = "SPECIES_STARMIE"

[[learnset.entries]]
slot = 0
move = "MOVE_WATER_GUN"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_RAPID_SPIN"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_RECOVER"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_SWIFT"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_CONFUSE_RAY"
level = 22
