[learnset]
index = 124
species = "SPECIES_JYNX"

[[learnset.entries]]
slot = 0
move = "MOVE_POUND"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_LICK"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_LOVELY_KISS"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_POWDER_SNOW"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_LICK"
level = 5

[[learnset.entries]]
slot = 5
move = "MOVE_LOVELY_KISS"
level = 8

[[learnset.entries]]
slot = 6
move = "MOVE_POWDER_SNOW"
level = 11

[[learnset.entries]]
slot = 7
move = "MOVE_DOUBLESLAP"
level = 15

[[learnset.entries]]
slot = 8
move = "MOVE_ICE_PUNCH"
level = 18

[[learnset.entries]]
slot = 9
move = "MOVE_HEART_STAMP"
level = 21

[[learnset.entries]]
slot = 10
move = "MOVE_MEAN_LOOK"
level = 25

[[learnset.entries]]
slot = 11
move = "MOVE_FAKE_TEARS"
level = 28

[[learnset.entries]]
slot = 12
move = "MOVE_WAKEUP_SLAP"
level = 33

[[learnset.entries]]
slot = 13
move = "MOVE_AVALANCHE"
level = 39

[[learnset.entries]]
slot = 14
move = "MOVE_BODY_SLAM"
level = 44

[[learnset.entries]]
slot = 15
move = "MOVE_WRING_OUT"
level = 49

[[learnset.entries]]
slot = 16
move = "MOVE_PERISH_SONG"
level = 55

[[learnset.entries]]
slot = 17
move = "MOVE_BLIZZARD"
level = 60
