[learnset]
index = 128
species = "SPECIES_TAUROS"

[[learnset.entries]]
slot = 0
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_TAIL_WHIP"
level = 3

[[learnset.entries]]
slot = 2
move = "MOVE_RAGE"
level = 5

[[learnset.entries]]
slot = 3
move = "MOVE_HORN_ATTACK"
level = 8

[[learnset.entries]]
slot = 4
move = "MOVE_SCARY_FACE"
level = 11

[[learnset.entries]]
slot = 5
move = "MOVE_PURSUIT"
level = 15

[[learnset.entries]]
slot = 6
move = "MOVE_REST"
level = 19

[[learnset.entries]]
slot = 7
move = "MOVE_PAYBACK"
level = 24

[[learnset.entries]]
slot = 8
move = "MOVE_WORK_UP"
level = 29

[[learnset.entries]]
slot = 9
move = "MOVE_ZEN_HEADBUTT"
level = 35

[[learnset.entries]]
slot = 10
move = "MOVE_TAKE_DOWN"
level = 41

[[learnset.entries]]
slot = 11
move = "MOVE_SWAGGER"
level = 48

[[learnset.entries]]
slot = 12
move = "MOVE_THRASH"
level = 55

[[learnset.entries]]
slot = 13
move = "MOVE_GIGA_IMPACT"
level = 63
