[learnset]
index = 131
species = "SPECIES_LAPRAS"

[[learnset.entries]]
slot = 0
move = "MOVE_SING"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_GROWL"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_WATER_GUN"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_MIST"
level = 4

[[learnset.entries]]
slot = 4
move = "MOVE_CONFUSE_RAY"
level = 7

[[learnset.entries]]
slot = 5
move = "MOVE_ICE_SHARD"
level = 10

[[learnset.entries]]
slot = 6
move = "MOVE_WATER_PULSE"
level = 14

[[learnset.entries]]
slot = 7
move = "MOVE_BODY_SLAM"
level = 18

[[learnset.entries]]
slot = 8
move = "MOVE_RAIN_DANCE"
level = 22

[[learnset.entries]]
slot = 9
move = "MOVE_PERISH_SONG"
level = 27

[[learnset.entries]]
slot = 10
move = "MOVE_ICE_BEAM"
level = 32

[[learnset.entries]]
slot = 11
move = "MOVE_BRINE"
level = 37

[[learnset.entries]]
slot = 12
move = "MOVE_SAFEGUARD"
level = 43

[[learnset.entries]]
slot = 13
move = "MOVE_HYDRO_PUMP"
level = 49

[[learnset.entries]]
slot = 14
move = "MOVE_SHEER_COLD"
level = 55
