[learnset]
index = 134
species = "SPECIES_VAPOREON"

[[learnset.entries]]
slot = 0
move = "MOVE_HELPING_HAND"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_TAIL_WHIP"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_SANDATTACK"
level = 5

[[learnset.entries]]
slot = 4
move = "MOVE_WATER_GUN"
level = 9

[[learnset.entries]]
slot = 5
move = "MOVE_QUICK_ATTACK"
level = 13

[[learnset.entries]]
slot = 6
move = "MOVE_WATER_PULSE"
level = 17

[[learnset.entries]]
slot = 7
move = "MOVE_AURORA_BEAM"
level = 21

[[learnset.entries]]
slot = 8
move = "MOVE_AQUA_RING"
level = 25

[[learnset.entries]]
slot = 9
move = "MOVE_ACID_ARMOR"
level = 29

[[learnset.entries]]
slot = 10
move = "MOVE_HAZE"
level = 33

[[learnset.entries]]
slot = 11
move = "MOVE_MUDDY_WATER"
level = 37

[[learnset.entries]]
slot = 12
move = "MOVE_LAST_RESORT"
level = 41

[[learnset.entries]]
slot = 13
move = "MOVE_HYDRO_PUMP"
level = 45
