[learnset]
index = 135
species = "SPECIES_JOLTEON"

[[learnset.entries]]
slot = 0
move = "MOVE_HELPING_HAND"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_TAIL_WHIP"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_SANDATTACK"
level = 5

[[learnset.entries]]
slot = 4
move = "MOVE_THUNDERSHOCK"
level = 9

[[learnset.entries]]
slot = 5
move = "MOVE_QUICK_ATTACK"
level = 13

[[learnset.entries]]
slot = 6
move = "MOVE_DOUBLE_KICK"
level = 17

[[learnset.entries]]
slot = 7
move = "MOVE_THUNDER_FANG"
level = 21

[[learnset.entries]]
slot = 8
move = "MOVE_PIN_MISSILE"
level = 25

[[learnset.entries]]
slot = 9
move = "MOVE_AGILITY"
level = 29

[[learnset.entries]]
slot = 10
move = "MOVE_THUNDER_WAVE"
level = 33

[[learnset.entries]]
slot = 11
move = "MOVE_DISCHARGE"
level = 37

[[learnset.entries]]
slot = 12
move = "MOVE_LAST_RESORT"
level = 41

[[learnset.entries]]
slot = 13
move = "MOVE_THUNDER"
level = 45
