[learnset]
index = 139
species = "SPECIES_OMASTAR"

[[learnset.entries]]
slot = 0
move = "MOVE_CONSTRICT"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_WITHDRAW"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_BITE"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_BITE"
level = 7

[[learnset.entries]]
slot = 4
move = "MOVE_WATER_GUN"
level = 10

[[learnset.entries]]
slot = 5
move = "MOVE_ROLLOUT"
level = 16

[[learnset.entries]]
slot = 6
move = "MOVE_LEER"
level = 19

[[learnset.entries]]
slot = 7
move = "MOVE_MUD_SHOT"
level = 25

[[learnset.entries]]
slot = 8
move = "MOVE_BRINE"
level = 28

[[learnset.entries]]
slot = 9
move = "MOVE_PROTECT"
level = 34

[[learnset.entries]]
slot = 10
move = "MOVE_ANCIENTPOWER"
level = 37

[[learnset.entries]]
slot = 11
move = "MOVE_SPIKE_CANNON"
level = 40

[[learnset.entries]]
slot = 12
move = "MOVE_TICKLE"
level = 48

[[learnset.entries]]
slot = 13
move = "MOVE_ROCK_BLAST"
level = 56

[[learnset.entries]]
slot = 14
move = "MOVE_SHELL_SMASH"
level = 67

[[learnset.entries]]
slot = 15
move = "MOVE_HYDRO_PUMP"
level = 75
