[learnset]
index = 144
species = "SPECIES_ARTICUNO"

[[learnset.entries]]
slot = 0
move = "MOVE_GUST"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_POWDER_SNOW"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_MIST"
level = 8

[[learnset.entries]]
slot = 3
move = "MOVE_ICE_SHARD"
level = 15

[[learnset.entries]]
slot = 4
move = "MOVE_MIND_READER"
level = 22

[[learnset.entries]]
slot = 5
move = "MOVE_ANCIENTPOWER"
level = 29

[[learnset.entries]]
slot = 6
move = "MOVE_AGILITY"
level = 36

[[learnset.entries]]
slot = 7
move = "MOVE_ICE_BEAM"
level = 43

[[learnset.entries]]
slot = 8
move = "MOVE_REFLECT"
level = 50

[[learnset.entries]]
slot = 9
move = "MOVE_ROOST"
level = 57

[[learnset.entries]]
slot = 10
move = "MOVE_TAILWIND"
level = 64

[[learnset.entries]]
slot = 11
move = "MOVE_BLIZZARD"
level = 71

[[learnset.entries]]
slot = 12
move = "MOVE_SHEER_COLD"
level = 78

[[learnset.entries]]
slot = 13
move = "MOVE_HAIL"
level = 85

[[learnset.entries]]
slot = 14
move = "MOVE_HURRICANE"
level = 92
