[learnset]
index = 145
species = "SPECIES_ZAPDOS"

[[learnset.entries]]
slot = 0
move = "MOVE_PECK"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_THUNDERSHOCK"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_THUNDER_WAVE"
level = 8

[[learnset.entries]]
slot = 3
move = "MOVE_DETECT"
level = 15

[[learnset.entries]]
slot = 4
move = "MOVE_PLUCK"
level = 22

[[learnset.entries]]
slot = 5
move = "MOVE_ANCIENTPOWER"
level = 29

[[learnset.entries]]
slot = 6
move = "MOVE_CHARGE"
level = 36

[[learnset.entries]]
slot = 7
move = "MOVE_AGILITY"
level = 43

[[learnset.entries]]
slot = 8
move = "MOVE_DISCHARGE"
level = 50

[[learnset.entries]]
slot = 9
move = "MOVE_ROOST"
level = 57

[[learnset.entries]]
slot = 10
move = "MOVE_LIGHT_SCREEN"
level = 64

[[learnset.entries]]
slot = 11
move = "MOVE_DRILL_PECK"
level = 71

[[learnset.entries]]
slot = 12
move = "MOVE_THUNDER"
level = 78

[[learnset.entries]]
slot = 13
move = "MOVE_RAIN_DANCE"
level = 85

[[learnset.entries]]
slot = 14
move = "MOVE_ZAP_CANNON"
level = 92
