[learnset]
index = 149
species = "SPECIES_DRAGONITE"

[[learnset.entries]]
slot = 0
move = "MOVE_FIRE_PUNCH"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_THUNDERPUNCH"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_ROOST"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_WRAP"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_LEER"
level = 1

[[learnset.entries]]
slot = 5
move = "MOVE_THUNDER_WAVE"
level = 1

[[learnset.entries]]
slot = 6
move = "MOVE_TWISTER"
level = 1

[[learnset.entries]]
slot = 7
move = "MOVE_THUNDER_WAVE"
level = 5

[[learnset.entries]]
slot = 8
move = "MOVE_TWISTER"
level = 11

[[learnset.entries]]
slot = 9
move = "MOVE_DRAGON_RAGE"
level = 15

[[learnset.entries]]
slot = 10
move = "MOVE_SLAM"
level = 21

[[learnset.entries]]
slot = 11
move = "MOVE_AGILITY"
level = 25

[[learnset.entries]]
slot = 12
move = "MOVE_DRAGON_TAIL"
level = 33

[[learnset.entries]]
slot = 13
move = "MOVE_AQUA_TAIL"
level = 39

[[learnset.entries]]
slot = 14
move = "MOVE_DRAGON_RUSH"
level = 47

[[learnset.entries]]
slot = 15
move = "MOVE_SAFEGUARD"
level = 53

[[learnset.entries]]
slot = 16
move = "MOVE_WING_ATTACK"
level = 55

[[learnset.entries]]
slot = 17
move = "MOVE_DRAGON_DANCE"
level = 61

[[learnset.entries]]
slot = 18
move = "MOVE_OUTRAGE"
level = 67

[[learnset.entries]]
slot = 19
move = "MOVE_HYPER_BEAM"
level = 75

[[learnset.entries]]
slot = 20
move = "MOVE_HURRICANE"
level = 81
