[learnset]
index = 150
species = "SPECIES_MEWTWO"

[[learnset.entries]]
slot = 0
move = "MOVE_CONFUSION"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_DISABLE"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_BARRIER"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_SWIFT"
level = 8

[[learnset.entries]]
slot = 4
move = "MOVE_FUTURE_SIGHT"
level = 15

[[learnset.entries]]
slot = 5
move = "MOVE_PSYCH_UP"
level = 22

[[learnset.entries]]
slot = 6
move = "MOVE_MIRACLE_EYE"
level = 29

[[learnset.entries]]
slot = 7
move = "MOVE_MIST"
level = 36

[[learnset.entries]]
slot = 8
move = "MOVE_PSYCHO_CUT"
level = 43

[[learnset.entries]]
slot = 9
move = "MOVE_AMNESIA"
level = 50

[[learnset.entries]]
slot = 10
move = "MOVE_POWER_SWAP"
level = 57

[[learnset.entries]]
slot = 11
move = "MOVE_GUARD_SWAP"
level = 57

[[learnset.entries]]
slot = 12
move = "MOVE_PSYCHIC"
level = 64

[[learnset.entries]]
slot = 13
move = "MOVE_ME_FIRST"
level = 71

[[learnset.entries]]
slot = 14
move = "MOVE_RECOVER"
level = 79

[[learnset.entries]]
slot = 15
move = "MOVE_SAFEGUARD"
level = 86

[[learnset.entries]]
slot = 16
move = "MOVE_AURA_SPHERE"
level = 93

[[learnset.entries]]
slot = 17
move = "MOVE_PSYSTRIKE"
level = 100
