[learnset]
index = 151
species = "SPECIES_MEW"

[[learnset.entries]]
slot = 0
move = "MOVE_POUND"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_REFLECT_TYPE"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_TRANSFORM"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_MEGA_PUNCH"
level = 10

[[learnset.entries]]
slot = 4
move = "MOVE_METRONOME"
level = 20

[[learnset.entries]]
slot = 5
move = "MOVE_PSYCHIC"
level = 30

[[learnset.entries]]
slot = 6
move = "MOVE_BARRIER"
level = 40

[[learnset.entries]]
slot = 7
move = "MOVE_ANCIENTPOWER"
level = 50

[[learnset.entries]]
slot = 8
move = "MOVE_AMNESIA"
level = 60

[[learnset.entries]]
slot = 9
move = "MOVE_ME_FIRST"
level = 70

[[learnset.entries]]
slot = 10
move = "MOVE_BATON_PASS"
level = 80

[[learnset.entries]]
slot = 11
move = "MOVE_NASTY_PLOT"
level = 90

[[learnset.entries]]
slot = 12
move = "MOVE_AURA_SPHERE"
level = 100
