[learnset]
index = 154
species = "SPECIES_MEGANIUM"

[[learnset.entries]]
slot = 0
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_GROWL"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_RAZOR_LEAF"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_POISONPOWDER"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_RAZOR_LEAF"
level = 6

[[learnset.entries]]
slot = 5
move = "MOVE_POISONPOWDER"
level = 9

[[learnset.entries]]
slot = 6
move = "MOVE_SYNTHESIS"
level = 12

[[learnset.entries]]
slot = 7
move = "MOVE_REFLECT"
level = 18

[[learnset.entries]]
slot = 8
move = "MOVE_MAGICAL_LEAF"
level = 22

[[learnset.entries]]
slot = 9
move = "MOVE_NATURAL_GIFT"
level = 26

[[learnset.entries]]
slot = 10
move = "MOVE_PETAL_DANCE"
level = 32

[[learnset.entries]]
slot = 11
move = "MOVE_SWEET_SCENT"
level = 34

[[learnset.entries]]
slot = 12
move = "MOVE_LIGHT_SCREEN"
level = 40

[[learnset.entries]]
slot = 13
move = "MOVE_BODY_SLAM"
level = 46

[[learnset.entries]]
slot = 14
move = "MOVE_SAFEGUARD"
level = 54

[[learnset.entries]]
slot = 15
move = "MOVE_AROMATHERAPY"
level = 60

[[learnset.entries]]
slot = 16
move = "MOVE_SOLARBEAM"
level = 66
