[learnset]
index = 157
species = "SPECIES_TYPHLOSION"

[[learnset.entries]]
slot = 0
move = "MOVE_GYRO_BALL"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_LEER"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_SMOKESCREEN"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_EMBER"
level = 1

[[learnset.entries]]
slot = 5
move = "MOVE_SMOKESCREEN"
level = 6

[[learnset.entries]]
slot = 6
move = "MOVE_EMBER"
level = 10

[[learnset.entries]]
slot = 7
move = "MOVE_QUICK_ATTACK"
level = 13

[[learnset.entries]]
slot = 8
move = "MOVE_FLAME_WHEEL"
level = 20

[[learnset.entries]]
slot = 9
move = "MOVE_DEFENSE_CURL"
level = 24

[[learnset.entries]]
slot = 10
move = "MOVE_SWIFT"
level = 31

[[learnset.entries]]
slot = 11
move = "MOVE_FLAME_CHARGE"
level = 35

[[learnset.entries]]
slot = 12
move = "MOVE_LAVA_PLUME"
level = 43

[[learnset.entries]]
slot = 13
move = "MOVE_FLAMETHROWER"
level = 48

[[learnset.entries]]
slot = 14
move = "MOVE_INFERNO"
level = 56

[[learnset.entries]]
slot = 15
move = "MOVE_ROLLOUT"
level = 61

[[learnset.entries]]
slot = 16
move = "MOVE_DOUBLEEDGE"
level = 69

[[learnset.entries]]
slot = 17
move = "MOVE_ERUPTION"
level = 74
