[learnset]
index = 161
species = "SPECIES_SENTRET"

[[learnset.entries]]
slot = 0
move = "MOVE_SCRATCH"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_FORESIGHT"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_DEFENSE_CURL"
level = 4

[[learnset.entries]]
slot = 3
move = "MOVE_QUICK_ATTACK"
level = 7

[[learnset.entries]]
slot = 4
move = "MOVE_FURY_SWIPES"
level = 13

[[learnset.entries]]
slot = 5
move = "MOVE_HELPING_HAND"
level = 16

[[learnset.entries]]
slot = 6
move = "MOVE_FOLLOW_ME"
level = 19

[[learnset.entries]]
slot = 7
move = "MOVE_SLAM"
level = 25

[[learnset.entries]]
slot = 8
move = "MOVE_REST"
level = 28

[[learnset.entries]]
slot = 9
move = "MOVE_SUCKER_PUNCH"
level = 31

[[learnset.entries]]
slot = 10
move = "MOVE_AMNESIA"
level = 36

[[learnset.entries]]
slot = 11
move = "MOVE_BATON_PASS"
level = 39

[[learnset.entries]]
slot = 12
move = "MOVE_ME_FIRST"
level = 42

[[learnset.entries]]
slot = 13
move = "MOVE_HYPER_VOICE"
level = 47
