[learnset]
index = 167
species = "SPECIES_SPINARAK"

[[learnset.entries]]
slot = 0
move = "MOVE_POISON_STING"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_STRING_SHOT"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_SCARY_FACE"
level = 5

[[learnset.entries]]
slot = 3
move = "MOVE_CONSTRICT"
level = 8

[[learnset.entries]]
slot = 4
move = "MOVE_LEECH_LIFE"
level = 12

[[learnset.entries]]
slot = 5
move = "MOVE_NIGHT_SHADE"
level = 15

[[learnset.entries]]
slot = 6
move = "MOVE_SHADOW_SNEAK"
level = 19

[[learnset.entries]]
slot = 7
move = "MOVE_FURY_SWIPES"
level = 22

[[learnset.entries]]
slot = 8
move = "MOVE_SUCKER_PUNCH"
level = 26

[[learnset.entries]]
slot = 9
move = "MOVE_SPIDER_WEB"
level = 29

[[learnset.entries]]
slot = 10
move = "MOVE_AGILITY"
level = 33

[[learnset.entries]]
slot = 11
move = "MOVE_PIN_MISSILE"
level = 36

[[learnset.entries]]
slot = 12
move = "MOVE_PSYCHIC"
level = 40

[[learnset.entries]]
slot = 13
move = "MOVE_POISON_JAB"
level = 43

[[learnset.entries]]
slot = 14
move = "MOVE_CROSS_POISON"
level = 47
