[learnset]
index = 172
species = "SPECIES_PICHU"

[[learnset.entries]]
slot = 0
move = "MOVE_THUNDERSHOCK"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_CHARM"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_TAIL_WHIP"
level = 5

[[learnset.entries]]
slot = 3
move = "MOVE_THUNDER_WAVE"
level = 10

[[learnset.entries]]
slot = 4
move = "MOVE_SWEET_KISS"
level = 13

[[learnset.entries]]
slot = 5
move = "MOVE_NASTY_PLOT"
level = 18
