[learnset]
index = 173
species = "SPECIES_CLEFFA"

[[learnset.entries]]
slot = 0
move = "MOVE_POUND"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_CHARM"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_ENCORE"
level = 4

[[learnset.entries]]
slot = 3
move = "MOVE_SING"
level = 7

[[learnset.entries]]
slot = 4
move = "MOVE_SWEET_KISS"
level = 10

[[learnset.entries]]
slot = 5
move = "MOVE_COPYCAT"
level = 13

[[learnset.entries]]
slot = 6
move = "MOVE_MAGICAL_LEAF"
level = 16
