[learnset]
index = 174
species = "SPECIES_IGGLYBUFF"

[[learnset.entries]]
slot = 0
move = "MOVE_SING"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_CHARM"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_DEFENSE_CURL"
level = 5

[[learnset.entries]]
slot = 3
move = "MOVE_POUND"
level = 9

[[learnset.entries]]
slot = 4
move = "MOVE_SWEET_KISS"
level = 13

[[learnset.entries]]
slot = 5
move = "MOVE_COPYCAT"
level = 17
