[learnset]
index = 182
species = "SPECIES_BELLOSSOM"

[[learnset.entries]]
slot = 0
move = "MOVE_LEAF_BLADE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_MEGA_DRAIN"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_SWEET_SCENT"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_STUN_SPORE"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_SUNNY_DAY"
level = 1

[[learnset.entries]]
slot = 5
move = "MOVE_MAGICAL_LEAF"
level = 23

[[learnset.entries]]
slot = 6
move = "MOVE_LEAF_STORM"
level = 53
