[learnset]
index = 186
species = "SPECIES_POLITOED"

[[learnset.entries]]
slot = 0
move = "MOVE_BUBBLEBEAM"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_HYPNOSIS"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_DOUBLESLAP"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_PERISH_SONG"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_SWAGGER"
level = 27

[[learnset.entries]]
slot = 5
move = "MOVE_BOUNCE"
level = 37

[[learnset.entries]]
slot = 6
move = "MOVE_HYPER_VOICE"
level = 48
