[learnset]
index = 188
species = "SPECIES_SKIPLOOM"

[[learnset.entries]]
slot = 0
move = "MOVE_SPLASH"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_SYNTHESIS"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_TAIL_WHIP"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_SYNTHESIS"
level = 4

[[learnset.entries]]
slot = 5
move = "MOVE_TAIL_WHIP"
level = 7

[[learnset.entries]]
slot = 6
move = "MOVE_TACKLE"
level = 10

[[learnset.entries]]
slot = 7
move = "MOVE_POISONPOWDER"
level = 12

[[learnset.entries]]
slot = 8
move = "MOVE_STUN_SPORE"
level = 14

[[learnset.entries]]
slot = 9
move = "MOVE_SLEEP_POWDER"
level = 16

[[learnset.entries]]
slot = 10
move = "MOVE_BULLET_SEED"
level = 20

[[learnset.entries]]
slot = 11
move = "MOVE_LEECH_SEED"
level = 24

[[learnset.entries]]
slot = 12
move = "MOVE_MEGA_DRAIN"
level = 28

[[learnset.entries]]
slot = 13
move = "MOVE_ACROBATICS"
level = 32

[[learnset.entries]]
slot = 14
move = "MOVE_RAGE_POWDER"
level = 36

[[learnset.entries]]
slot = 15
move = "MOVE_COTTON_SPORE"
level = 40

[[learnset.entries]]
slot = 16
move = "MOVE_UTURN"
level = 44

[[learnset.entries]]
slot = 17
move = "MOVE_WORRY_SEED"
level = 48

[[learnset.entries]]
slot = 18
move = "MOVE_GIGA_DRAIN"
level = 52

[[learnset.entries]]
slot = 19
move = "MOVE_BOUNCE"
level = 56

[[learnset.entries]]
slot = 20
move = "MOVE_MEMENTO"
level = 60
