[learnset]
index = 196
species = "SPECIES_ESPEON"

[[learnset.entries]]
slot = 0
move = "MOVE_HELPING_HAND"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_TAIL_WHIP"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_SANDATTACK"
level = 5

[[learnset.entries]]
slot = 4
move = "MOVE_CONFUSION"
level = 9

[[learnset.entries]]
slot = 5
move = "MOVE_QUICK_ATTACK"
level = 13

[[learnset.entries]]
slot = 6
move = "MOVE_SWIFT"
level = 17

[[learnset.entries]]
slot = 7
move = "MOVE_PSYBEAM"
level = 21

[[learnset.entries]]
slot = 8
move = "MOVE_FUTURE_SIGHT"
level = 25

[[learnset.entries]]
slot = 9
move = "MOVE_PSYCH_UP"
level = 29

[[learnset.entries]]
slot = 10
move = "MOVE_MORNING_SUN"
level = 33

[[learnset.entries]]
slot = 11
move = "MOVE_PSYCHIC"
level = 37

[[learnset.entries]]
slot = 12
move = "MOVE_LAST_RESORT"
level = 41

[[learnset.entries]]
slot = 13
move = "MOVE_POWER_SWAP"
level = 45
