[learnset]
index = 202
species = "SPECIES_WOBBUFFET"

[[learnset.entries]]
slot = 0
move = "MOVE_COUNTER"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_MIRROR_COAT"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_SAFEGUARD"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_DESTINY_BOND"
level = 1
