[learnset]
index = 203
species = "SPECIES_GIRAFARIG"

[[learnset.entries]]
slot = 0
move = "MOVE_POWER_SWAP"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_GUARD_SWAP"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_ASTONISH"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_GROWL"
level = 1

[[learnset.entries]]
slot = 5
move = "MOVE_CONFUSION"
level = 1

[[learnset.entries]]
slot = 6
move = "MOVE_ODOR_SLEUTH"
level = 5

[[learnset.entries]]
slot = 7
move = "MOVE_STOMP"
level = 10

[[learnset.entries]]
slot = 8
move = "MOVE_AGILITY"
level = 14

[[learnset.entries]]
slot = 9
move = "MOVE_PSYBEAM"
level = 19

[[learnset.entries]]
slot = 10
move = "MOVE_BATON_PASS"
level = 23

[[learnset.entries]]
slot = 11
move = "MOVE_ASSURANCE"
level = 28

[[learnset.entries]]
slot = 12
move = "MOVE_DOUBLE_HIT"
level = 32

[[learnset.entries]]
slot = 13
move = "MOVE_PSYCHIC"
level = 37

[[learnset.entries]]
slot = 14
move = "MOVE_ZEN_HEADBUTT"
level = 41

[[learnset.entries]]
slot = 15
move = "MOVE_CRUNCH"
level = 46
