[learnset]
index = 205
species = "SPECIES_FORRETRESS"

[[learnset.entries]]
slot = 0
move = "MOVE_TOXIC_SPIKES"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_PROTECT"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_SELFDESTRUCT"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_BUG_BITE"
level = 1

[[learnset.entries]]
slot = 5
move = "MOVE_SELFDESTRUCT"
level = 6

[[learnset.entries]]
slot = 6
move = "MOVE_BUG_BITE"
level = 9

[[learnset.entries]]
slot = 7
move = "MOVE_TAKE_DOWN"
level = 12

[[learnset.entries]]
slot = 8
move = "MOVE_RAPID_SPIN"
level = 17

[[learnset.entries]]
slot = 9
move = "MOVE_BIDE"
level = 20

[[learnset.entries]]
slot = 10
move = "MOVE_NATURAL_GIFT"
level = 23

[[learnset.entries]]
slot = 11
move = "MOVE_SPIKES"
level = 28

[[learnset.entries]]
slot = 12
move = "MOVE_MIRROR_SHOT"
level = 31

[[learnset.entries]]
slot = 13
move = "MOVE_AUTOTOMIZE"
level = 32

[[learnset.entries]]
slot = 14
move = "MOVE_PAYBACK"
level = 36

[[learnset.entries]]
slot = 15
move = "MOVE_EXPLOSION"
level = 42

[[learnset.entries]]
slot = 16
move = "MOVE_IRON_DEFENSE"
level = 46

[[learnset.entries]]
slot = 17
move = "MOVE_GYRO_BALL"
level = 50

[[learnset.entries]]
slot = 18
move = "MOVE_DOUBLEEDGE"
level = 56

[[learnset.entries]]
slot = 19
move = "MOVE_MAGNET_RISE"
level = 60

[[learnset.entries]]
slot = 20
move = "MOVE_ZAP_CANNON"
level = 64

[[learnset.entries]]
slot = 21
move = "MOVE_HEAVY_SLAM"
level = 70
