[learnset]
index = 213
species = "SPECIES_SHUCKLE"

[[learnset.entries]]
slot = 0
move = "MOVE_WITHDRAW"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_CONSTRICT"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_BIDE"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_ROLLOUT"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_ENCORE"
level = 5

[[learnset.entries]]
slot = 5
move = "MOVE_WRAP"
level = 9

[[learnset.entries]]
slot = 6
move = "MOVE_STRUGGLE_BUG"
level = 12

[[learnset.entries]]
slot = 7
move = "MOVE_SAFEGUARD"
level = 16

[[learnset.entries]]
slot = 8
move = "MOVE_REST"
level = 20

[[learnset.entries]]
slot = 9
move = "MOVE_ROCK_THROW"
level = 23

[[learnset.entries]]
slot = 10
move = "MOVE_GASTRO_ACID"
level = 27

[[learnset.entries]]
slot = 11
move = "MOVE_POWER_TRICK"
level = 31

[[learnset.entries]]
slot = 12
move = "MOVE_SHELL_SMASH"
level = 34

[[learnset.entries]]
slot = 13
move = "MOVE_ROCK_SLIDE"
level = 38

[[learnset.entries]]
slot = 14
move = "MOVE_BUG_BITE"
level = 42

[[learnset.entries]]
slot = 15
move = "MOVE_POWER_SPLIT"
level = 45

[[learnset.entries]]
slot = 16
move = "MOVE_GUARD_SPLIT"
level = 45

[[learnset.entries]]
slot = 17
move = "MOVE_STONE_EDGE"
level = 49
