[learnset]
index = 229
species = "SPECIES_HOUNDOOM"

[[learnset.entries]]
slot = 0
move = "MOVE_THUNDER_FANG"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_LEER"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_EMBER"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_HOWL"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_SMOG"
level = 1

[[learnset.entries]]
slot = 5
move = "MOVE_HOWL"
level = 4

[[learnset.entries]]
slot = 6
move = "MOVE_SMOG"
level = 8

[[learnset.entries]]
slot = 7
move = "MOVE_ROAR"
level = 13

[[learnset.entries]]
slot = 8
move = "MOVE_BITE"
level = 16

[[learnset.entries]]
slot = 9
move = "MOVE_ODOR_SLEUTH"
level = 20

[[learnset.entries]]
slot = 10
move = "MOVE_BEAT_UP"
level = 26

[[learnset.entries]]
slot = 11
move = "MOVE_FIRE_FANG"
level = 30

[[learnset.entries]]
slot = 12
move = "MOVE_FAINT_ATTACK"
level = 35

[[learnset.entries]]
slot = 13
move = "MOVE_EMBARGO"
level = 41

[[learnset.entries]]
slot = 14
move = "MOVE_FOUL_PLAY"
level = 45

[[learnset.entries]]
slot = 15
move = "MOVE_FLAMETHROWER"
level = 50

[[learnset.entries]]
slot = 16
move = "MOVE_CRUNCH"
level = 56

[[learnset.entries]]
slot = 17
move = "MOVE_NASTY_PLOT"
level = 60

[[learnset.entries]]
slot = 18
move = "MOVE_INFERNO"
level = 65
