[learnset]
index = 236
species = "SPECIES_TYROGUE"

[[learnset.entries]]
slot = 0
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_HELPING_HAND"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_FAKE_OUT"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_FORESIGHT"
level = 1
