[learnset]
index = 238
species = "SPECIES_SMOOCHUM"

[[learnset.entries]]
slot = 0
move = "MOVE_POUND"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_LICK"
level = 5

[[learnset.entries]]
slot = 2
move = "MOVE_SWEET_KISS"
level = 8

[[learnset.entries]]
slot = 3
move = "MOVE_POWDER_SNOW"
level = 11

[[learnset.entries]]
slot = 4
move = "MOVE_CONFUSION"
level = 15

[[learnset.entries]]
slot = 5
move = "MOVE_SING"
level = 18

[[learnset.entries]]
slot = 6
move = "MOVE_HEART_STAMP"
level = 21

[[learnset.entries]]
slot = 7
move = "MOVE_MEAN_LOOK"
level = 25

[[learnset.entries]]
slot = 8
move = "MOVE_FAKE_TEARS"
level = 28

[[learnset.entries]]
slot = 9
move = "MOVE_LUCKY_CHANT"
level = 31

[[learnset.entries]]
slot = 10
move = "MOVE_AVALANCHE"
level = 35

[[learnset.entries]]
slot = 11
move = "MOVE_PSYCHIC"
level = 38

[[learnset.entries]]
slot = 12
move = "MOVE_COPYCAT"
level = 41

[[learnset.entries]]
slot = 13
move = "MOVE_PERISH_SONG"
level = 45

[[learnset.entries]]
slot = 14
move = "MOVE_BLIZZARD"
level = 48
