[learnset]
index = 241
species = "SPECIES_MILTANK"

[[learnset.entries]]
slot = 0
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_GROWL"
level = 3

[[learnset.entries]]
slot = 2
move = "MOVE_DEFENSE_CURL"
level = 5

[[learnset.entries]]
slot = 3
move = "MOVE_STOMP"
level = 8

[[learnset.entries]]
slot = 4
move = "MOVE_MILK_DRINK"
level = 11

[[learnset.entries]]
slot = 5
move = "MOVE_BIDE"
level = 15

[[learnset.entries]]
slot = 6
move = "MOVE_ROLLOUT"
level = 19

[[learnset.entries]]
slot = 7
move = "MOVE_BODY_SLAM"
level = 24

[[learnset.entries]]
slot = 8
move = "MOVE_ZEN_HEADBUTT"
level = 29

[[learnset.entries]]
slot = 9
move = "MOVE_CAPTIVATE"
level = 35

[[learnset.entries]]
slot = 10
move = "MOVE_GYRO_BALL"
level = 41

[[learnset.entries]]
slot = 11
move = "MOVE_HEAL_BELL"
level = 48

[[learnset.entries]]
slot = 12
move = "MOVE_WAKEUP_SLAP"
level = 55
