[learnset]
index = 244
species = "SPECIES_ENTEI"

[[learnset.entries]]
slot = 0
move = "MOVE_BITE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_LEER"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_EMBER"
level = 8

[[learnset.entries]]
slot = 3
move = "MOVE_ROAR"
level = 15

[[learnset.entries]]
slot = 4
move = "MOVE_FIRE_SPIN"
level = 22

[[learnset.entries]]
slot = 5
move = "MOVE_STOMP"
level = 29

[[learnset.entries]]
slot = 6
move = "MOVE_FLAMETHROWER"
level = 36

[[learnset.entries]]
slot = 7
move = "MOVE_SWAGGER"
level = 43

[[learnset.entries]]
slot = 8
move = "MOVE_FIRE_FANG"
level = 50

[[learnset.entries]]
slot = 9
move = "MOVE_LAVA_PLUME"
level = 57

[[learnset.entries]]
slot = 10
move = "MOVE_EXTRASENSORY"
level = 64

[[learnset.entries]]
slot = 11
move = "MOVE_FIRE_BLAST"
level = 71

[[learnset.entries]]
slot = 12
move = "MOVE_CALM_MIND"
level = 78

[[learnset.entries]]
slot = 13
move = "MOVE_ERUPTION"
level = 85
