[learnset]
index = 250
species = "SPECIES_HOOH"

[[learnset.entries]]
slot = 0
move = "MOVE_WHIRLWIND"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_WEATHER_BALL"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_GUST"
level = 9

[[learnset.entries]]
slot = 3
move = "MOVE_BRAVE_BIRD"
level = 15

[[learnset.entries]]
slot = 4
move = "MOVE_EXTRASENSORY"
level = 23

[[learnset.entries]]
slot = 5
move = "MOVE_SUNNY_DAY"
level = 29

[[learnset.entries]]
slot = 6
move = "MOVE_FIRE_BLAST"
level = 37

[[learnset.entries]]
slot = 7
move = "MOVE_SACRED_FIRE"
level = 43

[[learnset.entries]]
slot = 8
move = "MOVE_PUNISHMENT"
level = 50

[[learnset.entries]]
slot = 9
move = "MOVE_ANCIENTPOWER"
level = 57

[[learnset.entries]]
slot = 10
move = "MOVE_SAFEGUARD"
level = 65

[[learnset.entries]]
slot = 11
move = "MOVE_RECOVER"
level = 71

[[learnset.entries]]
slot = 12
move = "MOVE_FUTURE_SIGHT"
level = 79

[[learnset.entries]]
slot = 13
move = "MOVE_NATURAL_GIFT"
level = 85

[[learnset.entries]]
slot = 14
move = "MOVE_CALM_MIND"
level = 93

[[learnset.entries]]
slot = 15
move = "MOVE_SKY_ATTACK"
level = 99
