[learnset]
index = 263
species = "SPECIES_ZIGZAGOON"

[[learnset.entries]]
slot = 0
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_GROWL"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_TAIL_WHIP"
level = 5

[[learnset.entries]]
slot = 3
move = "MOVE_HEADBUTT"
level = 9

[[learnset.entries]]
slot = 4
move = "MOVE_SANDATTACK"
level = 13

[[learnset.entries]]
slot = 5
move = "MOVE_ODOR_SLEUTH"
level = 17

[[learnset.entries]]
slot = 6
move = "MOVE_MUD_SPORT"
level = 21

[[learnset.entries]]
slot = 7
move = "MOVE_PIN_MISSILE"
level = 25

[[learnset.entries]]
slot = 8
move = "MOVE_COVET"
level = 29

[[learnset.entries]]
slot = 9
move = "MOVE_BESTOW"
level = 33

[[learnset.entries]]
slot = 10
move = "MOVE_FLAIL"
level = 37

[[learnset.entries]]
slot = 11
move = "MOVE_REST"
level = 41

[[learnset.entries]]
slot = 12
move = "MOVE_BELLY_DRUM"
level = 45

[[learnset.entries]]
slot = 13
move = "MOVE_FLING"
level = 49
