[learnset]
index = 265
species = "SPECIES_WURMPLE"

[[learnset.entries]]
slot = 0
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_STRING_SHOT"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_POISON_STING"
level = 5

[[learnset.entries]]
slot = 3
move = "MOVE_BUG_BITE"
level = 15
