[learnset]
index = 272
species = "SPECIES_LUDICOLO"

[[learnset.entries]]
slot = 0
move = "MOVE_ASTONISH"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_GROWL"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_MEGA_DRAIN"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_NATURE_POWER"
level = 1
