[learnset]
index = 273
species = "SPECIES_SEEDOT"

[[learnset.entries]]
slot = 0
move = "MOVE_BIDE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_HARDEN"
level = 3

[[learnset.entries]]
slot = 2
move = "MOVE_GROWTH"
level = 7

[[learnset.entries]]
slot = 3
move = "MOVE_NATURE_POWER"
level = 13

[[learnset.entries]]
slot = 4
move = "MOVE_SYNTHESIS"
level = 21

[[learnset.entries]]
slot = 5
move = "MOVE_SUNNY_DAY"
level = 31

[[learnset.entries]]
slot = 6
move = "MOVE_EXPLOSION"
level = 43
