[learnset]
index = 276
species = "SPECIES_TAILLOW"

[[learnset.entries]]
slot = 0
move = "MOVE_PECK"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_GROWL"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_FOCUS_ENERGY"
level = 4

[[learnset.entries]]
slot = 3
move = "MOVE_QUICK_ATTACK"
level = 8

[[learnset.entries]]
slot = 4
move = "MOVE_WING_ATTACK"
level = 13

[[learnset.entries]]
slot = 5
move = "MOVE_DOUBLE_TEAM"
level = 19

[[learnset.entries]]
slot = 6
move = "MOVE_ENDEAVOR"
level = 26

[[learnset.entries]]
slot = 7
move = "MOVE_AERIAL_ACE"
level = 34

[[learnset.entries]]
slot = 8
move = "MOVE_AGILITY"
level = 43

[[learnset.entries]]
slot = 9
move = "MOVE_AIR_SLASH"
level = 53
