[learnset]
index = 278
species = "SPECIES_WINGULL"

[[learnset.entries]]
slot = 0
move = "MOVE_GROWL"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_WATER_GUN"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_SUPERSONIC"
level = 6

[[learnset.entries]]
slot = 3
move = "MOVE_WING_ATTACK"
level = 9

[[learnset.entries]]
slot = 4
move = "MOVE_MIST"
level = 14

[[learnset.entries]]
slot = 5
move = "MOVE_WATER_PULSE"
level = 17

[[learnset.entries]]
slot = 6
move = "MOVE_QUICK_ATTACK"
level = 22

[[learnset.entries]]
slot = 7
move = "MOVE_ROOST"
level = 26

[[learnset.entries]]
slot = 8
move = "MOVE_PURSUIT"
level = 30

[[learnset.entries]]
slot = 9
move = "MOVE_AIR_CUTTER"
level = 33

[[learnset.entries]]
slot = 10
move = "MOVE_AGILITY"
level = 38

[[learnset.entries]]
slot = 11
move = "MOVE_AERIAL_ACE"
level = 42

[[learnset.entries]]
slot = 12
move = "MOVE_AIR_SLASH"
level = 46

[[learnset.entries]]
slot = 13
move = "MOVE_HURRICANE"
level = 49
