[learnset]
index = 281
species = "SPECIES_KIRLIA"

[[learnset.entries]]
slot = 0
move = "MOVE_GROWL"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_CONFUSION"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_DOUBLE_TEAM"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_TELEPORT"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_CONFUSION"
level = 6

[[learnset.entries]]
slot = 5
move = "MOVE_DOUBLE_TEAM"
level = 10

[[learnset.entries]]
slot = 6
move = "MOVE_TELEPORT"
level = 12

[[learnset.entries]]
slot = 7
move = "MOVE_LUCKY_CHANT"
level = 17

[[learnset.entries]]
slot = 8
move = "MOVE_MAGICAL_LEAF"
level = 22

[[learnset.entries]]
slot = 9
move = "MOVE_HEAL_PULSE"
level = 25

[[learnset.entries]]
slot = 10
move = "MOVE_CALM_MIND"
level = 31

[[learnset.entries]]
slot = 11
move = "MOVE_PSYCHIC"
level = 36

[[learnset.entries]]
slot = 12
move = "MOVE_IMPRISON"
level = 39

[[learnset.entries]]
slot = 13
move = "MOVE_FUTURE_SIGHT"
level = 45

[[learnset.entries]]
slot = 14
move = "MOVE_CHARM"
level = 50

[[learnset.entries]]
slot = 15
move = "MOVE_HYPNOSIS"
level = 53

[[learnset.entries]]
slot = 16
move = "MOVE_DREAM_EATER"
level = 59

[[learnset.entries]]
slot = 17
move = "MOVE_STORED_POWER"
level = 64
