[learnset]
index = 282
species = "SPECIES_GARDEVOIR"

[[learnset.entries]]
slot = 0
move = "MOVE_HEALING_WISH"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_GROWL"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_CONFUSION"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_DOUBLE_TEAM"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_TELEPORT"
level = 1

[[learnset.entries]]
slot = 5
move = "MOVE_CONFUSION"
level = 6

[[learnset.entries]]
slot = 6
move = "MOVE_DOUBLE_TEAM"
level = 10

[[learnset.entries]]
slot = 7
move = "MOVE_TELEPORT"
level = 12

[[learnset.entries]]
slot = 8
move = "MOVE_WISH"
level = 17

[[learnset.entries]]
slot = 9
move = "MOVE_MAGICAL_LEAF"
level = 22

[[learnset.entries]]
slot = 10
move = "MOVE_HEAL_PULSE"
level = 25

[[learnset.entries]]
slot = 11
move = "MOVE_CALM_MIND"
level = 33

[[learnset.entries]]
slot = 12
move = "MOVE_PSYCHIC"
level = 40

[[learnset.entries]]
slot = 13
move = "MOVE_IMPRISON"
level = 45

[[learnset.entries]]
slot = 14
move = "MOVE_FUTURE_SIGHT"
level = 53

[[learnset.entries]]
slot = 15
move = "MOVE_CAPTIVATE"
level = 60

[[learnset.entries]]
slot = 16
move = "MOVE_HYPNOSIS"
level = 65

[[learnset.entries]]
slot = 17
move = "MOVE_DREAM_EATER"
level = 73

[[learnset.entries]]
slot = 18
move = "MOVE_STORED_POWER"
level = 80
