[learnset]
index = 283
species = "SPECIES_SURSKIT"

[[learnset.entries]]
slot = 0
move = "MOVE_BUBBLE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_QUICK_ATTACK"
level = 7

[[learnset.entries]]
slot = 2
move = "MOVE_SWEET_SCENT"
level = 13

[[learnset.entries]]
slot = 3
move = "MOVE_WATER_SPORT"
level = 19

[[learnset.entries]]
slot = 4
move = "MOVE_BUBBLEBEAM"
level = 25

[[learnset.entries]]
slot = 5
move = "MOVE_AGILITY"
level = 31

[[learnset.entries]]
slot = 6
move = "MOVE_MIST"
level = 37

[[learnset.entries]]
slot = 7
move = "MOVE_HAZE"
level = 37

[[learnset.entries]]
slot = 8
move = "MOVE_BATON_PASS"
level = 43
