[learnset]
index = 286
species = "SPECIES_BRELOOM"

[[learnset.entries]]
slot = 0
move = "MOVE_ABSORB"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_STUN_SPORE"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_LEECH_SEED"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_TACKLE"
level = 5

[[learnset.entries]]
slot = 5
move = "MOVE_STUN_SPORE"
level = 9

[[learnset.entries]]
slot = 6
move = "MOVE_LEECH_SEED"
level = 13

[[learnset.entries]]
slot = 7
move = "MOVE_MEGA_DRAIN"
level = 17

[[learnset.entries]]
slot = 8
move = "MOVE_HEADBUTT"
level = 21

[[learnset.entries]]
slot = 9
move = "MOVE_MACH_PUNCH"
level = 23

[[learnset.entries]]
slot = 10
move = "MOVE_COUNTER"
level = 25

[[learnset.entries]]
slot = 11
move = "MOVE_FORCE_PALM"
level = 29

[[learnset.entries]]
slot = 12
move = "MOVE_SKY_UPPERCUT"
level = 33

[[learnset.entries]]
slot = 13
move = "MOVE_MIND_READER"
level = 37

[[learnset.entries]]
slot = 14
move = "MOVE_SEED_BOMB"
level = 41

[[learnset.entries]]
slot = 15
move = "MOVE_DYNAMICPUNCH"
level = 45
