[learnset]
index = 291
species = "SPECIES_NINJASK"

[[learnset.entries]]
slot = 0
move = "MOVE_BUG_BITE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_SCRATCH"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_HARDEN"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_LEECH_LIFE"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_SANDATTACK"
level = 1

[[learnset.entries]]
slot = 5
move = "MOVE_LEECH_LIFE"
level = 5

[[learnset.entries]]
slot = 6
move = "MOVE_SANDATTACK"
level = 9

[[learnset.entries]]
slot = 7
move = "MOVE_FURY_SWIPES"
level = 14

[[learnset.entries]]
slot = 8
move = "MOVE_MIND_READER"
level = 19

[[learnset.entries]]
slot = 9
move = "MOVE_DOUBLE_TEAM"
level = 20

[[learnset.entries]]
slot = 10
move = "MOVE_FURY_CUTTER"
level = 20

[[learnset.entries]]
slot = 11
move = "MOVE_SCREECH"
level = 20

[[learnset.entries]]
slot = 12
move = "MOVE_SWORDS_DANCE"
level = 25

[[learnset.entries]]
slot = 13
move = "MOVE_SLASH"
level = 31

[[learnset.entries]]
slot = 14
move = "MOVE_AGILITY"
level = 38

[[learnset.entries]]
slot = 15
move = "MOVE_BATON_PASS"
level = 45

[[learnset.entries]]
slot = 16
move = "MOVE_XSCISSOR"
level = 52
