[learnset]
index = 293
species = "SPECIES_WHISMUR"

[[learnset.entries]]
slot = 0
move = "MOVE_POUND"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_UPROAR"
level = 5

[[learnset.entries]]
slot = 2
move = "MOVE_ASTONISH"
level = 11

[[learnset.entries]]
slot = 3
move = "MOVE_HOWL"
level = 15

[[learnset.entries]]
slot = 4
move = "MOVE_SUPERSONIC"
level = 21

[[learnset.entries]]
slot = 5
move = "MOVE_STOMP"
level = 25

[[learnset.entries]]
slot = 6
move = "MOVE_SCREECH"
level = 31

[[learnset.entries]]
slot = 7
move = "MOVE_ROAR"
level = 35

[[learnset.entries]]
slot = 8
move = "MOVE_SYNCHRONOISE"
level = 41

[[learnset.entries]]
slot = 9
move = "MOVE_REST"
level = 45

[[learnset.entries]]
slot = 10
move = "MOVE_SLEEP_TALK"
level = 45

[[learnset.entries]]
slot = 11
move = "MOVE_HYPER_VOICE"
level = 51
