[learnset]
index = 301
species = "SPECIES_DELCATTY"

[[learnset.entries]]
slot = 0
move = "MOVE_FAKE_OUT"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_ATTRACT"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_SING"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_DOUBLESLAP"
level = 1
