[learnset]
index = 304
species = "SPECIES_ARON"

[[learnset.entries]]
slot = 0
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_HARDEN"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_MUDSLAP"
level = 4

[[learnset.entries]]
slot = 3
move = "MOVE_HEADBUTT"
level = 8

[[learnset.entries]]
slot = 4
move = "MOVE_METAL_CLAW"
level = 11

[[learnset.entries]]
slot = 5
move = "MOVE_IRON_DEFENSE"
level = 15

[[learnset.entries]]
slot = 6
move = "MOVE_ROAR"
level = 18

[[learnset.entries]]
slot = 7
move = "MOVE_TAKE_DOWN"
level = 22

[[learnset.entries]]
slot = 8
move = "MOVE_IRON_HEAD"
level = 25

[[learnset.entries]]
slot = 9
move = "MOVE_PROTECT"
level = 29

[[learnset.entries]]
slot = 10
move = "MOVE_METAL_SOUND"
level = 32

[[learnset.entries]]
slot = 11
move = "MOVE_IRON_TAIL"
level = 36

[[learnset.entries]]
slot = 12
move = "MOVE_AUTOTOMIZE"
level = 39

[[learnset.entries]]
slot = 13
move = "MOVE_HEAVY_SLAM"
level = 43

[[learnset.entries]]
slot = 14
move = "MOVE_DOUBLEEDGE"
level = 46

[[learnset.entries]]
slot = 15
move = "MOVE_METAL_BURST"
level = 50
