[learnset]
index = 317
species = "SPECIES_SWALOT"

[[learnset.entries]]
slot = 0
move = "MOVE_POUND"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_YAWN"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_POISON_GAS"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_SLUDGE"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_YAWN"
level = 6

[[learnset.entries]]
slot = 5
move = "MOVE_POISON_GAS"
level = 9

[[learnset.entries]]
slot = 6
move = "MOVE_SLUDGE"
level = 14

[[learnset.entries]]
slot = 7
move = "MOVE_AMNESIA"
level = 17

[[learnset.entries]]
slot = 8
move = "MOVE_ENCORE"
level = 23

[[learnset.entries]]
slot = 9
move = "MOVE_BODY_SLAM"
level = 26

[[learnset.entries]]
slot = 10
move = "MOVE_TOXIC"
level = 30

[[learnset.entries]]
slot = 11
move = "MOVE_ACID_SPRAY"
level = 38

[[learnset.entries]]
slot = 12
move = "MOVE_STOCKPILE"
level = 45

[[learnset.entries]]
slot = 13
move = "MOVE_SPIT_UP"
level = 45

[[learnset.entries]]
slot = 14
move = "MOVE_SWALLOW"
level = 45

[[learnset.entries]]
slot = 15
move = "MOVE_SLUDGE_BOMB"
level = 52

[[learnset.entries]]
slot = 16
move = "MOVE_GASTRO_ACID"
level = 59

[[learnset.entries]]
slot = 17
move = "MOVE_WRING_OUT"
level = 66

[[learnset.entries]]
slot = 18
move = "MOVE_GUNK_SHOT"
level = 73
