[learnset]
index = 320
species = "SPECIES_WAILMER"

[[learnset.entries]]
slot = 0
move = "MOVE_SPLASH"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_GROWL"
level = 4

[[learnset.entries]]
slot = 2
move = "MOVE_WATER_GUN"
level = 7

[[learnset.entries]]
slot = 3
move = "MOVE_ROLLOUT"
level = 11

[[learnset.entries]]
slot = 4
move = "MOVE_WHIRLPOOL"
level = 14

[[learnset.entries]]
slot = 5
move = "MOVE_ASTONISH"
level = 17

[[learnset.entries]]
slot = 6
move = "MOVE_WATER_PULSE"
level = 21

[[learnset.entries]]
slot = 7
move = "MOVE_MIST"
level = 24

[[learnset.entries]]
slot = 8
move = "MOVE_REST"
level = 27

[[learnset.entries]]
slot = 9
move = "MOVE_BRINE"
level = 31

[[learnset.entries]]
slot = 10
move = "MOVE_WATER_SPOUT"
level = 34

[[learnset.entries]]
slot = 11
move = "MOVE_AMNESIA"
level = 37

[[learnset.entries]]
slot = 12
move = "MOVE_DIVE"
level = 41

[[learnset.entries]]
slot = 13
move = "MOVE_BOUNCE"
level = 44

[[learnset.entries]]
slot = 14
move = "MOVE_HYDRO_PUMP"
level = 47

[[learnset.entries]]
slot = 15
move = "MOVE_HEAVY_SLAM"
level = 50
