[learnset]
index = 325
species = "SPECIES_SPOINK"

[[learnset.entries]]
slot = 0
move = "MOVE_SPLASH"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_PSYWAVE"
level = 7

[[learnset.entries]]
slot = 2
move = "MOVE_ODOR_SLEUTH"
level = 10

[[learnset.entries]]
slot = 3
move = "MOVE_PSYBEAM"
level = 14

[[learnset.entries]]
slot = 4
move = "MOVE_PSYCH_UP"
level = 15

[[learnset.entries]]
slot = 5
move = "MOVE_CONFUSE_RAY"
level = 18

[[learnset.entries]]
slot = 6
move = "MOVE_MAGIC_COAT"
level = 21

[[learnset.entries]]
slot = 7
move = "MOVE_ZEN_HEADBUTT"
level = 26

[[learnset.entries]]
slot = 8
move = "MOVE_REST"
level = 29

[[learnset.entries]]
slot = 9
move = "MOVE_SNORE"
level = 29

[[learnset.entries]]
slot = 10
move = "MOVE_POWER_GEM"
level = 33

[[learnset.entries]]
slot = 11
move = "MOVE_PSYSHOCK"
level = 38

[[learnset.entries]]
slot = 12
move = "MOVE_PAYBACK"
level = 40

[[learnset.entries]]
slot = 13
move = "MOVE_PSYCHIC"
level = 44

[[learnset.entries]]
slot = 14
move = "MOVE_BOUNCE"
level = 50
