[learnset]
index = 329
species = "SPECIES_VIBRAVA"

[[learnset.entries]]
slot = 0
move = "MOVE_SONICBOOM"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_SANDATTACK"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_FAINT_ATTACK"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_SAND_TOMB"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_SANDATTACK"
level = 4

[[learnset.entries]]
slot = 5
move = "MOVE_FAINT_ATTACK"
level = 7

[[learnset.entries]]
slot = 6
move = "MOVE_SAND_TOMB"
level = 10

[[learnset.entries]]
slot = 7
move = "MOVE_MUDSLAP"
level = 13

[[learnset.entries]]
slot = 8
move = "MOVE_BIDE"
level = 17

[[learnset.entries]]
slot = 9
move = "MOVE_BULLDOZE"
level = 21

[[learnset.entries]]
slot = 10
move = "MOVE_ROCK_SLIDE"
level = 25

[[learnset.entries]]
slot = 11
move = "MOVE_SUPERSONIC"
level = 29

[[learnset.entries]]
slot = 12
move = "MOVE_SCREECH"
level = 34

[[learnset.entries]]
slot = 13
move = "MOVE_DRAGONBREATH"
level = 35

[[learnset.entries]]
slot = 14
move = "MOVE_EARTH_POWER"
level = 39

[[learnset.entries]]
slot = 15
move = "MOVE_SANDSTORM"
level = 44

[[learnset.entries]]
slot = 16
move = "MOVE_HYPER_BEAM"
level = 49
