[learnset]
index = 349
species = "SPECIES_FEEBAS"

[[learnset.entries]]
slot = 0
move = "MOVE_SPLASH"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_TACKLE"
level = 15

[[learnset.entries]]
slot = 2
move = "MOVE_FLAIL"
level = 30
