[learnset]
index = 355
species = "SPECIES_DUSKULL"

[[learnset.entries]]
slot = 0
move = "MOVE_LEER"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_NIGHT_SHADE"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_DISABLE"
level = 6

[[learnset.entries]]
slot = 3
move = "MOVE_FORESIGHT"
level = 9

[[learnset.entries]]
slot = 4
move = "MOVE_ASTONISH"
level = 14

[[learnset.entries]]
slot = 5
move = "MOVE_CONFUSE_RAY"
level = 17

[[learnset.entries]]
slot = 6
move = "MOVE_SHADOW_SNEAK"
level = 22

[[learnset.entries]]
slot = 7
move = "MOVE_PURSUIT"
level = 25

[[learnset.entries]]
slot = 8
move = "MOVE_CURSE"
level = 30

[[learnset.entries]]
slot = 9
move = "MOVE_WILLOWISP"
level = 33

[[learnset.entries]]
slot = 10
move = "MOVE_HEX"
level = 38

[[learnset.entries]]
slot = 11
move = "MOVE_MEAN_LOOK"
level = 41

[[learnset.entries]]
slot = 12
move = "MOVE_PAYBACK"
level = 46

[[learnset.entries]]
slot = 13
move = "MOVE_FUTURE_SIGHT"
level = 49
