[learnset]
index = 357
species = "SPECIES_TROPIUS"

[[learnset.entries]]
slot = 0
move = "MOVE_LEER"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_GUST"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_GROWTH"
level = 7

[[learnset.entries]]
slot = 3
move = "MOVE_RAZOR_LEAF"
level = 11

[[learnset.entries]]
slot = 4
move = "MOVE_STOMP"
level = 17

[[learnset.entries]]
slot = 5
move = "MOVE_SWEET_SCENT"
level = 21

[[learnset.entries]]
slot = 6
move = "MOVE_WHIRLWIND"
level = 27

[[learnset.entries]]
slot = 7
move = "MOVE_MAGICAL_LEAF"
level = 31

[[learnset.entries]]
slot = 8
move = "MOVE_BODY_SLAM"
level = 37

[[learnset.entries]]
slot = 9
move = "MOVE_SYNTHESIS"
level = 41

[[learnset.entries]]
slot = 10
move = "MOVE_LEAF_TORNADO"
level = 47

[[learnset.entries]]
slot = 11
move = "MOVE_AIR_SLASH"
level = 51

[[learnset.entries]]
slot = 12
move = "MOVE_BESTOW"
level = 57

[[learnset.entries]]
slot = 13
move = "MOVE_SOLARBEAM"
level = 61

[[learnset.entries]]
slot = 14
move = "MOVE_NATURAL_GIFT"
level = 67

[[learnset.entries]]
slot = 15
move = "MOVE_LEAF_STORM"
level = 71
