[learnset]
index = 360
species = "SPECIES_WYNAUT"

[[learnset.entries]]
slot = 0
move = "MOVE_SPLASH"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_CHARM"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_ENCORE"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_COUNTER"
level = 15

[[learnset.entries]]
slot = 4
move = "MOVE_MIRROR_COAT"
level = 15

[[learnset.entries]]
slot = 5
move = "MOVE_SAFEGUARD"
level = 15

[[learnset.entries]]
slot = 6
move = "MOVE_DESTINY_BOND"
level = 15
