[learnset]
index = 362
species = "SPECIES_GLALIE"

[[learnset.entries]]
slot = 0
move = "MOVE_POWDER_SNOW"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_LEER"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_DOUBLE_TEAM"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_BITE"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_DOUBLE_TEAM"
level = 4

[[learnset.entries]]
slot = 5
move = "MOVE_BITE"
level = 10

[[learnset.entries]]
slot = 6
move = "MOVE_ICY_WIND"
level = 13

[[learnset.entries]]
slot = 7
move = "MOVE_HEADBUTT"
level = 19

[[learnset.entries]]
slot = 8
move = "MOVE_PROTECT"
level = 22

[[learnset.entries]]
slot = 9
move = "MOVE_ICE_FANG"
level = 28

[[learnset.entries]]
slot = 10
move = "MOVE_CRUNCH"
level = 31

[[learnset.entries]]
slot = 11
move = "MOVE_ICE_BEAM"
level = 37

[[learnset.entries]]
slot = 12
move = "MOVE_HAIL"
level = 40

[[learnset.entries]]
slot = 13
move = "MOVE_BLIZZARD"
level = 51

[[learnset.entries]]
slot = 14
move = "MOVE_SHEER_COLD"
level = 59
