[learnset]
index = 366
species = "SPECIES_CLAMPERL"

[[learnset.entries]]
slot = 0
move = "MOVE_CLAMP"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_WATER_GUN"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_WHIRLPOOL"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_IRON_DEFENSE"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_SHELL_SMASH"
level = 51
