[learnset]
index = 367
species = "SPECIES_HUNTAIL"

[[learnset.entries]]
slot = 0
move = "MOVE_WHIRLPOOL"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_BITE"
level = 6

[[learnset.entries]]
slot = 2
move = "MOVE_SCREECH"
level = 10

[[learnset.entries]]
slot = 3
move = "MOVE_WATER_PULSE"
level = 15

[[learnset.entries]]
slot = 4
move = "MOVE_SCARY_FACE"
level = 19

[[learnset.entries]]
slot = 5
move = "MOVE_ICE_FANG"
level = 24

[[learnset.entries]]
slot = 6
move = "MOVE_BRINE"
level = 28

[[learnset.entries]]
slot = 7
move = "MOVE_BATON_PASS"
level = 33

[[learnset.entries]]
slot = 8
move = "MOVE_DIVE"
level = 37

[[learnset.entries]]
slot = 9
move = "MOVE_CRUNCH"
level = 42

[[learnset.entries]]
slot = 10
move = "MOVE_AQUA_TAIL"
level = 46

[[learnset.entries]]
slot = 11
move = "MOVE_HYDRO_PUMP"
level = 51
