[learnset]
index = 369
species = "SPECIES_RELICANTH"

[[learnset.entries]]
slot = 0
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_HARDEN"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_WATER_GUN"
level = 8

[[learnset.entries]]
slot = 3
move = "MOVE_ROCK_TOMB"
level = 15

[[learnset.entries]]
slot = 4
move = "MOVE_YAWN"
level = 22

[[learnset.entries]]
slot = 5
move = "MOVE_TAKE_DOWN"
level = 29

[[learnset.entries]]
slot = 6
move = "MOVE_MUD_SPORT"
level = 36

[[learnset.entries]]
slot = 7
move = "MOVE_ANCIENTPOWER"
level = 43

[[learnset.entries]]
slot = 8
move = "MOVE_DOUBLEEDGE"
level = 50

[[learnset.entries]]
slot = 9
move = "MOVE_DIVE"
level = 57

[[learnset.entries]]
slot = 10
move = "MOVE_REST"
level = 64

[[learnset.entries]]
slot = 11
move = "MOVE_HYDRO_PUMP"
level = 71

[[learnset.entries]]
slot = 12
move = "MOVE_HEAD_SMASH"
level = 78
