[learnset]
index = 370
species = "SPECIES_LUVDISC"

[[learnset.entries]]
slot = 0
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_CHARM"
level = 4

[[learnset.entries]]
slot = 2
move = "MOVE_WATER_GUN"
level = 7

[[learnset.entries]]
slot = 3
move = "MOVE_AGILITY"
level = 9

[[learnset.entries]]
slot = 4
move = "MOVE_TAKE_DOWN"
level = 14

[[learnset.entries]]
slot = 5
move = "MOVE_LUCKY_CHANT"
level = 17

[[learnset.entries]]
slot = 6
move = "MOVE_WATER_PULSE"
level = 22

[[learnset.entries]]
slot = 7
move = "MOVE_ATTRACT"
level = 27

[[learnset.entries]]
slot = 8
move = "MOVE_FLAIL"
level = 31

[[learnset.entries]]
slot = 9
move = "MOVE_SWEET_KISS"
level = 37

[[learnset.entries]]
slot = 10
move = "MOVE_HYDRO_PUMP"
level = 40

[[learnset.entries]]
slot = 11
move = "MOVE_AQUA_RING"
level = 46

[[learnset.entries]]
slot = 12
move = "MOVE_CAPTIVATE"
level = 51

[[learnset.entries]]
slot = 13
move = "MOVE_SAFEGUARD"
level = 55
