[learnset]
index = 376
species = "SPECIES_METAGROSS"

[[learnset.entries]]
slot = 0
move = "MOVE_MAGNET_RISE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_TAKE_DOWN"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_METAL_CLAW"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_CONFUSION"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_CONFUSION"
level = 20

[[learnset.entries]]
slot = 5
move = "MOVE_METAL_CLAW"
level = 20

[[learnset.entries]]
slot = 6
move = "MOVE_PURSUIT"
level = 23

[[learnset.entries]]
slot = 7
move = "MOVE_MIRACLE_EYE"
level = 26

[[learnset.entries]]
slot = 8
move = "MOVE_ZEN_HEADBUTT"
level = 29

[[learnset.entries]]
slot = 9
move = "MOVE_BULLET_PUNCH"
level = 32

[[learnset.entries]]
slot = 10
move = "MOVE_SCARY_FACE"
level = 35

[[learnset.entries]]
slot = 11
move = "MOVE_AGILITY"
level = 38

[[learnset.entries]]
slot = 12
move = "MOVE_PSYCHIC"
level = 41

[[learnset.entries]]
slot = 13
move = "MOVE_METEOR_MASH"
level = 44

[[learnset.entries]]
slot = 14
move = "MOVE_HAMMER_ARM"
level = 45

[[learnset.entries]]
slot = 15
move = "MOVE_IRON_DEFENSE"
level = 53

[[learnset.entries]]
slot = 16
move = "MOVE_HYPER_BEAM"
level = 62
