[learnset]
index = 378
species = "SPECIES_REGICE"

[[learnset.entries]]
slot = 0
move = "MOVE_EXPLOSION"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_STOMP"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_ICY_WIND"
level = 9

[[learnset.entries]]
slot = 3
move = "MOVE_CURSE"
level = 17

[[learnset.entries]]
slot = 4
move = "MOVE_SUPERPOWER"
level = 25

[[learnset.entries]]
slot = 5
move = "MOVE_ANCIENTPOWER"
level = 33

[[learnset.entries]]
slot = 6
move = "MOVE_AMNESIA"
level = 41

[[learnset.entries]]
slot = 7
move = "MOVE_CHARGE_BEAM"
level = 49

[[learnset.entries]]
slot = 8
move = "MOVE_LOCKON"
level = 57

[[learnset.entries]]
slot = 9
move = "MOVE_ZAP_CANNON"
level = 65

[[learnset.entries]]
slot = 10
move = "MOVE_ICE_BEAM"
level = 73

[[learnset.entries]]
slot = 11
move = "MOVE_HAMMER_ARM"
level = 81

[[learnset.entries]]
slot = 12
move = "MOVE_HYPER_BEAM"
level = 89
