[learnset]
index = 384
species = "SPECIES_RAYQUAZA"

[[learnset.entries]]
slot = 0
move = "MOVE_TWISTER"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_SCARY_FACE"
level = 5

[[learnset.entries]]
slot = 2
move = "MOVE_CRUNCH"
level = 15

[[learnset.entries]]
slot = 3
move = "MOVE_HYPER_VOICE"
level = 20

[[learnset.entries]]
slot = 4
move = "MOVE_REST"
level = 30

[[learnset.entries]]
slot = 5
move = "MOVE_AIR_SLASH"
level = 35

[[learnset.entries]]
slot = 6
move = "MOVE_ANCIENTPOWER"
level = 45

[[learnset.entries]]
slot = 7
move = "MOVE_OUTRAGE"
level = 50

[[learnset.entries]]
slot = 8
move = "MOVE_DRAGON_DANCE"
level = 60

[[learnset.entries]]
slot = 9
move = "MOVE_FLY"
level = 65

[[learnset.entries]]
slot = 10
move = "MOVE_EXTREMESPEED"
level = 75

[[learnset.entries]]
slot = 11
move = "MOVE_HYPER_BEAM"
level = 80

[[learnset.entries]]
slot = 12
move = "MOVE_DRAGON_PULSE"
level = 90
