[learnset]
index = 387
species = "SPECIES_TURTWIG"

[[learnset.entries]]
slot = 0
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_WITHDRAW"
level = 5

[[learnset.entries]]
slot = 2
move = "MOVE_ABSORB"
level = 9

[[learnset.entries]]
slot = 3
move = "MOVE_RAZOR_LEAF"
level = 13

[[learnset.entries]]
slot = 4
move = "MOVE_CURSE"
level = 17

[[learnset.entries]]
slot = 5
move = "MOVE_BITE"
level = 21

[[learnset.entries]]
slot = 6
move = "MOVE_MEGA_DRAIN"
level = 25

[[learnset.entries]]
slot = 7
move = "MOVE_LEECH_SEED"
level = 29

[[learnset.entries]]
slot = 8
move = "MOVE_SYNTHESIS"
level = 33

[[learnset.entries]]
slot = 9
move = "MOVE_CRUNCH"
level = 37

[[learnset.entries]]
slot = 10
move = "MOVE_GIGA_DRAIN"
level = 41

[[learnset.entries]]
slot = 11
move = "MOVE_LEAF_STORM"
level = 45
