[learnset]
index = 389
species = "SPECIES_TORTERRA"

[[learnset.entries]]
slot = 0
move = "MOVE_WOOD_HAMMER"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_WITHDRAW"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_ABSORB"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_RAZOR_LEAF"
level = 1

[[learnset.entries]]
slot = 5
move = "MOVE_WITHDRAW"
level = 5

[[learnset.entries]]
slot = 6
move = "MOVE_ABSORB"
level = 9

[[learnset.entries]]
slot = 7
move = "MOVE_RAZOR_LEAF"
level = 13

[[learnset.entries]]
slot = 8
move = "MOVE_CURSE"
level = 17

[[learnset.entries]]
slot = 9
move = "MOVE_BITE"
level = 22

[[learnset.entries]]
slot = 10
move = "MOVE_MEGA_DRAIN"
level = 27

[[learnset.entries]]
slot = 11
move = "MOVE_EARTHQUAKE"
level = 32

[[learnset.entries]]
slot = 12
move = "MOVE_LEECH_SEED"
level = 33

[[learnset.entries]]
slot = 13
move = "MOVE_SYNTHESIS"
level = 39

[[learnset.entries]]
slot = 14
move = "MOVE_CRUNCH"
level = 45

[[learnset.entries]]
slot = 15
move = "MOVE_GIGA_DRAIN"
level = 51

[[learnset.entries]]
slot = 16
move = "MOVE_LEAF_STORM"
level = 57
