[learnset]
index = 397
species = "SPECIES_STARAVIA"

[[learnset.entries]]
slot = 0
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_GROWL"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_QUICK_ATTACK"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_QUICK_ATTACK"
level = 5

[[learnset.entries]]
slot = 4
move = "MOVE_WING_ATTACK"
level = 9

[[learnset.entries]]
slot = 5
move = "MOVE_DOUBLE_TEAM"
level = 13

[[learnset.entries]]
slot = 6
move = "MOVE_ENDEAVOR"
level = 18

[[learnset.entries]]
slot = 7
move = "MOVE_WHIRLWIND"
level = 23

[[learnset.entries]]
slot = 8
move = "MOVE_AERIAL_ACE"
level = 28

[[learnset.entries]]
slot = 9
move = "MOVE_TAKE_DOWN"
level = 33

[[learnset.entries]]
slot = 10
move = "MOVE_AGILITY"
level = 38

[[learnset.entries]]
slot = 11
move = "MOVE_BRAVE_BIRD"
level = 43

[[learnset.entries]]
slot = 12
move = "MOVE_FINAL_GAMBIT"
level = 48
