[learnset]
index = 399
species = "SPECIES_BIDOOF"

[[learnset.entries]]
slot = 0
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_GROWL"
level = 5

[[learnset.entries]]
slot = 2
move = "MOVE_DEFENSE_CURL"
level = 9

[[learnset.entries]]
slot = 3
move = "MOVE_ROLLOUT"
level = 13

[[learnset.entries]]
slot = 4
move = "MOVE_HEADBUTT"
level = 17

[[learnset.entries]]
slot = 5
move = "MOVE_HYPER_FANG"
level = 21

[[learnset.entries]]
slot = 6
move = "MOVE_YAWN"
level = 25

[[learnset.entries]]
slot = 7
move = "MOVE_AMNESIA"
level = 29

[[learnset.entries]]
slot = 8
move = "MOVE_TAKE_DOWN"
level = 33

[[learnset.entries]]
slot = 9
move = "MOVE_SUPER_FANG"
level = 37

[[learnset.entries]]
slot = 10
move = "MOVE_SUPERPOWER"
level = 41

[[learnset.entries]]
slot = 11
move = "MOVE_CURSE"
level = 45
