[learnset]
index = 400
species = "SPECIES_BIBAREL"

[[learnset.entries]]
slot = 0
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_GROWL"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_GROWL"
level = 5

[[learnset.entries]]
slot = 3
move = "MOVE_DEFENSE_CURL"
level = 9

[[learnset.entries]]
slot = 4
move = "MOVE_ROLLOUT"
level = 13

[[learnset.entries]]
slot = 5
move = "MOVE_WATER_GUN"
level = 15

[[learnset.entries]]
slot = 6
move = "MOVE_HEADBUTT"
level = 18

[[learnset.entries]]
slot = 7
move = "MOVE_HYPER_FANG"
level = 23

[[learnset.entries]]
slot = 8
move = "MOVE_YAWN"
level = 28

[[learnset.entries]]
slot = 9
move = "MOVE_AMNESIA"
level = 33

[[learnset.entries]]
slot = 10
move = "MOVE_TAKE_DOWN"
level = 38

[[learnset.entries]]
slot = 11
move = "MOVE_SUPER_FANG"
level = 43

[[learnset.entries]]
slot = 12
move = "MOVE_SUPERPOWER"
level = 48

[[learnset.entries]]
slot = 13
move = "MOVE_CURSE"
level = 53
