[learnset]
index = 401
species = "SPECIES_KRICKETOT"

[[learnset.entries]]
slot = 0
move = "MOVE_GROWL"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_BIDE"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_STRUGGLE_BUG"
level = 6

[[learnset.entries]]
slot = 3
move = "MOVE_BUG_BITE"
level = 16
