[learnset]
index = 403
species = "SPECIES_SHINX"

[[learnset.entries]]
slot = 0
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_LEER"
level = 5

[[learnset.entries]]
slot = 2
move = "MOVE_CHARGE"
level = 9

[[learnset.entries]]
slot = 3
move = "MOVE_SPARK"
level = 13

[[learnset.entries]]
slot = 4
move = "MOVE_BITE"
level = 17

[[learnset.entries]]
slot = 5
move = "MOVE_ROAR"
level = 21

[[learnset.entries]]
slot = 6
move = "MOVE_SWAGGER"
level = 25

[[learnset.entries]]
slot = 7
move = "MOVE_THUNDER_FANG"
level = 29

[[learnset.entries]]
slot = 8
move = "MOVE_CRUNCH"
level = 33

[[learnset.entries]]
slot = 9
move = "MOVE_SCARY_FACE"
level = 37

[[learnset.entries]]
slot = 10
move = "MOVE_DISCHARGE"
level = 41

[[learnset.entries]]
slot = 11
move = "MOVE_WILD_CHARGE"
level = 45
