[learnset]
index = 406
species = "SPECIES_BUDEW"

[[learnset.entries]]
slot = 0
move = "MOVE_ABSORB"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_GROWTH"
level = 4

[[learnset.entries]]
slot = 2
move = "MOVE_WATER_SPORT"
level = 7

[[learnset.entries]]
slot = 3
move = "MOVE_STUN_SPORE"
level = 10

[[learnset.entries]]
slot = 4
move = "MOVE_MEGA_DRAIN"
level = 13

[[learnset.entries]]
slot = 5
move = "MOVE_WORRY_SEED"
level = 16
