[learnset]
index = 410
species = "SPECIES_SHIELDON"

[[learnset.entries]]
slot = 0
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_PROTECT"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_TAUNT"
level = 6

[[learnset.entries]]
slot = 3
move = "MOVE_METAL_SOUND"
level = 10

[[learnset.entries]]
slot = 4
move = "MOVE_TAKE_DOWN"
level = 15

[[learnset.entries]]
slot = 5
move = "MOVE_IRON_DEFENSE"
level = 19

[[learnset.entries]]
slot = 6
move = "MOVE_SWAGGER"
level = 24

[[learnset.entries]]
slot = 7
move = "MOVE_ANCIENTPOWER"
level = 28

[[learnset.entries]]
slot = 8
move = "MOVE_ENDURE"
level = 33

[[learnset.entries]]
slot = 9
move = "MOVE_METAL_BURST"
level = 37

[[learnset.entries]]
slot = 10
move = "MOVE_IRON_HEAD"
level = 42

[[learnset.entries]]
slot = 11
move = "MOVE_HEAVY_SLAM"
level = 46
