[learnset]
index = 412
species = "SPECIES_BURMY"

[[learnset.entries]]
slot = 0
move = "MOVE_PROTECT"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_TACKLE"
level = 10

[[learnset.entries]]
slot = 2
move = "MOVE_BUG_BITE"
level = 15

[[learnset.entries]]
slot = 3
move = "MOVE_HIDDEN_POWER"
level = 20
