[learnset]
index = 415
species = "SPECIES_COMBEE"

[[learnset.entries]]
slot = 0
move = "MOVE_SWEET_SCENT"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_GUST"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_BUG_BITE"
level = 13

[[learnset.entries]]
slot = 3
move = "MOVE_BUG_BUZZ"
level = 29
