[learnset]
index = 417
species = "SPECIES_PACHIRISU"

[[learnset.entries]]
slot = 0
move = "MOVE_GROWL"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_BIDE"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_QUICK_ATTACK"
level = 5

[[learnset.entries]]
slot = 3
move = "MOVE_CHARM"
level = 9

[[learnset.entries]]
slot = 4
move = "MOVE_SPARK"
level = 13

[[learnset.entries]]
slot = 5
move = "MOVE_ENDURE"
level = 17

[[learnset.entries]]
slot = 6
move = "MOVE_SWIFT"
level = 21

[[learnset.entries]]
slot = 7
move = "MOVE_ELECTRO_BALL"
level = 25

[[learnset.entries]]
slot = 8
move = "MOVE_SWEET_KISS"
level = 29

[[learnset.entries]]
slot = 9
move = "MOVE_THUNDER_WAVE"
level = 33

[[learnset.entries]]
slot = 10
move = "MOVE_SUPER_FANG"
level = 37

[[learnset.entries]]
slot = 11
move = "MOVE_DISCHARGE"
level = 41

[[learnset.entries]]
slot = 12
move = "MOVE_LAST_RESORT"
level = 45

[[learnset.entries]]
slot = 13
move = "MOVE_HYPER_FANG"
level = 49
