[learnset]
index = 419
species = "SPECIES_FLOATZEL"

[[learnset.entries]]
slot = 0
move = "MOVE_ICE_FANG"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_CRUNCH"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_SONICBOOM"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_GROWL"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_WATER_SPORT"
level = 1

[[learnset.entries]]
slot = 5
move = "MOVE_QUICK_ATTACK"
level = 1

[[learnset.entries]]
slot = 6
move = "MOVE_GROWL"
level = 4

[[learnset.entries]]
slot = 7
move = "MOVE_WATER_SPORT"
level = 7

[[learnset.entries]]
slot = 8
move = "MOVE_QUICK_ATTACK"
level = 11

[[learnset.entries]]
slot = 9
move = "MOVE_WATER_GUN"
level = 15

[[learnset.entries]]
slot = 10
move = "MOVE_PURSUIT"
level = 18

[[learnset.entries]]
slot = 11
move = "MOVE_SWIFT"
level = 21

[[learnset.entries]]
slot = 12
move = "MOVE_AQUA_JET"
level = 24

[[learnset.entries]]
slot = 13
move = "MOVE_DOUBLE_HIT"
level = 29

[[learnset.entries]]
slot = 14
move = "MOVE_WHIRLPOOL"
level = 35

[[learnset.entries]]
slot = 15
move = "MOVE_RAZOR_WIND"
level = 41

[[learnset.entries]]
slot = 16
move = "MOVE_AQUA_TAIL"
level = 46

[[learnset.entries]]
slot = 17
move = "MOVE_AGILITY"
level = 51

[[learnset.entries]]
slot = 18
move = "MOVE_HYDRO_PUMP"
level = 57
