[learnset]
index = 431
species = "SPECIES_GLAMEOW"

[[learnset.entries]]
slot = 0
move = "MOVE_FAKE_OUT"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_SCRATCH"
level = 5

[[learnset.entries]]
slot = 2
move = "MOVE_GROWL"
level = 8

[[learnset.entries]]
slot = 3
move = "MOVE_HYPNOSIS"
level = 13

[[learnset.entries]]
slot = 4
move = "MOVE_FAINT_ATTACK"
level = 17

[[learnset.entries]]
slot = 5
move = "MOVE_FURY_SWIPES"
level = 20

[[learnset.entries]]
slot = 6
move = "MOVE_CHARM"
level = 25

[[learnset.entries]]
slot = 7
move = "MOVE_ASSIST"
level = 29

[[learnset.entries]]
slot = 8
move = "MOVE_CAPTIVATE"
level = 32

[[learnset.entries]]
slot = 9
move = "MOVE_SLASH"
level = 37

[[learnset.entries]]
slot = 10
move = "MOVE_SUCKER_PUNCH"
level = 41

[[learnset.entries]]
slot = 11
move = "MOVE_ATTRACT"
level = 44

[[learnset.entries]]
slot = 12
move = "MOVE_HONE_CLAWS"
level = 48
