[learnset]
index = 433
species = "SPECIES_CHINGLING"

[[learnset.entries]]
slot = 0
move = "MOVE_WRAP"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_GROWL"
level = 6

[[learnset.entries]]
slot = 2
move = "MOVE_ASTONISH"
level = 9

[[learnset.entries]]
slot = 3
move = "MOVE_CONFUSION"
level = 14

[[learnset.entries]]
slot = 4
move = "MOVE_UPROAR"
level = 17

[[learnset.entries]]
slot = 5
move = "MOVE_LAST_RESORT"
level = 22

[[learnset.entries]]
slot = 6
move = "MOVE_ENTRAINMENT"
level = 25
