[learnset]
index = 434
species = "SPECIES_STUNKY"

[[learnset.entries]]
slot = 0
move = "MOVE_SCRATCH"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_FOCUS_ENERGY"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_POISON_GAS"
level = 4

[[learnset.entries]]
slot = 3
move = "MOVE_SCREECH"
level = 7

[[learnset.entries]]
slot = 4
move = "MOVE_FURY_SWIPES"
level = 10

[[learnset.entries]]
slot = 5
move = "MOVE_SMOKESCREEN"
level = 14

[[learnset.entries]]
slot = 6
move = "MOVE_FEINT"
level = 18

[[learnset.entries]]
slot = 7
move = "MOVE_SLASH"
level = 22

[[learnset.entries]]
slot = 8
move = "MOVE_TOXIC"
level = 27

[[learnset.entries]]
slot = 9
move = "MOVE_ACID_SPRAY"
level = 32

[[learnset.entries]]
slot = 10
move = "MOVE_NIGHT_SLASH"
level = 37

[[learnset.entries]]
slot = 11
move = "MOVE_MEMENTO"
level = 43

[[learnset.entries]]
slot = 12
move = "MOVE_EXPLOSION"
level = 49
