[learnset]
index = 436
species = "SPECIES_BRONZOR"

[[learnset.entries]]
slot = 0
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_CONFUSION"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_HYPNOSIS"
level = 5

[[learnset.entries]]
slot = 3
move = "MOVE_IMPRISON"
level = 9

[[learnset.entries]]
slot = 4
move = "MOVE_CONFUSE_RAY"
level = 11

[[learnset.entries]]
slot = 5
move = "MOVE_PSYWAVE"
level = 15

[[learnset.entries]]
slot = 6
move = "MOVE_IRON_DEFENSE"
level = 19

[[learnset.entries]]
slot = 7
move = "MOVE_FAINT_ATTACK"
level = 21

[[learnset.entries]]
slot = 8
move = "MOVE_SAFEGUARD"
level = 25

[[learnset.entries]]
slot = 9
move = "MOVE_FUTURE_SIGHT"
level = 29

[[learnset.entries]]
slot = 10
move = "MOVE_METAL_SOUND"
level = 31

[[learnset.entries]]
slot = 11
move = "MOVE_GYRO_BALL"
level = 35

[[learnset.entries]]
slot = 12
move = "MOVE_EXTRASENSORY"
level = 39

[[learnset.entries]]
slot = 13
move = "MOVE_PAYBACK"
level = 41

[[learnset.entries]]
slot = 14
move = "MOVE_HEAL_BLOCK"
level = 45

[[learnset.entries]]
slot = 15
move = "MOVE_HEAVY_SLAM"
level = 49
