[learnset]
index = 440
species = "SPECIES_HAPPINY"

[[learnset.entries]]
slot = 0
move = "MOVE_POUND"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_CHARM"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_COPYCAT"
level = 5

[[learnset.entries]]
slot = 3
move = "MOVE_REFRESH"
level = 9

[[learnset.entries]]
slot = 4
move = "MOVE_SWEET_KISS"
level = 12
