[learnset]
index = 441
species = "SPECIES_CHATOT"

[[learnset.entries]]
slot = 0
move = "MOVE_PECK"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_GROWL"
level = 5

[[learnset.entries]]
slot = 2
move = "MOVE_MIRROR_MOVE"
level = 9

[[learnset.entries]]
slot = 3
move = "MOVE_SING"
level = 13

[[learnset.entries]]
slot = 4
move = "MOVE_FURY_ATTACK"
level = 17

[[learnset.entries]]
slot = 5
move = "MOVE_CHATTER"
level = 21

[[learnset.entries]]
slot = 6
move = "MOVE_TAUNT"
level = 25

[[learnset.entries]]
slot = 7
move = "MOVE_ROUND"
level = 29

[[learnset.entries]]
slot = 8
move = "MOVE_MIMIC"
level = 33

[[learnset.entries]]
slot = 9
move = "MOVE_ECHOED_VOICE"
level = 37

[[learnset.entries]]
slot = 10
move = "MOVE_ROOST"
level = 41

[[learnset.entries]]
slot = 11
move = "MOVE_UPROAR"
level = 45

[[learnset.entries]]
slot = 12
move = "MOVE_SYNCHRONOISE"
level = 49

[[learnset.entries]]
slot = 13
move = "MOVE_FEATHERDANCE"
level = 53

[[learnset.entries]]
slot = 14
move = "MOVE_HYPER_VOICE"
level = 57
