[learnset]
index = 442
species = "SPECIES_SPIRITOMB"

[[learnset.entries]]
slot = 0
move = "MOVE_CURSE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_PURSUIT"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_CONFUSE_RAY"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_SPITE"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_SHADOW_SNEAK"
level = 1

[[learnset.entries]]
slot = 5
move = "MOVE_FAINT_ATTACK"
level = 7

[[learnset.entries]]
slot = 6
move = "MOVE_HYPNOSIS"
level = 13

[[learnset.entries]]
slot = 7
move = "MOVE_DREAM_EATER"
level = 19

[[learnset.entries]]
slot = 8
move = "MOVE_OMINOUS_WIND"
level = 25

[[learnset.entries]]
slot = 9
move = "MOVE_SUCKER_PUNCH"
level = 31

[[learnset.entries]]
slot = 10
move = "MOVE_NASTY_PLOT"
level = 37

[[learnset.entries]]
slot = 11
move = "MOVE_MEMENTO"
level = 43

[[learnset.entries]]
slot = 12
move = "MOVE_DARK_PULSE"
level = 49
