[learnset]
index = 443
species = "SPECIES_GIBLE"

[[learnset.entries]]
slot = 0
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_SANDATTACK"
level = 3

[[learnset.entries]]
slot = 2
move = "MOVE_DRAGON_RAGE"
level = 7

[[learnset.entries]]
slot = 3
move = "MOVE_SANDSTORM"
level = 13

[[learnset.entries]]
slot = 4
move = "MOVE_TAKE_DOWN"
level = 15

[[learnset.entries]]
slot = 5
move = "MOVE_SAND_TOMB"
level = 19

[[learnset.entries]]
slot = 6
move = "MOVE_SLASH"
level = 25

[[learnset.entries]]
slot = 7
move = "MOVE_DRAGON_CLAW"
level = 27

[[learnset.entries]]
slot = 8
move = "MOVE_DIG"
level = 31

[[learnset.entries]]
slot = 9
move = "MOVE_DRAGON_RUSH"
level = 37
