[learnset]
index = 447
species = "SPECIES_RIOLU"

[[learnset.entries]]
slot = 0
move = "MOVE_FORESIGHT"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_QUICK_ATTACK"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_ENDURE"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_COUNTER"
level = 6

[[learnset.entries]]
slot = 4
move = "MOVE_FEINT"
level = 11

[[learnset.entries]]
slot = 5
move = "MOVE_FORCE_PALM"
level = 15

[[learnset.entries]]
slot = 6
move = "MOVE_COPYCAT"
level = 19

[[learnset.entries]]
slot = 7
move = "MOVE_SCREECH"
level = 24

[[learnset.entries]]
slot = 8
move = "MOVE_REVERSAL"
level = 29

[[learnset.entries]]
slot = 9
move = "MOVE_NASTY_PLOT"
level = 47

[[learnset.entries]]
slot = 10
move = "MOVE_FINAL_GAMBIT"
level = 55
