[learnset]
index = 448
species = "SPECIES_LUCARIO"

[[learnset.entries]]
slot = 0
move = "MOVE_DARK_PULSE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_FORESIGHT"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_QUICK_ATTACK"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_DETECT"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_METAL_CLAW"
level = 1

[[learnset.entries]]
slot = 5
move = "MOVE_COUNTER"
level = 6

[[learnset.entries]]
slot = 6
move = "MOVE_FEINT"
level = 11

[[learnset.entries]]
slot = 7
move = "MOVE_FORCE_PALM"
level = 15

[[learnset.entries]]
slot = 8
move = "MOVE_ME_FIRST"
level = 19

[[learnset.entries]]
slot = 9
move = "MOVE_METAL_SOUND"
level = 24

[[learnset.entries]]
slot = 10
move = "MOVE_BONE_RUSH"
level = 29

[[learnset.entries]]
slot = 11
move = "MOVE_QUICK_GUARD"
level = 33

[[learnset.entries]]
slot = 12
move = "MOVE_SWORDS_DANCE"
level = 37

[[learnset.entries]]
slot = 13
move = "MOVE_HEAL_PULSE"
level = 42

[[learnset.entries]]
slot = 14
move = "MOVE_CALM_MIND"
level = 47

[[learnset.entries]]
slot = 15
move = "MOVE_AURA_SPHERE"
level = 51

[[learnset.entries]]
slot = 16
move = "MOVE_CLOSE_COMBAT"
level = 55

[[learnset.entries]]
slot = 17
move = "MOVE_DRAGON_PULSE"
level = 60

[[learnset.entries]]
slot = 18
move = "MOVE_EXTREMESPEED"
level = 65
