[learnset]
index = 449
species = "SPECIES_HIPPOPOTAS"

[[learnset.entries]]
slot = 0
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_SANDATTACK"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_BITE"
level = 7

[[learnset.entries]]
slot = 3
move = "MOVE_YAWN"
level = 13

[[learnset.entries]]
slot = 4
move = "MOVE_TAKE_DOWN"
level = 19

[[learnset.entries]]
slot = 5
move = "MOVE_DIG"
level = 19

[[learnset.entries]]
slot = 6
move = "MOVE_SAND_TOMB"
level = 25

[[learnset.entries]]
slot = 7
move = "MOVE_CRUNCH"
level = 31

[[learnset.entries]]
slot = 8
move = "MOVE_EARTHQUAKE"
level = 37

[[learnset.entries]]
slot = 9
move = "MOVE_DOUBLEEDGE"
level = 44

[[learnset.entries]]
slot = 10
move = "MOVE_FISSURE"
level = 50
