[learnset]
index = 452
species = "SPECIES_DRAPION"

[[learnset.entries]]
slot = 0
move = "MOVE_THUNDER_FANG"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_ICE_FANG"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_FIRE_FANG"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_BITE"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_POISON_STING"
level = 1

[[learnset.entries]]
slot = 5
move = "MOVE_LEER"
level = 1

[[learnset.entries]]
slot = 6
move = "MOVE_KNOCK_OFF"
level = 1

[[learnset.entries]]
slot = 7
move = "MOVE_KNOCK_OFF"
level = 5

[[learnset.entries]]
slot = 8
move = "MOVE_PIN_MISSILE"
level = 9

[[learnset.entries]]
slot = 9
move = "MOVE_ACUPRESSURE"
level = 13

[[learnset.entries]]
slot = 10
move = "MOVE_PURSUIT"
level = 16

[[learnset.entries]]
slot = 11
move = "MOVE_BUG_BITE"
level = 20

[[learnset.entries]]
slot = 12
move = "MOVE_POISON_FANG"
level = 23

[[learnset.entries]]
slot = 13
move = "MOVE_VENOSHOCK"
level = 27

[[learnset.entries]]
slot = 14
move = "MOVE_HONE_CLAWS"
level = 30

[[learnset.entries]]
slot = 15
move = "MOVE_TOXIC_SPIKES"
level = 34

[[learnset.entries]]
slot = 16
move = "MOVE_NIGHT_SLASH"
level = 38

[[learnset.entries]]
slot = 17
move = "MOVE_SCARY_FACE"
level = 43

[[learnset.entries]]
slot = 18
move = "MOVE_CRUNCH"
level = 49

[[learnset.entries]]
slot = 19
move = "MOVE_CROSS_POISON"
level = 57
