[learnset]
index = 456
species = "SPECIES_FINNEON"

[[learnset.entries]]
slot = 0
move = "MOVE_POUND"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_WATER_GUN"
level = 6

[[learnset.entries]]
slot = 2
move = "MOVE_ATTRACT"
level = 10

[[learnset.entries]]
slot = 3
move = "MOVE_RAIN_DANCE"
level = 13

[[learnset.entries]]
slot = 4
move = "MOVE_GUST"
level = 17

[[learnset.entries]]
slot = 5
move = "MOVE_WATER_PULSE"
level = 22

[[learnset.entries]]
slot = 6
move = "MOVE_CAPTIVATE"
level = 26

[[learnset.entries]]
slot = 7
move = "MOVE_SAFEGUARD"
level = 29

[[learnset.entries]]
slot = 8
move = "MOVE_AQUA_RING"
level = 33

[[learnset.entries]]
slot = 9
move = "MOVE_WHIRLPOOL"
level = 38

[[learnset.entries]]
slot = 10
move = "MOVE_UTURN"
level = 42

[[learnset.entries]]
slot = 11
move = "MOVE_BOUNCE"
level = 45

[[learnset.entries]]
slot = 12
move = "MOVE_SILVER_WIND"
level = 49

[[learnset.entries]]
slot = 13
move = "MOVE_SOAK"
level = 54
