[learnset]
index = 459
species = "SPECIES_SNOVER"

[[learnset.entries]]
slot = 0
move = "MOVE_POWDER_SNOW"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_LEER"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_RAZOR_LEAF"
level = 5

[[learnset.entries]]
slot = 3
move = "MOVE_ICY_WIND"
level = 9

[[learnset.entries]]
slot = 4
move = "MOVE_GRASSWHISTLE"
level = 13

[[learnset.entries]]
slot = 5
move = "MOVE_SWAGGER"
level = 17

[[learnset.entries]]
slot = 6
move = "MOVE_MIST"
level = 21

[[learnset.entries]]
slot = 7
move = "MOVE_ICE_SHARD"
level = 26

[[learnset.entries]]
slot = 8
move = "MOVE_INGRAIN"
level = 31

[[learnset.entries]]
slot = 9
move = "MOVE_WOOD_HAMMER"
level = 36

[[learnset.entries]]
slot = 10
move = "MOVE_BLIZZARD"
level = 41

[[learnset.entries]]
slot = 11
move = "MOVE_SHEER_COLD"
level = 46
