[learnset]
index = 470
species = "SPECIES_LEAFEON"

[[learnset.entries]]
slot = 0
move = "MOVE_TAIL_WHIP"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_HELPING_HAND"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_SANDATTACK"
level = 5

[[learnset.entries]]
slot = 4
move = "MOVE_RAZOR_LEAF"
level = 9

[[learnset.entries]]
slot = 5
move = "MOVE_QUICK_ATTACK"
level = 13

[[learnset.entries]]
slot = 6
move = "MOVE_GRASSWHISTLE"
level = 17

[[learnset.entries]]
slot = 7
move = "MOVE_MAGICAL_LEAF"
level = 21

[[learnset.entries]]
slot = 8
move = "MOVE_GIGA_DRAIN"
level = 25

[[learnset.entries]]
slot = 9
move = "MOVE_SWORDS_DANCE"
level = 29

[[learnset.entries]]
slot = 10
move = "MOVE_SYNTHESIS"
level = 33

[[learnset.entries]]
slot = 11
move = "MOVE_SUNNY_DAY"
level = 37

[[learnset.entries]]
slot = 12
move = "MOVE_LAST_RESORT"
level = 41

[[learnset.entries]]
slot = 13
move = "MOVE_LEAF_BLADE"
level = 45
