[learnset]
index = 475
species = "SPECIES_GALLADE"

[[learnset.entries]]
slot = 0
move = "MOVE_LEAF_BLADE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_NIGHT_SLASH"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_LEER"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_CONFUSION"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_DOUBLE_TEAM"
level = 1

[[learnset.entries]]
slot = 5
move = "MOVE_TELEPORT"
level = 1

[[learnset.entries]]
slot = 6
move = "MOVE_CONFUSION"
level = 6

[[learnset.entries]]
slot = 7
move = "MOVE_DOUBLE_TEAM"
level = 10

[[learnset.entries]]
slot = 8
move = "MOVE_TELEPORT"
level = 12

[[learnset.entries]]
slot = 9
move = "MOVE_FURY_CUTTER"
level = 17

[[learnset.entries]]
slot = 10
move = "MOVE_SLASH"
level = 22

[[learnset.entries]]
slot = 11
move = "MOVE_HEAL_PULSE"
level = 25

[[learnset.entries]]
slot = 12
move = "MOVE_SWORDS_DANCE"
level = 31

[[learnset.entries]]
slot = 13
move = "MOVE_PSYCHO_CUT"
level = 36

[[learnset.entries]]
slot = 14
move = "MOVE_HELPING_HAND"
level = 39

[[learnset.entries]]
slot = 15
move = "MOVE_FEINT"
level = 45

[[learnset.entries]]
slot = 16
move = "MOVE_FALSE_SWIPE"
level = 50

[[learnset.entries]]
slot = 17
move = "MOVE_PROTECT"
level = 53

[[learnset.entries]]
slot = 18
move = "MOVE_CLOSE_COMBAT"
level = 59

[[learnset.entries]]
slot = 19
move = "MOVE_STORED_POWER"
level = 64
