[learnset]
index = 486
species = "SPECIES_REGIGIGAS"

[[learnset.entries]]
slot = 0
move = "MOVE_FIRE_PUNCH"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_ICE_PUNCH"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_THUNDERPUNCH"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_DIZZY_PUNCH"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_KNOCK_OFF"
level = 1

[[learnset.entries]]
slot = 5
move = "MOVE_CONFUSE_RAY"
level = 1

[[learnset.entries]]
slot = 6
move = "MOVE_FORESIGHT"
level = 1

[[learnset.entries]]
slot = 7
move = "MOVE_REVENGE"
level = 25

[[learnset.entries]]
slot = 8
move = "MOVE_WIDE_GUARD"
level = 40

[[learnset.entries]]
slot = 9
move = "MOVE_ZEN_HEADBUTT"
level = 50

[[learnset.entries]]
slot = 10
move = "MOVE_PAYBACK"
level = 65

[[learnset.entries]]
slot = 11
move = "MOVE_CRUSH_GRIP"
level = 75

[[learnset.entries]]
slot = 12
move = "MOVE_HEAVY_SLAM"
level = 90

[[learnset.entries]]
slot = 13
move = "MOVE_GIGA_IMPACT"
level = 100
