[learnset]
index = 487
species = "SPECIES_GIRATINA"

[[learnset.entries]]
slot = 0
move = "MOVE_DRAGONBREATH"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_SCARY_FACE"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_OMINOUS_WIND"
level = 6

[[learnset.entries]]
slot = 3
move = "MOVE_ANCIENTPOWER"
level = 10

[[learnset.entries]]
slot = 4
move = "MOVE_SLASH"
level = 15

[[learnset.entries]]
slot = 5
move = "MOVE_SHADOW_SNEAK"
level = 19

[[learnset.entries]]
slot = 6
move = "MOVE_DESTINY_BOND"
level = 24

[[learnset.entries]]
slot = 7
move = "MOVE_DRAGON_CLAW"
level = 28

[[learnset.entries]]
slot = 8
move = "MOVE_EARTH_POWER"
level = 33

[[learnset.entries]]
slot = 9
move = "MOVE_AURA_SPHERE"
level = 37

[[learnset.entries]]
slot = 10
move = "MOVE_SHADOW_CLAW"
level = 42

[[learnset.entries]]
slot = 11
move = "MOVE_SHADOW_FORCE"
level = 46

[[learnset.entries]]
slot = 12
move = "MOVE_HEX"
level = 50
