[learnset]
index = 488
species = "SPECIES_CRESSELIA"

[[learnset.entries]]
slot = 0
move = "MOVE_CONFUSION"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_DOUBLE_TEAM"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_SAFEGUARD"
level = 11

[[learnset.entries]]
slot = 3
move = "MOVE_MIST"
level = 20

[[learnset.entries]]
slot = 4
move = "MOVE_AURORA_BEAM"
level = 29

[[learnset.entries]]
slot = 5
move = "MOVE_FUTURE_SIGHT"
level = 38

[[learnset.entries]]
slot = 6
move = "MOVE_SLASH"
level = 47

[[learnset.entries]]
slot = 7
move = "MOVE_MOONLIGHT"
level = 57

[[learnset.entries]]
slot = 8
move = "MOVE_PSYCHO_CUT"
level = 66

[[learnset.entries]]
slot = 9
move = "MOVE_PSYCHO_SHIFT"
level = 75

[[learnset.entries]]
slot = 10
move = "MOVE_LUNAR_DANCE"
level = 84

[[learnset.entries]]
slot = 11
move = "MOVE_PSYCHIC"
level = 93
