[learnset]
index = 491
species = "SPECIES_DARKRAI"

[[learnset.entries]]
slot = 0
move = "MOVE_OMINOUS_WIND"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_DISABLE"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_QUICK_ATTACK"
level = 11

[[learnset.entries]]
slot = 3
move = "MOVE_HYPNOSIS"
level = 20

[[learnset.entries]]
slot = 4
move = "MOVE_FAINT_ATTACK"
level = 29

[[learnset.entries]]
slot = 5
move = "MOVE_NIGHTMARE"
level = 38

[[learnset.entries]]
slot = 6
move = "MOVE_DOUBLE_TEAM"
level = 47

[[learnset.entries]]
slot = 7
move = "MOVE_HAZE"
level = 57

[[learnset.entries]]
slot = 8
move = "MOVE_DARK_VOID"
level = 66

[[learnset.entries]]
slot = 9
move = "MOVE_NASTY_PLOT"
level = 75

[[learnset.entries]]
slot = 10
move = "MOVE_DREAM_EATER"
level = 84

[[learnset.entries]]
slot = 11
move = "MOVE_DARK_PULSE"
level = 93
