[learnset]
index = 493
species = "SPECIES_ARCEUS"

[[learnset.entries]]
slot = 0
move = "MOVE_SEISMIC_TOSS"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_COSMIC_POWER"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_NATURAL_GIFT"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_PUNISHMENT"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_GRAVITY"
level = 10

[[learnset.entries]]
slot = 5
move = "MOVE_EARTH_POWER"
level = 20

[[learnset.entries]]
slot = 6
move = "MOVE_HYPER_VOICE"
level = 30

[[learnset.entries]]
slot = 7
move = "MOVE_EXTREMESPEED"
level = 40

[[learnset.entries]]
slot = 8
move = "MOVE_REFRESH"
level = 50

[[learnset.entries]]
slot = 9
move = "MOVE_FUTURE_SIGHT"
level = 60

[[learnset.entries]]
slot = 10
move = "MOVE_RECOVER"
level = 70

[[learnset.entries]]
slot = 11
move = "MOVE_HYPER_BEAM"
level = 80

[[learnset.entries]]
slot = 12
move = "MOVE_PERISH_SONG"
level = 90

[[learnset.entries]]
slot = 13
move = "MOVE_JUDGMENT"
level = 100
