[learnset]
index = 499
species = "SPECIES_PIGNITE"

[[learnset.entries]]
slot = 0
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_TAIL_WHIP"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_EMBER"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_ODOR_SLEUTH"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_TAIL_WHIP"
level = 3

[[learnset.entries]]
slot = 5
move = "MOVE_EMBER"
level = 7

[[learnset.entries]]
slot = 6
move = "MOVE_ODOR_SLEUTH"
level = 9

[[learnset.entries]]
slot = 7
move = "MOVE_DEFENSE_CURL"
level = 13

[[learnset.entries]]
slot = 8
move = "MOVE_FLAME_CHARGE"
level = 15

[[learnset.entries]]
slot = 9
move = "MOVE_ARM_THRUST"
level = 17

[[learnset.entries]]
slot = 10
move = "MOVE_SMOG"
level = 20

[[learnset.entries]]
slot = 11
move = "MOVE_ROLLOUT"
level = 23

[[learnset.entries]]
slot = 12
move = "MOVE_TAKE_DOWN"
level = 28

[[learnset.entries]]
slot = 13
move = "MOVE_HEAT_CRASH"
level = 31

[[learnset.entries]]
slot = 14
move = "MOVE_ASSURANCE"
level = 36

[[learnset.entries]]
slot = 15
move = "MOVE_FLAMETHROWER"
level = 39

[[learnset.entries]]
slot = 16
move = "MOVE_HEAD_SMASH"
level = 44

[[learnset.entries]]
slot = 17
move = "MOVE_ROAR"
level = 47

[[learnset.entries]]
slot = 18
move = "MOVE_FLARE_BLITZ"
level = 52
