[learnset]
index = 507
species = "SPECIES_HERDIER"

[[learnset.entries]]
slot = 0
move = "MOVE_LEER"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_ODOR_SLEUTH"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_BITE"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_ODOR_SLEUTH"
level = 5

[[learnset.entries]]
slot = 5
move = "MOVE_BITE"
level = 8

[[learnset.entries]]
slot = 6
move = "MOVE_HELPING_HAND"
level = 12

[[learnset.entries]]
slot = 7
move = "MOVE_TAKE_DOWN"
level = 15

[[learnset.entries]]
slot = 8
move = "MOVE_WORK_UP"
level = 20

[[learnset.entries]]
slot = 9
move = "MOVE_CRUNCH"
level = 24

[[learnset.entries]]
slot = 10
move = "MOVE_ROAR"
level = 29

[[learnset.entries]]
slot = 11
move = "MOVE_RETALIATE"
level = 33

[[learnset.entries]]
slot = 12
move = "MOVE_REVERSAL"
level = 38

[[learnset.entries]]
slot = 13
move = "MOVE_LAST_RESORT"
level = 42

[[learnset.entries]]
slot = 14
move = "MOVE_GIGA_IMPACT"
level = 47
