[learnset]
index = 509
species = "SPECIES_PURRLOIN"

[[learnset.entries]]
slot = 0
move = "MOVE_SCRATCH"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_GROWL"
level = 3

[[learnset.entries]]
slot = 2
move = "MOVE_ASSIST"
level = 6

[[learnset.entries]]
slot = 3
move = "MOVE_SANDATTACK"
level = 10

[[learnset.entries]]
slot = 4
move = "MOVE_FURY_SWIPES"
level = 12

[[learnset.entries]]
slot = 5
move = "MOVE_PURSUIT"
level = 15

[[learnset.entries]]
slot = 6
move = "MOVE_TORMENT"
level = 19

[[learnset.entries]]
slot = 7
move = "MOVE_FAKE_OUT"
level = 21

[[learnset.entries]]
slot = 8
move = "MOVE_HONE_CLAWS"
level = 24

[[learnset.entries]]
slot = 9
move = "MOVE_ASSURANCE"
level = 28

[[learnset.entries]]
slot = 10
move = "MOVE_SLASH"
level = 30

[[learnset.entries]]
slot = 11
move = "MOVE_CAPTIVATE"
level = 33

[[learnset.entries]]
slot = 12
move = "MOVE_NIGHT_SLASH"
level = 37

[[learnset.entries]]
slot = 13
move = "MOVE_SNATCH"
level = 39

[[learnset.entries]]
slot = 14
move = "MOVE_NASTY_PLOT"
level = 42

[[learnset.entries]]
slot = 15
move = "MOVE_SUCKER_PUNCH"
level = 46
