[learnset]
index = 512
species = "SPECIES_SIMISAGE"

[[learnset.entries]]
slot = 0
move = "MOVE_LEER"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_LICK"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_FURY_SWIPES"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_SEED_BOMB"
level = 1
