[learnset]
index = 516
species = "SPECIES_SIMIPOUR"

[[learnset.entries]]
slot = 0
move = "MOVE_LEER"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_LICK"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_FURY_SWIPES"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_SCALD"
level = 1
