[learnset]
index = 518
species = "SPECIES_MUSHARNA"

[[learnset.entries]]
slot = 0
move = "MOVE_DEFENSE_CURL"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_LUCKY_CHANT"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_PSYBEAM"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_HYPNOSIS"
level = 1
