[learnset]
index = 521
species = "SPECIES_UNFEZANT"

[[learnset.entries]]
slot = 0
move = "MOVE_GUST"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_GROWL"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_LEER"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_QUICK_ATTACK"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_GROWL"
level = 4

[[learnset.entries]]
slot = 5
move = "MOVE_LEER"
level = 8

[[learnset.entries]]
slot = 6
move = "MOVE_QUICK_ATTACK"
level = 11

[[learnset.entries]]
slot = 7
move = "MOVE_AIR_CUTTER"
level = 15

[[learnset.entries]]
slot = 8
move = "MOVE_ROOST"
level = 18

[[learnset.entries]]
slot = 9
move = "MOVE_DETECT"
level = 23

[[learnset.entries]]
slot = 10
move = "MOVE_TAUNT"
level = 27

[[learnset.entries]]
slot = 11
move = "MOVE_AIR_SLASH"
level = 33

[[learnset.entries]]
slot = 12
move = "MOVE_RAZOR_WIND"
level = 38

[[learnset.entries]]
slot = 13
move = "MOVE_FEATHERDANCE"
level = 44

[[learnset.entries]]
slot = 14
move = "MOVE_SWAGGER"
level = 49

[[learnset.entries]]
slot = 15
move = "MOVE_FACADE"
level = 55

[[learnset.entries]]
slot = 16
move = "MOVE_TAILWIND"
level = 60

[[learnset.entries]]
slot = 17
move = "MOVE_SKY_ATTACK"
level = 66
