[learnset]
index = 526
species = "SPECIES_GIGALITH"

[[learnset.entries]]
slot = 0
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_HARDEN"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_SANDATTACK"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_HEADBUTT"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_HARDEN"
level = 4

[[learnset.entries]]
slot = 5
move = "MOVE_SANDATTACK"
level = 7

[[learnset.entries]]
slot = 6
move = "MOVE_HEADBUTT"
level = 10

[[learnset.entries]]
slot = 7
move = "MOVE_ROCK_BLAST"
level = 14

[[learnset.entries]]
slot = 8
move = "MOVE_MUDSLAP"
level = 17

[[learnset.entries]]
slot = 9
move = "MOVE_IRON_DEFENSE"
level = 20

[[learnset.entries]]
slot = 10
move = "MOVE_SMACK_DOWN"
level = 23

[[learnset.entries]]
slot = 11
move = "MOVE_POWER_GEM"
level = 25

[[learnset.entries]]
slot = 12
move = "MOVE_ROCK_SLIDE"
level = 30

[[learnset.entries]]
slot = 13
move = "MOVE_STEALTH_ROCK"
level = 36

[[learnset.entries]]
slot = 14
move = "MOVE_SANDSTORM"
level = 42

[[learnset.entries]]
slot = 15
move = "MOVE_STONE_EDGE"
level = 48

[[learnset.entries]]
slot = 16
move = "MOVE_EXPLOSION"
level = 55
