[learnset]
index = 527
species = "SPECIES_WOOBAT"

[[learnset.entries]]
slot = 0
move = "MOVE_CONFUSION"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_ODOR_SLEUTH"
level = 4

[[learnset.entries]]
slot = 2
move = "MOVE_GUST"
level = 8

[[learnset.entries]]
slot = 3
move = "MOVE_ASSURANCE"
level = 12

[[learnset.entries]]
slot = 4
move = "MOVE_HEART_STAMP"
level = 15

[[learnset.entries]]
slot = 5
move = "MOVE_IMPRISON"
level = 19

[[learnset.entries]]
slot = 6
move = "MOVE_AIR_CUTTER"
level = 21

[[learnset.entries]]
slot = 7
move = "MOVE_ATTRACT"
level = 25

[[learnset.entries]]
slot = 8
move = "MOVE_AMNESIA"
level = 29

[[learnset.entries]]
slot = 9
move = "MOVE_CALM_MIND"
level = 29

[[learnset.entries]]
slot = 10
move = "MOVE_AIR_SLASH"
level = 32

[[learnset.entries]]
slot = 11
move = "MOVE_FUTURE_SIGHT"
level = 36

[[learnset.entries]]
slot = 12
move = "MOVE_PSYCHIC"
level = 41

[[learnset.entries]]
slot = 13
move = "MOVE_ENDEAVOR"
level = 47
