[learnset]
index = 529
species = "SPECIES_DRILBUR"

[[learnset.entries]]
slot = 0
move = "MOVE_SCRATCH"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_MUD_SPORT"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_RAPID_SPIN"
level = 5

[[learnset.entries]]
slot = 3
move = "MOVE_MUDSLAP"
level = 8

[[learnset.entries]]
slot = 4
move = "MOVE_FURY_SWIPES"
level = 12

[[learnset.entries]]
slot = 5
move = "MOVE_METAL_CLAW"
level = 15

[[learnset.entries]]
slot = 6
move = "MOVE_DIG"
level = 19

[[learnset.entries]]
slot = 7
move = "MOVE_HONE_CLAWS"
level = 22

[[learnset.entries]]
slot = 8
move = "MOVE_SLASH"
level = 26

[[learnset.entries]]
slot = 9
move = "MOVE_ROCK_SLIDE"
level = 29

[[learnset.entries]]
slot = 10
move = "MOVE_EARTHQUAKE"
level = 33

[[learnset.entries]]
slot = 11
move = "MOVE_SWORDS_DANCE"
level = 36

[[learnset.entries]]
slot = 12
move = "MOVE_SANDSTORM"
level = 40

[[learnset.entries]]
slot = 13
move = "MOVE_DRILL_RUN"
level = 43

[[learnset.entries]]
slot = 14
move = "MOVE_FISSURE"
level = 47
