[learnset]
index = 531
species = "SPECIES_AUDINO"

[[learnset.entries]]
slot = 0
move = "MOVE_POUND"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_GROWL"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_HELPING_HAND"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_REFRESH"
level = 5

[[learnset.entries]]
slot = 4
move = "MOVE_DOUBLESLAP"
level = 10

[[learnset.entries]]
slot = 5
move = "MOVE_ATTRACT"
level = 15

[[learnset.entries]]
slot = 6
move = "MOVE_SECRET_POWER"
level = 20

[[learnset.entries]]
slot = 7
move = "MOVE_ENTRAINMENT"
level = 25

[[learnset.entries]]
slot = 8
move = "MOVE_TAKE_DOWN"
level = 30

[[learnset.entries]]
slot = 9
move = "MOVE_HEAL_PULSE"
level = 35

[[learnset.entries]]
slot = 10
move = "MOVE_AFTER_YOU"
level = 40

[[learnset.entries]]
slot = 11
move = "MOVE_SIMPLE_BEAM"
level = 45

[[learnset.entries]]
slot = 12
move = "MOVE_DOUBLEEDGE"
level = 50

[[learnset.entries]]
slot = 13
move = "MOVE_LAST_RESORT"
level = 55
