[learnset]
index = 540
species = "SPECIES_SEWADDLE"

[[learnset.entries]]
slot = 0
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_STRING_SHOT"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_BUG_BITE"
level = 8

[[learnset.entries]]
slot = 3
move = "MOVE_RAZOR_LEAF"
level = 15

[[learnset.entries]]
slot = 4
move = "MOVE_STRUGGLE_BUG"
level = 22

[[learnset.entries]]
slot = 5
move = "MOVE_ENDURE"
level = 29

[[learnset.entries]]
slot = 6
move = "MOVE_BUG_BUZZ"
level = 36

[[learnset.entries]]
slot = 7
move = "MOVE_FLAIL"
level = 43
