[learnset]
index = 541
species = "SPECIES_SWADLOON"

[[learnset.entries]]
slot = 0
move = "MOVE_GRASSWHISTLE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_STRING_SHOT"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_BUG_BITE"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_RAZOR_LEAF"
level = 1

[[learnset.entries]]
slot = 5
move = "MOVE_PROTECT"
level = 20
