[learnset]
index = 542
species = "SPECIES_LEAVANNY"

[[learnset.entries]]
slot = 0
move = "MOVE_FALSE_SWIPE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_STRING_SHOT"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_BUG_BITE"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_RAZOR_LEAF"
level = 1

[[learnset.entries]]
slot = 5
move = "MOVE_BUG_BITE"
level = 8

[[learnset.entries]]
slot = 6
move = "MOVE_RAZOR_LEAF"
level = 15

[[learnset.entries]]
slot = 7
move = "MOVE_STRUGGLE_BUG"
level = 22

[[learnset.entries]]
slot = 8
move = "MOVE_SLASH"
level = 29

[[learnset.entries]]
slot = 9
move = "MOVE_HELPING_HAND"
level = 32

[[learnset.entries]]
slot = 10
move = "MOVE_LEAF_BLADE"
level = 36

[[learnset.entries]]
slot = 11
move = "MOVE_XSCISSOR"
level = 39

[[learnset.entries]]
slot = 12
move = "MOVE_ENTRAINMENT"
level = 43

[[learnset.entries]]
slot = 13
move = "MOVE_SWORDS_DANCE"
level = 46

[[learnset.entries]]
slot = 14
move = "MOVE_LEAF_STORM"
level = 50
