[learnset]
index = 547
species = "SPECIES_WHIMSICOTT"

[[learnset.entries]]
slot = 0
move = "MOVE_GROWTH"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_LEECH_SEED"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_MEGA_DRAIN"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_COTTON_SPORE"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_GUST"
level = 10

[[learnset.entries]]
slot = 5
move = "MOVE_TAILWIND"
level = 28

[[learnset.entries]]
slot = 6
move = "MOVE_HURRICANE"
level = 46
