[learnset]
index = 548
species = "SPECIES_PETILIL"

[[learnset.entries]]
slot = 0
move = "MOVE_ABSORB"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_GROWTH"
level = 4

[[learnset.entries]]
slot = 2
move = "MOVE_LEECH_SEED"
level = 8

[[learnset.entries]]
slot = 3
move = "MOVE_SLEEP_POWDER"
level = 10

[[learnset.entries]]
slot = 4
move = "MOVE_MEGA_DRAIN"
level = 13

[[learnset.entries]]
slot = 5
move = "MOVE_SYNTHESIS"
level = 17

[[learnset.entries]]
slot = 6
move = "MOVE_MAGICAL_LEAF"
level = 19

[[learnset.entries]]
slot = 7
move = "MOVE_STUN_SPORE"
level = 22

[[learnset.entries]]
slot = 8
move = "MOVE_GIGA_DRAIN"
level = 26

[[learnset.entries]]
slot = 9
move = "MOVE_AROMATHERAPY"
level = 28

[[learnset.entries]]
slot = 10
move = "MOVE_HELPING_HAND"
level = 31

[[learnset.entries]]
slot = 11
move = "MOVE_ENERGY_BALL"
level = 35

[[learnset.entries]]
slot = 12
move = "MOVE_ENTRAINMENT"
level = 37

[[learnset.entries]]
slot = 13
move = "MOVE_SUNNY_DAY"
level = 40

[[learnset.entries]]
slot = 14
move = "MOVE_AFTER_YOU"
level = 44

[[learnset.entries]]
slot = 15
move = "MOVE_LEAF_STORM"
level = 46
