[learnset]
index = 549
species = "SPECIES_LILLIGANT"

[[learnset.entries]]
slot = 0
move = "MOVE_GROWTH"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_LEECH_SEED"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_MEGA_DRAIN"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_SYNTHESIS"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_TEETER_DANCE"
level = 10

[[learnset.entries]]
slot = 5
move = "MOVE_QUIVER_DANCE"
level = 28

[[learnset.entries]]
slot = 6
move = "MOVE_PETAL_DANCE"
level = 46
