[learnset]
index = 555
species = "SPECIES_DARMANITAN"

[[learnset.entries]]
slot = 0
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_ROLLOUT"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_INCINERATE"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_RAGE"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_ROLLOUT"
level = 3

[[learnset.entries]]
slot = 5
move = "MOVE_INCINERATE"
level = 6

[[learnset.entries]]
slot = 6
move = "MOVE_RAGE"
level = 9

[[learnset.entries]]
slot = 7
move = "MOVE_FIRE_FANG"
level = 11

[[learnset.entries]]
slot = 8
move = "MOVE_HEADBUTT"
level = 14

[[learnset.entries]]
slot = 9
move = "MOVE_SWAGGER"
level = 17

[[learnset.entries]]
slot = 10
move = "MOVE_FACADE"
level = 19

[[learnset.entries]]
slot = 11
move = "MOVE_FIRE_PUNCH"
level = 22

[[learnset.entries]]
slot = 12
move = "MOVE_WORK_UP"
level = 25

[[learnset.entries]]
slot = 13
move = "MOVE_THRASH"
level = 27

[[learnset.entries]]
slot = 14
move = "MOVE_BELLY_DRUM"
level = 30

[[learnset.entries]]
slot = 15
move = "MOVE_FLARE_BLITZ"
level = 33

[[learnset.entries]]
slot = 16
move = "MOVE_HAMMER_ARM"
level = 35

[[learnset.entries]]
slot = 17
move = "MOVE_TAUNT"
level = 39

[[learnset.entries]]
slot = 18
move = "MOVE_SUPERPOWER"
level = 47

[[learnset.entries]]
slot = 19
move = "MOVE_OVERHEAT"
level = 54
