[learnset]
index = 557
species = "SPECIES_DWEBBLE"

[[learnset.entries]]
slot = 0
move = "MOVE_FURY_CUTTER"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_ROCK_BLAST"
level = 5

[[learnset.entries]]
slot = 2
move = "MOVE_WITHDRAW"
level = 7

[[learnset.entries]]
slot = 3
move = "MOVE_SANDATTACK"
level = 11

[[learnset.entries]]
slot = 4
move = "MOVE_FAINT_ATTACK"
level = 13

[[learnset.entries]]
slot = 5
move = "MOVE_SMACK_DOWN"
level = 17

[[learnset.entries]]
slot = 6
move = "MOVE_ROCK_POLISH"
level = 19

[[learnset.entries]]
slot = 7
move = "MOVE_BUG_BITE"
level = 23

[[learnset.entries]]
slot = 8
move = "MOVE_STEALTH_ROCK"
level = 24

[[learnset.entries]]
slot = 9
move = "MOVE_ROCK_SLIDE"
level = 29

[[learnset.entries]]
slot = 10
move = "MOVE_SLASH"
level = 31

[[learnset.entries]]
slot = 11
move = "MOVE_XSCISSOR"
level = 35

[[learnset.entries]]
slot = 12
move = "MOVE_SHELL_SMASH"
level = 37

[[learnset.entries]]
slot = 13
move = "MOVE_FLAIL"
level = 41

[[learnset.entries]]
slot = 14
move = "MOVE_ROCK_WRECKER"
level = 43
