[learnset]
index = 561
species = "SPECIES_SIGILYPH"

[[learnset.entries]]
slot = 0
move = "MOVE_GUST"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_MIRACLE_EYE"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_HYPNOSIS"
level = 4

[[learnset.entries]]
slot = 3
move = "MOVE_PSYWAVE"
level = 8

[[learnset.entries]]
slot = 4
move = "MOVE_TAILWIND"
level = 11

[[learnset.entries]]
slot = 5
move = "MOVE_WHIRLWIND"
level = 14

[[learnset.entries]]
slot = 6
move = "MOVE_PSYBEAM"
level = 18

[[learnset.entries]]
slot = 7
move = "MOVE_AIR_CUTTER"
level = 21

[[learnset.entries]]
slot = 8
move = "MOVE_LIGHT_SCREEN"
level = 24

[[learnset.entries]]
slot = 9
move = "MOVE_REFLECT"
level = 28

[[learnset.entries]]
slot = 10
move = "MOVE_SYNCHRONOISE"
level = 31

[[learnset.entries]]
slot = 11
move = "MOVE_MIRROR_MOVE"
level = 34

[[learnset.entries]]
slot = 12
move = "MOVE_GRAVITY"
level = 38

[[learnset.entries]]
slot = 13
move = "MOVE_AIR_SLASH"
level = 41

[[learnset.entries]]
slot = 14
move = "MOVE_PSYCHIC"
level = 44

[[learnset.entries]]
slot = 15
move = "MOVE_COSMIC_POWER"
level = 48

[[learnset.entries]]
slot = 16
move = "MOVE_SKY_ATTACK"
level = 51
