[learnset]
index = 567
species = "SPECIES_ARCHEOPS"

[[learnset.entries]]
slot = 0
move = "MOVE_QUICK_ATTACK"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_LEER"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_WING_ATTACK"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_ROCK_THROW"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_ROCK_THROW"
level = 5

[[learnset.entries]]
slot = 5
move = "MOVE_DOUBLE_TEAM"
level = 8

[[learnset.entries]]
slot = 6
move = "MOVE_SCARY_FACE"
level = 11

[[learnset.entries]]
slot = 7
move = "MOVE_PLUCK"
level = 15

[[learnset.entries]]
slot = 8
move = "MOVE_ANCIENTPOWER"
level = 18

[[learnset.entries]]
slot = 9
move = "MOVE_AGILITY"
level = 21

[[learnset.entries]]
slot = 10
move = "MOVE_QUICK_GUARD"
level = 25

[[learnset.entries]]
slot = 11
move = "MOVE_ACROBATICS"
level = 28

[[learnset.entries]]
slot = 12
move = "MOVE_DRAGONBREATH"
level = 31

[[learnset.entries]]
slot = 13
move = "MOVE_CRUNCH"
level = 35

[[learnset.entries]]
slot = 14
move = "MOVE_ENDEAVOR"
level = 40

[[learnset.entries]]
slot = 15
move = "MOVE_UTURN"
level = 45

[[learnset.entries]]
slot = 16
move = "MOVE_ROCK_SLIDE"
level = 51

[[learnset.entries]]
slot = 17
move = "MOVE_DRAGON_CLAW"
level = 56

[[learnset.entries]]
slot = 18
move = "MOVE_THRASH"
level = 61
