[learnset]
index = 571
species = "SPECIES_ZOROARK"

[[learnset.entries]]
slot = 0
move = "MOVE_UTURN"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_SCRATCH"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_LEER"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_PURSUIT"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_HONE_CLAWS"
level = 1

[[learnset.entries]]
slot = 5
move = "MOVE_PURSUIT"
level = 5

[[learnset.entries]]
slot = 6
move = "MOVE_HONE_CLAWS"
level = 9

[[learnset.entries]]
slot = 7
move = "MOVE_FURY_SWIPES"
level = 13

[[learnset.entries]]
slot = 8
move = "MOVE_FAINT_ATTACK"
level = 17

[[learnset.entries]]
slot = 9
move = "MOVE_SCARY_FACE"
level = 21

[[learnset.entries]]
slot = 10
move = "MOVE_TAUNT"
level = 25

[[learnset.entries]]
slot = 11
move = "MOVE_FOUL_PLAY"
level = 29

[[learnset.entries]]
slot = 12
move = "MOVE_NIGHT_SLASH"
level = 30

[[learnset.entries]]
slot = 13
move = "MOVE_TORMENT"
level = 34

[[learnset.entries]]
slot = 14
move = "MOVE_AGILITY"
level = 39

[[learnset.entries]]
slot = 15
move = "MOVE_EMBARGO"
level = 44

[[learnset.entries]]
slot = 16
move = "MOVE_PUNISHMENT"
level = 49

[[learnset.entries]]
slot = 17
move = "MOVE_NASTY_PLOT"
level = 54

[[learnset.entries]]
slot = 18
move = "MOVE_IMPRISON"
level = 59

[[learnset.entries]]
slot = 19
move = "MOVE_NIGHT_DAZE"
level = 64
