[learnset]
index = 573
species = "SPECIES_CINCCINO"

[[learnset.entries]]
slot = 0
move = "MOVE_BULLET_SEED"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_ROCK_BLAST"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_HELPING_HAND"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_TICKLE"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_SING"
level = 1

[[learnset.entries]]
slot = 5
move = "MOVE_TAIL_SLAP"
level = 1
