[learnset]
index = 576
species = "SPECIES_GOTHITELLE"

[[learnset.entries]]
slot = 0
move = "MOVE_POUND"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_CONFUSION"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_TICKLE"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_FAKE_TEARS"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_CONFUSION"
level = 3

[[learnset.entries]]
slot = 5
move = "MOVE_TICKLE"
level = 7

[[learnset.entries]]
slot = 6
move = "MOVE_FAKE_TEARS"
level = 10

[[learnset.entries]]
slot = 7
move = "MOVE_DOUBLESLAP"
level = 14

[[learnset.entries]]
slot = 8
move = "MOVE_PSYBEAM"
level = 16

[[learnset.entries]]
slot = 9
move = "MOVE_EMBARGO"
level = 19

[[learnset.entries]]
slot = 10
move = "MOVE_FAINT_ATTACK"
level = 24

[[learnset.entries]]
slot = 11
move = "MOVE_PSYSHOCK"
level = 25

[[learnset.entries]]
slot = 12
move = "MOVE_FLATTER"
level = 28

[[learnset.entries]]
slot = 13
move = "MOVE_FUTURE_SIGHT"
level = 31

[[learnset.entries]]
slot = 14
move = "MOVE_HEAL_BLOCK"
level = 34

[[learnset.entries]]
slot = 15
move = "MOVE_PSYCHIC"
level = 39

[[learnset.entries]]
slot = 16
move = "MOVE_TELEKINESIS"
level = 45

[[learnset.entries]]
slot = 17
move = "MOVE_CHARM"
level = 54

[[learnset.entries]]
slot = 18
move = "MOVE_MAGIC_ROOM"
level = 59
