[learnset]
index = 578
species = "SPECIES_DUOSION"

[[learnset.entries]]
slot = 0
move = "MOVE_PSYWAVE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_REFLECT"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_ROLLOUT"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_SNATCH"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_REFLECT"
level = 3

[[learnset.entries]]
slot = 5
move = "MOVE_ROLLOUT"
level = 7

[[learnset.entries]]
slot = 6
move = "MOVE_SNATCH"
level = 10

[[learnset.entries]]
slot = 7
move = "MOVE_HIDDEN_POWER"
level = 14

[[learnset.entries]]
slot = 8
move = "MOVE_LIGHT_SCREEN"
level = 16

[[learnset.entries]]
slot = 9
move = "MOVE_CHARM"
level = 19

[[learnset.entries]]
slot = 10
move = "MOVE_RECOVER"
level = 24

[[learnset.entries]]
slot = 11
move = "MOVE_PSYSHOCK"
level = 25

[[learnset.entries]]
slot = 12
move = "MOVE_ENDEAVOR"
level = 28

[[learnset.entries]]
slot = 13
move = "MOVE_FUTURE_SIGHT"
level = 31

[[learnset.entries]]
slot = 14
move = "MOVE_PAIN_SPLIT"
level = 34

[[learnset.entries]]
slot = 15
move = "MOVE_PSYCHIC"
level = 39

[[learnset.entries]]
slot = 16
move = "MOVE_SKILL_SWAP"
level = 43

[[learnset.entries]]
slot = 17
move = "MOVE_HEAL_BLOCK"
level = 50

[[learnset.entries]]
slot = 18
move = "MOVE_WONDER_ROOM"
level = 53
