[learnset]
index = 591
species = "SPECIES_AMOONGUSS"

[[learnset.entries]]
slot = 0
move = "MOVE_ABSORB"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_GROWTH"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_ASTONISH"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_BIDE"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_GROWTH"
level = 6

[[learnset.entries]]
slot = 5
move = "MOVE_ASTONISH"
level = 8

[[learnset.entries]]
slot = 6
move = "MOVE_BIDE"
level = 12

[[learnset.entries]]
slot = 7
move = "MOVE_MEGA_DRAIN"
level = 15

[[learnset.entries]]
slot = 8
move = "MOVE_INGRAIN"
level = 18

[[learnset.entries]]
slot = 9
move = "MOVE_FAINT_ATTACK"
level = 20

[[learnset.entries]]
slot = 10
move = "MOVE_SWEET_SCENT"
level = 24

[[learnset.entries]]
slot = 11
move = "MOVE_GIGA_DRAIN"
level = 28

[[learnset.entries]]
slot = 12
move = "MOVE_TOXIC"
level = 32

[[learnset.entries]]
slot = 13
move = "MOVE_SYNTHESIS"
level = 35

[[learnset.entries]]
slot = 14
move = "MOVE_CLEAR_SMOG"
level = 43

[[learnset.entries]]
slot = 15
move = "MOVE_SOLARBEAM"
level = 49

[[learnset.entries]]
slot = 16
move = "MOVE_RAGE_POWDER"
level = 54

[[learnset.entries]]
slot = 17
move = "MOVE_SPORE"
level = 62
