[learnset]
index = 597
species = "SPECIES_FERROSEED"

[[learnset.entries]]
slot = 0
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_HARDEN"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_ROLLOUT"
level = 6

[[learnset.entries]]
slot = 3
move = "MOVE_CURSE"
level = 9

[[learnset.entries]]
slot = 4
move = "MOVE_METAL_CLAW"
level = 14

[[learnset.entries]]
slot = 5
move = "MOVE_PIN_MISSILE"
level = 18

[[learnset.entries]]
slot = 6
move = "MOVE_GYRO_BALL"
level = 21

[[learnset.entries]]
slot = 7
move = "MOVE_IRON_DEFENSE"
level = 26

[[learnset.entries]]
slot = 8
move = "MOVE_MIRROR_SHOT"
level = 30

[[learnset.entries]]
slot = 9
move = "MOVE_INGRAIN"
level = 35

[[learnset.entries]]
slot = 10
move = "MOVE_SELFDESTRUCT"
level = 38

[[learnset.entries]]
slot = 11
move = "MOVE_IRON_HEAD"
level = 43

[[learnset.entries]]
slot = 12
move = "MOVE_PAYBACK"
level = 47

[[learnset.entries]]
slot = 13
move = "MOVE_FLASH_CANNON"
level = 52

[[learnset.entries]]
slot = 14
move = "MOVE_EXPLOSION"
level = 55
