[learnset]
index = 602
species = "SPECIES_TYNAMO"

[[learnset.entries]]
slot = 0
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_THUNDER_WAVE"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_SPARK"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_CHARGE_BEAM"
level = 1
