[learnset]
index = 604
species = "SPECIES_EELEKTROSS"

[[learnset.entries]]
slot = 0
move = "MOVE_CRUSH_CLAW"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_HEADBUTT"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_ACID"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_DISCHARGE"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_CRUNCH"
level = 1
