[learnset]
index = 605
species = "SPECIES_ELGYEM"

[[learnset.entries]]
slot = 0
move = "MOVE_CONFUSION"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_GROWL"
level = 4

[[learnset.entries]]
slot = 2
move = "MOVE_HEAL_BLOCK"
level = 8

[[learnset.entries]]
slot = 3
move = "MOVE_MIRACLE_EYE"
level = 11

[[learnset.entries]]
slot = 4
move = "MOVE_PSYBEAM"
level = 15

[[learnset.entries]]
slot = 5
move = "MOVE_HEADBUTT"
level = 18

[[learnset.entries]]
slot = 6
move = "MOVE_HIDDEN_POWER"
level = 22

[[learnset.entries]]
slot = 7
move = "MOVE_IMPRISON"
level = 25

[[learnset.entries]]
slot = 8
move = "MOVE_SIMPLE_BEAM"
level = 29

[[learnset.entries]]
slot = 9
move = "MOVE_ZEN_HEADBUTT"
level = 32

[[learnset.entries]]
slot = 10
move = "MOVE_PSYCH_UP"
level = 36

[[learnset.entries]]
slot = 11
move = "MOVE_PSYCHIC"
level = 39

[[learnset.entries]]
slot = 12
move = "MOVE_CALM_MIND"
level = 43

[[learnset.entries]]
slot = 13
move = "MOVE_RECOVER"
level = 46

[[learnset.entries]]
slot = 14
move = "MOVE_GUARD_SPLIT"
level = 50

[[learnset.entries]]
slot = 15
move = "MOVE_POWER_SPLIT"
level = 50

[[learnset.entries]]
slot = 16
move = "MOVE_SYNCHRONOISE"
level = 53

[[learnset.entries]]
slot = 17
move = "MOVE_WONDER_ROOM"
level = 56
