[learnset]
index = 609
species = "SPECIES_CHANDELURE"

[[learnset.entries]]
slot = 0
move = "MOVE_SMOG"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_CONFUSE_RAY"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_FLAME_BURST"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_HEX"
level = 1
