[learnset]
index = 614
species = "SPECIES_BEARTIC"

[[learnset.entries]]
slot = 0
move = "MOVE_SUPERPOWER"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_AQUA_JET"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_POWDER_SNOW"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_GROWL"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_BIDE"
level = 1

[[learnset.entries]]
slot = 5
move = "MOVE_ICY_WIND"
level = 1

[[learnset.entries]]
slot = 6
move = "MOVE_GROWL"
level = 5

[[learnset.entries]]
slot = 7
move = "MOVE_BIDE"
level = 9

[[learnset.entries]]
slot = 8
move = "MOVE_ICY_WIND"
level = 13

[[learnset.entries]]
slot = 9
move = "MOVE_FURY_SWIPES"
level = 17

[[learnset.entries]]
slot = 10
move = "MOVE_BRINE"
level = 21

[[learnset.entries]]
slot = 11
move = "MOVE_ENDURE"
level = 25

[[learnset.entries]]
slot = 12
move = "MOVE_SWAGGER"
level = 29

[[learnset.entries]]
slot = 13
move = "MOVE_SLASH"
level = 33

[[learnset.entries]]
slot = 14
move = "MOVE_FLAIL"
level = 36

[[learnset.entries]]
slot = 15
move = "MOVE_ICICLE_CRASH"
level = 37

[[learnset.entries]]
slot = 16
move = "MOVE_REST"
level = 41

[[learnset.entries]]
slot = 17
move = "MOVE_BLIZZARD"
level = 45

[[learnset.entries]]
slot = 18
move = "MOVE_HAIL"
level = 53

[[learnset.entries]]
slot = 19
move = "MOVE_THRASH"
level = 59

[[learnset.entries]]
slot = 20
move = "MOVE_SHEER_COLD"
level = 66
