[learnset]
index = 618
species = "SPECIES_STUNFISK"

[[learnset.entries]]
slot = 0
move = "MOVE_MUDSLAP"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_MUD_SPORT"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_BIDE"
level = 5

[[learnset.entries]]
slot = 3
move = "MOVE_THUNDERSHOCK"
level = 9

[[learnset.entries]]
slot = 4
move = "MOVE_MUD_SHOT"
level = 13

[[learnset.entries]]
slot = 5
move = "MOVE_CAMOUFLAGE"
level = 17

[[learnset.entries]]
slot = 6
move = "MOVE_MUD_BOMB"
level = 21

[[learnset.entries]]
slot = 7
move = "MOVE_DISCHARGE"
level = 25

[[learnset.entries]]
slot = 8
move = "MOVE_ENDURE"
level = 30

[[learnset.entries]]
slot = 9
move = "MOVE_BOUNCE"
level = 35

[[learnset.entries]]
slot = 10
move = "MOVE_MUDDY_WATER"
level = 40

[[learnset.entries]]
slot = 11
move = "MOVE_THUNDERBOLT"
level = 45

[[learnset.entries]]
slot = 12
move = "MOVE_REVENGE"
level = 50

[[learnset.entries]]
slot = 13
move = "MOVE_FLAIL"
level = 55

[[learnset.entries]]
slot = 14
move = "MOVE_FISSURE"
level = 61
