[learnset]
index = 621
species = "SPECIES_DRUDDIGON"

[[learnset.entries]]
slot = 0
move = "MOVE_LEER"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_SCRATCH"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_HONE_CLAWS"
level = 5

[[learnset.entries]]
slot = 3
move = "MOVE_BITE"
level = 9

[[learnset.entries]]
slot = 4
move = "MOVE_SCARY_FACE"
level = 13

[[learnset.entries]]
slot = 5
move = "MOVE_DRAGON_RAGE"
level = 18

[[learnset.entries]]
slot = 6
move = "MOVE_SLASH"
level = 21

[[learnset.entries]]
slot = 7
move = "MOVE_CRUNCH"
level = 25

[[learnset.entries]]
slot = 8
move = "MOVE_DRAGON_CLAW"
level = 27

[[learnset.entries]]
slot = 9
move = "MOVE_CHIP_AWAY"
level = 31

[[learnset.entries]]
slot = 10
move = "MOVE_REVENGE"
level = 35

[[learnset.entries]]
slot = 11
move = "MOVE_NIGHT_SLASH"
level = 40

[[learnset.entries]]
slot = 12
move = "MOVE_DRAGON_TAIL"
level = 45

[[learnset.entries]]
slot = 13
move = "MOVE_ROCK_CLIMB"
level = 49

[[learnset.entries]]
slot = 14
move = "MOVE_SUPERPOWER"
level = 55

[[learnset.entries]]
slot = 15
move = "MOVE_OUTRAGE"
level = 62
