[learnset]
index = 624
species = "SPECIES_PAWNIARD"

[[learnset.entries]]
slot = 0
move = "MOVE_SCRATCH"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_LEER"
level = 6

[[learnset.entries]]
slot = 2
move = "MOVE_FURY_CUTTER"
level = 9

[[learnset.entries]]
slot = 3
move = "MOVE_TORMENT"
level = 14

[[learnset.entries]]
slot = 4
move = "MOVE_FAINT_ATTACK"
level = 17

[[learnset.entries]]
slot = 5
move = "MOVE_SCARY_FACE"
level = 22

[[learnset.entries]]
slot = 6
move = "MOVE_METAL_CLAW"
level = 25

[[learnset.entries]]
slot = 7
move = "MOVE_SLASH"
level = 30

[[learnset.entries]]
slot = 8
move = "MOVE_ASSURANCE"
level = 33

[[learnset.entries]]
slot = 9
move = "MOVE_METAL_SOUND"
level = 38

[[learnset.entries]]
slot = 10
move = "MOVE_EMBARGO"
level = 41

[[learnset.entries]]
slot = 11
move = "MOVE_IRON_DEFENSE"
level = 46

[[learnset.entries]]
slot = 12
move = "MOVE_NIGHT_SLASH"
level = 49

[[learnset.entries]]
slot = 13
move = "MOVE_IRON_HEAD"
level = 54

[[learnset.entries]]
slot = 14
move = "MOVE_SWORDS_DANCE"
level = 57

[[learnset.entries]]
slot = 15
move = "MOVE_GUILLOTINE"
level = 62
