[learnset]
index = 632
species = "SPECIES_DURANT"

[[learnset.entries]]
slot = 0
move = "MOVE_VICEGRIP"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_SANDATTACK"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_FURY_CUTTER"
level = 6

[[learnset.entries]]
slot = 3
move = "MOVE_BITE"
level = 11

[[learnset.entries]]
slot = 4
move = "MOVE_AGILITY"
level = 16

[[learnset.entries]]
slot = 5
move = "MOVE_METAL_CLAW"
level = 21

[[learnset.entries]]
slot = 6
move = "MOVE_BUG_BITE"
level = 26

[[learnset.entries]]
slot = 7
move = "MOVE_CRUNCH"
level = 31

[[learnset.entries]]
slot = 8
move = "MOVE_IRON_HEAD"
level = 36

[[learnset.entries]]
slot = 9
move = "MOVE_DIG"
level = 41

[[learnset.entries]]
slot = 10
move = "MOVE_ENTRAINMENT"
level = 46

[[learnset.entries]]
slot = 11
move = "MOVE_XSCISSOR"
level = 51

[[learnset.entries]]
slot = 12
move = "MOVE_IRON_DEFENSE"
level = 56

[[learnset.entries]]
slot = 13
move = "MOVE_GUILLOTINE"
level = 61

[[learnset.entries]]
slot = 14
move = "MOVE_METAL_SOUND"
level = 66
