[learnset]
index = 635
species = "SPECIES_HYDREIGON"

[[learnset.entries]]
slot = 0
move = "MOVE_TRI_ATTACK"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_DRAGON_RAGE"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_FOCUS_ENERGY"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_BITE"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_FOCUS_ENERGY"
level = 4

[[learnset.entries]]
slot = 5
move = "MOVE_BITE"
level = 9

[[learnset.entries]]
slot = 6
move = "MOVE_HEADBUTT"
level = 12

[[learnset.entries]]
slot = 7
move = "MOVE_DRAGONBREATH"
level = 17

[[learnset.entries]]
slot = 8
move = "MOVE_ROAR"
level = 20

[[learnset.entries]]
slot = 9
move = "MOVE_CRUNCH"
level = 25

[[learnset.entries]]
slot = 10
move = "MOVE_SLAM"
level = 28

[[learnset.entries]]
slot = 11
move = "MOVE_DRAGON_PULSE"
level = 32

[[learnset.entries]]
slot = 12
move = "MOVE_WORK_UP"
level = 38

[[learnset.entries]]
slot = 13
move = "MOVE_DRAGON_RUSH"
level = 42

[[learnset.entries]]
slot = 14
move = "MOVE_BODY_SLAM"
level = 48

[[learnset.entries]]
slot = 15
move = "MOVE_SCARY_FACE"
level = 55

[[learnset.entries]]
slot = 16
move = "MOVE_HYPER_VOICE"
level = 68

[[learnset.entries]]
slot = 17
move = "MOVE_OUTRAGE"
level = 79
