[learnset]
index = 636
species = "SPECIES_LARVESTA"

[[learnset.entries]]
slot = 0
move = "MOVE_EMBER"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_STRING_SHOT"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_LEECH_LIFE"
level = 10

[[learnset.entries]]
slot = 3
move = "MOVE_TAKE_DOWN"
level = 20

[[learnset.entries]]
slot = 4
move = "MOVE_FLAME_CHARGE"
level = 30

[[learnset.entries]]
slot = 5
move = "MOVE_BUG_BITE"
level = 40

[[learnset.entries]]
slot = 6
move = "MOVE_DOUBLEEDGE"
level = 50

[[learnset.entries]]
slot = 7
move = "MOVE_FLAME_WHEEL"
level = 60

[[learnset.entries]]
slot = 8
move = "MOVE_BUG_BUZZ"
level = 70

[[learnset.entries]]
slot = 9
move = "MOVE_AMNESIA"
level = 80

[[learnset.entries]]
slot = 10
move = "MOVE_THRASH"
level = 90

[[learnset.entries]]
slot = 11
move = "MOVE_FLARE_BLITZ"
level = 100
