[learnset]
index = 688
species = "SPECIES_BINACLE"

[[learnset.entries]]
slot = 0
move = "MOVE_TACKLE"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_PROTECT"
level = 10

[[learnset.entries]]
slot = 2
move = "MOVE_BUG_BITE"
level = 15

[[learnset.entries]]
slot = 3
move = "MOVE_HIDDEN_POWER"
level = 20

[[learnset.entries]]
slot = 4
move = "MOVE_CONFUSION"
level = 23

[[learnset.entries]]
slot = 5
move = "MOVE_ROCK_BLAST"
level = 26

[[learnset.entries]]
slot = 6
move = "MOVE_HARDEN"
level = 29

[[learnset.entries]]
slot = 7
move = "MOVE_PSYBEAM"
level = 32

[[learnset.entries]]
slot = 8
move = "MOVE_CAPTIVATE"
level = 35

[[learnset.entries]]
slot = 9
move = "MOVE_FLAIL"
level = 38

[[learnset.entries]]
slot = 10
move = "MOVE_ATTRACT"
level = 41

[[learnset.entries]]
slot = 11
move = "MOVE_PSYCHIC"
level = 44

[[learnset.entries]]
slot = 12
move = "MOVE_FISSURE"
level = 47
