[learnset]
index = 693
species = "SPECIES_CLAWITZER"

[[learnset.entries]]
slot = 0
move = "MOVE_TRICK"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_ASTONISH"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_THUNDER_WAVE"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_THUNDERSHOCK"
level = 1

[[learnset.entries]]
slot = 4
move = "MOVE_CONFUSE_RAY"
level = 1

[[learnset.entries]]
slot = 5
move = "MOVE_UPROAR"
level = 8

[[learnset.entries]]
slot = 6
move = "MOVE_DOUBLE_TEAM"
level = 15

[[learnset.entries]]
slot = 7
move = "MOVE_SHOCK_WAVE"
level = 22

[[learnset.entries]]
slot = 8
move = "MOVE_OMINOUS_WIND"
level = 29

[[learnset.entries]]
slot = 9
move = "MOVE_SUBSTITUTE"
level = 36

[[learnset.entries]]
slot = 10
move = "MOVE_ELECTRO_BALL"
level = 43

[[learnset.entries]]
slot = 11
move = "MOVE_HEX"
level = 50

[[learnset.entries]]
slot = 12
move = "MOVE_CHARGE"
level = 57

[[learnset.entries]]
slot = 13
move = "MOVE_DISCHARGE"
level = 64
