[learnset]
index = 703
species = "SPECIES_CARBINK"

[[learnset.entries]]
slot = 0
move = "MOVE_ICY_WIND"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_DRAGON_RAGE"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_IMPRISON"
level = 8

[[learnset.entries]]
slot = 3
move = "MOVE_ANCIENTPOWER"
level = 15

[[learnset.entries]]
slot = 4
move = "MOVE_ICE_BEAM"
level = 22

[[learnset.entries]]
slot = 5
move = "MOVE_DRAGONBREATH"
level = 29

[[learnset.entries]]
slot = 6
move = "MOVE_SLASH"
level = 36

[[learnset.entries]]
slot = 7
move = "MOVE_FUSION_FLARE"
level = 43

[[learnset.entries]]
slot = 8
move = "MOVE_ICE_BURN"
level = 50

[[learnset.entries]]
slot = 9
move = "MOVE_DRAGON_PULSE"
level = 57

[[learnset.entries]]
slot = 10
move = "MOVE_IMPRISON"
level = 64

[[learnset.entries]]
slot = 11
move = "MOVE_ENDEAVOR"
level = 71

[[learnset.entries]]
slot = 12
move = "MOVE_BLIZZARD"
level = 78

[[learnset.entries]]
slot = 13
move = "MOVE_OUTRAGE"
level = 85

[[learnset.entries]]
slot = 14
move = "MOVE_HYPER_VOICE"
level = 92
