[learnset]
index = 707
species = "SPECIES_KLEFKI"

[[learnset.entries]]
slot = 0
move = "MOVE_UPROAR"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_ASTONISH"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_THUNDERSHOCK"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_SWAGGER"
level = 7

[[learnset.entries]]
slot = 4
move = "MOVE_BITE"
level = 13

[[learnset.entries]]
slot = 5
move = "MOVE_REVENGE"
level = 19

[[learnset.entries]]
slot = 6
move = "MOVE_SHOCK_WAVE"
level = 25

[[learnset.entries]]
slot = 7
move = "MOVE_HEAL_BLOCK"
level = 31

[[learnset.entries]]
slot = 8
move = "MOVE_AGILITY"
level = 37

[[learnset.entries]]
slot = 9
move = "MOVE_DISCHARGE"
level = 43

[[learnset.entries]]
slot = 10
move = "MOVE_CRUNCH"
level = 49

[[learnset.entries]]
slot = 11
move = "MOVE_CHARGE"
level = 55

[[learnset.entries]]
slot = 12
move = "MOVE_NASTY_PLOT"
level = 61

[[learnset.entries]]
slot = 13
move = "MOVE_THUNDER"
level = 67

[[learnset.entries]]
slot = 14
move = "MOVE_DARK_PULSE"
level = 73

[[learnset.entries]]
slot = 15
move = "MOVE_HAMMER_ARM"
level = 79

[[learnset.entries]]
slot = 16
move = "MOVE_THRASH"
level = 85
