[learnset]
index = 708
species = "SPECIES_PHANTUMP"

[[learnset.entries]]
slot = 0
move = "MOVE_BLOCK"
level = 1

[[learnset.entries]]
slot = 1
move = "MOVE_MUD_SHOT"
level = 1

[[learnset.entries]]
slot = 2
move = "MOVE_ROCK_TOMB"
level = 1

[[learnset.entries]]
slot = 3
move = "MOVE_IMPRISON"
level = 7

[[learnset.entries]]
slot = 4
move = "MOVE_PUNISHMENT"
level = 13

[[learnset.entries]]
slot = 5
move = "MOVE_BULLDOZE"
level = 19

[[learnset.entries]]
slot = 6
move = "MOVE_ROCK_THROW"
level = 25

[[learnset.entries]]
slot = 7
move = "MOVE_EXTRASENSORY"
level = 31

[[learnset.entries]]
slot = 8
move = "MOVE_SWORDS_DANCE"
level = 37

[[learnset.entries]]
slot = 9
move = "MOVE_EARTH_POWER"
level = 43

[[learnset.entries]]
slot = 10
move = "MOVE_ROCK_SLIDE"
level = 49

[[learnset.entries]]
slot = 11
move = "MOVE_EARTHQUAKE"
level = 55

[[learnset.entries]]
slot = 12
move = "MOVE_SANDSTORM"
level = 61

[[learnset.entries]]
slot = 13
move = "MOVE_FISSURE"
level = 67

[[learnset.entries]]
slot = 14
move = "MOVE_STONE_EDGE"
level = 73

[[learnset.entries]]
slot = 15
move = "MOVE_HAMMER_ARM"
level = 79

[[learnset.entries]]
slot = 16
move = "MOVE_OUTRAGE"
level = 85
