learnsets = [
  '0.toml',
  '1.toml',
  '2.toml',
  '3.toml',
  '4.toml',
  '5.toml',
  '6.toml',
  '7.toml',
  '8.toml',
  '9.toml',
  '10.toml',
  '11.toml',
  '12.toml',
  '13.toml',
  '14.toml',
  '15.toml',
  '16.toml',
  '17.toml',
  '18.toml',
  '19.toml',
  '20.toml',
  '21.toml',
  '22.toml',
  '23.toml',
  '24.toml',
  '25.toml',
  '26.toml',
  '27.toml',
  '28.toml',
  '29.toml',
  '30.toml',
  '31.toml',
  '32.toml',
  '33.toml',
  '34.toml',
  '35.toml',
  '36.toml',
  '37.toml',
  '38.toml',
  '39.toml',
  '40.toml',
  '41.toml',
  '42.toml',
  '43.toml',
  '44.toml',
  '45.toml',
  '46.toml',
  '47.toml',
  '48.toml',
  '49.toml',
  '50.toml',
  '51.toml',
  '52.toml',
  '53.toml',
  '54.toml',
  '55.toml',
  '56.toml',
  '57.toml',
  '58.toml',
  '59.toml',
  '60.toml',
  '61.toml',
  '62.toml',
  '63.toml',
  '64.toml',
  '65.toml',
  '66.toml',
  '67.toml',
  '68.toml',
  '69.toml',
  '70.toml',
  '71.toml',
  '72.toml',
  '73.toml',
  '74.toml',
  '75.toml',
  '76.toml',
  '77.toml',
  '78.toml',
  '79.toml',
  '80.toml',
  '81.toml',
  '82.toml',
  '83.toml',
  '84.toml',
  '85.toml',
  '86.toml',
  '87.toml',
  '88.toml',
  '89.toml',
  '90.toml',
  '91.toml',
  '92.toml',
  '93.toml',
  '94.toml',
  '95.toml',
  '96.toml',
  '97.toml',
  '98.toml',
  '99.toml',
  '100.toml',
  '101.toml',
  '102.toml',
  '103.toml',
  '104.toml',
  '105.toml',
  '106.toml',
  '107.toml',
  '108.toml',
  '109.toml',
  '110.toml',
  '111.toml',
  '112.toml',
  '113.toml',
  '114.toml',
  '115.toml',
  '116.toml',
  '117.toml',
  '118.toml',
  '119.toml',
  '120.toml',
  '121.toml',
  '122.toml',
  '123.toml',
  '124.toml',
  '125.toml',
  '126.toml',
  '127.toml',
  '128.toml',
  '129.toml',
  '130.toml',
  '131.toml',
  '132.toml',
  '133.toml',
  '134.toml',
  '135.toml',
  '136.toml',
  '137.toml',
  '138.toml',
  '139.toml',
  '140.toml',
  '141.toml',
  '142.toml',
  '143.toml',
  '144.toml',
  '145.toml',
  '146.toml',
  '147.toml',
  '148.toml',
  '149.toml',
  '150.toml',
  '151.toml',
  '152.toml',
  '153.toml',
  '154.toml',
  '155.toml',
  '156.toml',
  '157.toml',
  '158.toml',
  '159.toml',
  '160.toml',
  '161.toml',
  '162.toml',
  '163.toml',
  '164.toml',
  '165.toml',
  '166.toml',
  '167.toml',
  '168.toml',
  '169.toml',
  '170.toml',
  '171.toml',
  '172.toml',
  '173.toml',
  '174.toml',
  '175.toml',
  '176.toml',
  '177.toml',
  '178.toml',
  '179.toml',
  '180.toml',
  '181.toml',
  '182.toml',
  '183.toml',
  '184.toml',
  '185.toml',
  '186.toml',
  '187.toml',
  '188.toml',
  '189.toml',
  '190.toml',
  '191.toml',
  '192.toml',
  '193.toml',
  '194.toml',
  '195.toml',
  '196.toml',
  '197.toml',
  '198.toml',
  '199.toml',
  '200.toml',
  '201.toml',
  '202.toml',
  '203.toml',
  '204.toml',
  '205.toml',
  '206.toml',
  '207.toml',
  '208.toml',
  '209.toml',
  '210.toml',
  '211.toml',
  '212.toml',
  '213.toml',
  '214.toml',
  '215.toml',
  '216.toml',
  '217.toml',
  '218.toml',
  '219.toml',
  '220.toml',
  '221.toml',
  '222.toml',
  '223.toml',
  '224.toml',
  '225.toml',
  '226.toml',
  '227.toml',
  '228.toml',
  '229.toml',
  '230.toml',
  '231.toml',
  '232.toml',
  '233.toml',
  '234.toml',
  '235.toml',
  '236.toml',
  '237.toml',
  '238.toml',
  '239.toml',
  '240.toml',
  '241.toml',
  '242.toml',
  '243.toml',
  '244.toml',
  '245.toml',
  '246.toml',
  '247.toml',
  '248.toml',
  '249.toml',
  '250.toml',
  '251.toml',
  '252.toml',
  '253.toml',
  '254.toml',
  '255.toml',
  '256.toml',
  '257.toml',
  '258.toml',
  '259.toml',
  '260.toml',
  '261.toml',
  '262.toml',
  '263.toml',
  '264.toml',
  '265.toml',
  '266.toml',
  '267.toml',
  '268.toml',
  '269.toml',
  '270.toml',
  '271.toml',
  '272.toml',
  '273.toml',
  '274.toml',
  '275.toml',
  '276.toml',
  '277.toml',
  '278.toml',
  '279.toml',
  '280.toml',
  '281.toml',
  '282.toml',
  '283.toml',
  '284.toml',
  '285.toml',
  '286.toml',
  '287.toml',
  '288.toml',
  '289.toml',
  '290.toml',
  '291.toml',
  '292.toml',
  '293.toml',
  '294.toml',
  '295.toml',
  '296.toml',
  '297.toml',
  '298.toml',
  '299.toml',
  '300.toml',
  '301.toml',
  '302.toml',
  '303.toml',
  '304.toml',
  '305.toml',
  '306.toml',
  '307.toml',
  '308.toml',
  '309.toml',
  '310.toml',
  '311.toml',
  '312.toml',
  '313.toml',
  '314.toml',
  '315.toml',
  '316.toml',
  '317.toml',
  '318.toml',
  '319.toml',
  '320.toml',
  '321.toml',
  '322.toml',
  '323.toml',
  '324.toml',
  '325.toml',
  '326.toml',
  '327.toml',
  '328.toml',
  '329.toml',
  '330.toml',
  '331.toml',
  '332.toml',
  '333.toml',
  '334.toml',
  '335.toml',
  '336.toml',
  '337.toml',
  '338.toml',
  '339.toml',
  '340.toml',
  '341.toml',
  '342.toml',
  '343.toml',
  '344.toml',
  '345.toml',
  '346.toml',
  '347.toml',
  '348.toml',
  '349.toml',
  '350.toml',
  '351.toml',
  '352.toml',
  '353.toml',
  '354.toml',
  '355.toml',
  '356.toml',
  '357.toml',
  '358.toml',
  '359.toml',
  '360.toml',
  '361.toml',
  '362.toml',
  '363.toml',
  '364.toml',
  '365.toml',
  '366.toml',
  '367.toml',
  '368.toml',
  '369.toml',
  '370.toml',
  '371.toml',
  '372.toml',
  '373.toml',
  '374.toml',
  '375.toml',
  '376.toml',
  '377.toml',
  '378.toml',
  '379.toml',
  '380.toml',
  '381.toml',
  '382.toml',
  '383.toml',
  '384.toml',
  '385.toml',
  '386.toml',
  '387.toml',
  '388.toml',
  '389.toml',
  '390.toml',
  '391.toml',
  '392.toml',
  '393.toml',
  '394.toml',
  '395.toml',
  '396.toml',
  '397.toml',
  '398.toml',
  '399.toml',
  '400.toml',
  '401.toml',
  '402.toml',
  '403.toml',
  '404.toml',
  '405.toml',
  '406.toml',
  '407.toml',
  '408.toml',
  '409.toml',
  '410.toml',
  '411.toml',
  '412.toml',
  '413.toml',
  '414.toml',
  '415.toml',
  '416.toml',
  '417.toml',
  '418.toml',
  '419.toml',
  '420.toml',
  '421.toml',
  '422.toml',
  '423.toml',
  '424.toml',
  '425.toml',
  '426.toml',
  '427.toml',
  '428.toml',
  '429.toml',
  '430.toml',
  '431.toml',
  '432.toml',
  '433.toml',
  '434.toml',
  '435.toml',
  '436.toml',
  '437.toml',
  '438.toml',
  '439.toml',
  '440.toml',
  '441.toml',
  '442.toml',
  '443.toml',
  '444.toml',
  '445.toml',
  '446.toml',
  '447.toml',
  '448.toml',
  '449.toml',
  '450.toml',
  '451.toml',
  '452.toml',
  '453.toml',
  '454.toml',
  '455.toml',
  '456.toml',
  '457.toml',
  '458.toml',
  '459.toml',
  '460.toml',
  '461.toml',
  '462.toml',
  '463.toml',
  '464.toml',
  '465.toml',
  '466.toml',
  '467.toml',
  '468.toml',
  '469.toml',
  '470.toml',
  '471.toml',
  '472.toml',
  '473.toml',
  '474.toml',
  '475.toml',
  '476.toml',
  '477.toml',
  '478.toml',
  '479.toml',
  '480.toml',
  '481.toml',
  '482.toml',
  '483.toml',
  '484.toml',
  '485.toml',
  '486.toml',
  '487.toml',
  '488.toml',
  '489.toml',
  '490.toml',
  '491.toml',
  '492.toml',
  '493.toml',
  '494.toml',
  '495.toml',
  '496.toml',
  '497.toml',
  '498.toml',
  '499.toml',
  '500.toml',
  '501.toml',
  '502.toml',
  '503.toml',
  '504.toml',
  '505.toml',
  '506.toml',
  '507.toml',
  '508.toml',
  '509.toml',
  '510.toml',
  '511.toml',
  '512.toml',
  '513.toml',
  '514.toml',
  '515.toml',
  '516.toml',
  '517.toml',
  '518.toml',
  '519.toml',
  '520.toml',
  '521.toml',
  '522.toml',
  '523.toml',
  '524.toml',
  '525.toml',
  '526.toml',
  '527.toml',
  '528.toml',
  '529.toml',
  '530.toml',
  '531.toml',
  '532.toml',
  '533.toml',
  '534.toml',
  '535.toml',
  '536.toml',
  '537.toml',
  '538.toml',
  '539.toml',
  '540.toml',
  '541.toml',
  '542.toml',
  '543.toml',
  '544.toml',
  '545.toml',
  '546.toml',
  '547.toml',
  '548.toml',
  '549.toml',
  '550.toml',
  '551.toml',
  '552.toml',
  '553.toml',
  '554.toml',
  '555.toml',
  '556.toml',
  '557.toml',
  '558.toml',
  '559.toml',
  '560.toml',
  '561.toml',
  '562.toml',
  '563.toml',
  '564.toml',
  '565.toml',
  '566.toml',
  '567.toml',
  '568.toml',
  '569.toml',
  '570.toml',
  '571.toml',
  '572.toml',
  '573.toml',
  '574.toml',
  '575.toml',
  '576.toml',
  '577.toml',
  '578.toml',
  '579.toml',
  '580.toml',
  '581.toml',
  '582.toml',
  '583.toml',
  '584.toml',
  '585.toml',
  '586.toml',
  '587.toml',
  '588.toml',
  '589.toml',
  '590.toml',
  '591.toml',
  '592.toml',
  '593.toml',
  '594.toml',
  '595.toml',
  '596.toml',
  '597.toml',
  '598.toml',
  '599.toml',
  '600.toml',
  '601.toml',
  '602.toml',
  '603.toml',
  '604.toml',
  '605.toml',
  '606.toml',
  '607.toml',
  '608.toml',
  '609.toml',
  '610.toml',
  '611.toml',
  '612.toml',
  '613.toml',
  '614.toml',
  '615.toml',
  '616.toml',
  '617.toml',
  '618.toml',
  '619.toml',
  '620.toml',
  '621.toml',
  '622.toml',
  '623.toml',
  '624.toml',
  '625.toml',
  '626.toml',
  '627.toml',
  '628.toml',
  '629.toml',
  '630.toml',
  '631.toml',
  '632.toml',
  '633.toml',
  '634.toml',
  '635.toml',
  '636.toml',
  '637.toml',
  '638.toml',
  '639.toml',
  '640.toml',
  '641.toml',
  '642.toml',
  '643.toml',
  '644.toml',
  '645.toml',
  '646.toml',
  '647.toml',
  '648.toml',
  '649.toml',
  '650.toml',
  '651.toml',
  '652.toml',
  '653.toml',
  '654.toml',
  '655.toml',
  '656.toml',
  '657.toml',
  '658.toml',
  '659.toml',
  '660.toml',
  '661.toml',
  '662.toml',
  '663.toml',
  '664.toml',
  '665.toml',
  '666.toml',
  '667.toml',
  '668.toml',
  '669.toml',
  '670.toml',
  '671.toml',
  '672.toml',
  '673.toml',
  '674.toml',
  '675.toml',
  '676.toml',
  '677.toml',
  '678.toml',
  '679.toml',
  '680.toml',
  '681.toml',
  '682.toml',
  '683.toml',
  '684.toml',
  '685.toml',
  '686.toml',
  '687.toml',
  '688.toml',
  '689.toml',
  '690.toml',
  '691.toml',
  '692.toml',
  '693.toml',
  '694.toml',
  '695.toml',
  '696.toml',
  '697.toml',
  '698.toml',
  '699.toml',
  '700.toml',
  '701.toml',
  '702.toml',
  '703.toml',
  '704.toml',
  '705.toml',
  '706.toml',
  '707.toml',
  '708.toml',
  '709.toml',
  '710.toml',
  '711.toml',
  '712.toml',
  '713.toml',
  '714.toml',
  '715.toml',
  '716.toml',
  '717.toml',
  '718.toml',
  '719.toml',
  '720.toml',
  '721.toml',
  '722.toml',
  '723.toml',
  '724.toml',
  '725.toml',
  '726.toml',
  '727.toml',
  '728.toml',
  '729.toml',
  '730.toml',
  '731.toml',
  '732.toml',
  '733.toml',
  '734.toml',
  '735.toml',
  '736.toml',
  '737.toml',
  '738.toml',
  '739.toml',
  '740.toml',
  '741.toml',
  '742.toml',
  '743.toml',
  '744.toml',
  '745.toml',
  '746.toml',
  '747.toml',
  '748.toml',
  '749.toml',
  '750.toml',
  '751.toml',
  '752.toml',
  '753.toml',
  '754.toml',
  '755.toml',
  '756.toml',
  '757.toml',
  '758.toml',
  '759.toml',
  '760.toml',
  '761.toml',
  '762.toml',
  '763.toml',
  '764.toml',
  '765.toml',
  '766.toml',
  '767.toml',
  '768.toml',
  '769.toml',
  '770.toml',
  '771.toml',
  '772.toml',
  '773.toml',
  '774.toml',
  '775.toml',
  '776.toml',
  '777.toml',
  '778.toml',
  '779.toml',
  '780.toml',
  '781.toml',
  '782.toml',
  '783.toml',
  '784.toml',
  '785.toml',
  '786.toml',
  '787.toml',
  '788.toml',
  '789.toml',
  '790.toml',
  '791.toml',
  '792.toml',
  '793.toml',
  '794.toml',
  '795.toml',
  '796.toml',
  '797.toml',
  '798.toml',
  '799.toml',
  '800.toml',
  '801.toml',
  '802.toml',
  '803.toml',
  '804.toml',
  '805.toml',
  '806.toml',
  '807.toml',
  '808.toml',
  '809.toml',
  '810.toml',
  '811.toml',
  '812.toml',
  '813.toml',
  '814.toml',
  '815.toml',
  '816.toml',
  '817.toml',
  '818.toml',
  '819.toml',
  '820.toml',
  '821.toml',
  '822.toml',
  '823.toml',
  '824.toml',
  '825.toml',
]

# Learnsets (/a/0/1/8)
learnsets_arc = 'a' / '0' / '1' / '8'
learnset_files = []
foreach learnset : learnsets
  learnset_name = fs.replace_suffix(learnset, '')
  learnset_files += custom_target(
    'learnset_' + learnset_name,
    input: meson.current_source_dir() / learnset,
    output: learnset_name,
    command: [mkdata_py, 'generic', '@INPUT@', meson.project_build_root() / '@OUTPUT@', 'format', 'learnsets'],
  )
endforeach

vfs_files += custom_target(
  'pack_learnsets_narc',
  input: learnset_files,
  output: 'pack_learnsets_narc.stamp',
  command: [pack_narc_py, '@OUTPUT@', meson.project_source_root() / 'vfs' / 'data' / learnsets_arc, '@INPUT@'],
)
