encounters = [
  '0.toml',
  '1.toml',
  '2.toml',
  '3.toml',
  '4.toml',
  '5.toml',
  '6.toml',
  '7.toml',
  '8.toml',
  '9.toml',
  '10.toml',
  '11.toml',
  '12.toml',
  '13.toml',
  '14.toml',
  '15.toml',
  '16.toml',
  '17.toml',
  '18.toml',
  '19.toml',
  '20.toml',
  '21.toml',
  '22.toml',
  '23.toml',
  '24.toml',
  '25.toml',
  '26.toml',
  '27.toml',
  '28.toml',
  '29.toml',
  '30.toml',
  '31.toml',
  '32.toml',
  '33.toml',
  '34.toml',
  '35.toml',
  '36.toml',
  '37.toml',
  '38.toml',
  '39.toml',
  '40.toml',
  '41.toml',
  '42.toml',
  '43.toml',
  '44.toml',
  '45.toml',
  '46.toml',
  '47.toml',
  '48.toml',
  '49.toml',
  '50.toml',
  '51.toml',
  '52.toml',
  '53.toml',
  '54.toml',
  '55.toml',
  '56.toml',
  '57.toml',
  '58.toml',
  '59.toml',
  '60.toml',
  '61.toml',
  '62.toml',
  '63.toml',
  '64.toml',
  '65.toml',
  '66.toml',
  '67.toml',
  '68.toml',
  '69.toml',
  '70.toml',
  '71.toml',
  '72.toml',
  '73.toml',
  '74.toml',
  '75.toml',
  '76.toml',
  '77.toml',
  '78.toml',
  '79.toml',
  '80.toml',
  '81.toml',
  '82.toml',
  '83.toml',
  '84.toml',
  '85.toml',
  '86.toml',
  '87.toml',
  '88.toml',
  '89.toml',
  '90.toml',
  '91.toml',
  '92.toml',
  '93.toml',
  '94.toml',
  '95.toml',
  '96.toml',
  '97.toml',
  '98.toml',
  '99.toml',
  '100.toml',
  '101.toml',
  '102.toml',
  '103.toml',
  '104.toml',
  '105.toml',
  '106.toml',
  '107.toml',
  '108.toml',
  '109.toml',
  '110.toml',
  '111.toml',
  '112.toml',
  '113.toml',
  '114.toml',
  '115.toml',
  '116.toml',
  '117.toml',
  '118.toml',
  '119.toml',
  '120.toml',
  '121.toml',
  '122.toml',
  '123.toml',
  '124.toml',
  '125.toml',
  '126.toml',
  '127.toml',
  '128.toml',
  '129.toml',
  '130.toml',
  '131.toml',
  '132.toml',
  '133.toml',
  '134.toml'
]

# Encounters (/a/1/2/7)
encounters_arc = 'a' / '1' / '2' / '7'
encounter_files = []
foreach encounter : encounters
  encounter_name = fs.replace_suffix(encounter, '')
  encounter_files += custom_target(
    'encounter_' + encounter_name,
    input: meson.current_source_dir() / encounter,
    output: encounter_name,
    command: [mkdata_py, 'encounter', '@INPUT@', meson.project_build_root() / '@OUTPUT@'],
  )
endforeach

vfs_files += custom_target(
  'pack_encounters_narc',
  input: encounter_files,
  output: 'pack_encounters_narc.stamp',
  command: [pack_narc_py, '@OUTPUT@', meson.project_source_root() / 'vfs' / 'data' / encounters_arc, '@INPUT@'],
)
