[encounter]
index = 6

[encounter.rates]
grass_singles = 1
grass_doubles = 3
grass_special = 1
surf_singles = 0
surf_special = 0
fish_singles = 0
fish_special = 0
unknown = 0

[[encounter.slots]]
category = "grass"
type = "singles"
slot = 0
chance = 20
species = "SPECIES_WATCHOG"
form = 0
minimum_level = 56
maximum_level = 56

[[encounter.slots]]
category = "grass"
type = "singles"
slot = 1
chance = 20
species = "SPECIES_LIEPARD"
form = 0
minimum_level = 56
maximum_level = 56

[[encounter.slots]]
category = "grass"
type = "singles"
slot = 2
chance = 10
species = "SPECIES_RATICATE"
form = 0
minimum_level = 57
maximum_level = 57

[[encounter.slots]]
category = "grass"
type = "singles"
slot = 3
chance = 10
species = "SPECIES_JIGGLYPUFF"
form = 0
minimum_level = 57
maximum_level = 57

[[encounter.slots]]
category = "grass"
type = "singles"
slot = 4
chance = 10
species = "SPECIES_MUNNA"
form = 0
minimum_level = 57
maximum_level = 57

[[encounter.slots]]
category = "grass"
type = "singles"
slot = 5
chance = 10
species = "SPECIES_MUNNA"
form = 0
minimum_level = 58
maximum_level = 58

[[encounter.slots]]
category = "grass"
type = "singles"
slot = 6
chance = 5
species = "SPECIES_GOLBAT"
form = 0
minimum_level = 57
maximum_level = 57

[[encounter.slots]]
category = "grass"
type = "singles"
slot = 7
chance = 5
species = "SPECIES_GOLBAT"
form = 0
minimum_level = 58
maximum_level = 58

[[encounter.slots]]
category = "grass"
type = "singles"
slot = 8
chance = 4
species = "SPECIES_WATCHOG"
form = 0
minimum_level = 59
maximum_level = 59

[[encounter.slots]]
category = "grass"
type = "singles"
slot = 9
chance = 4
species = "SPECIES_LIEPARD"
form = 0
minimum_level = 59
maximum_level = 59

[[encounter.slots]]
category = "grass"
type = "singles"
slot = 10
chance = 1
species = "SPECIES_WATCHOG"
form = 0
minimum_level = 59
maximum_level = 59

[[encounter.slots]]
category = "grass"
type = "singles"
slot = 11
chance = 1
species = "SPECIES_LIEPARD"
form = 0
minimum_level = 59
maximum_level = 59

[[encounter.slots]]
category = "grass"
type = "doubles"
slot = 0
chance = 20
species = "SPECIES_WATCHOG"
form = 0
minimum_level = 64
maximum_level = 64

[[encounter.slots]]
category = "grass"
type = "doubles"
slot = 1
chance = 20
species = "SPECIES_LIEPARD"
form = 0
minimum_level = 64
maximum_level = 64

[[encounter.slots]]
category = "grass"
type = "doubles"
slot = 2
chance = 10
species = "SPECIES_RATICATE"
form = 0
minimum_level = 65
maximum_level = 65

[[encounter.slots]]
category = "grass"
type = "doubles"
slot = 3
chance = 10
species = "SPECIES_JIGGLYPUFF"
form = 0
minimum_level = 65
maximum_level = 65

[[encounter.slots]]
category = "grass"
type = "doubles"
slot = 4
chance = 10
species = "SPECIES_MUNNA"
form = 0
minimum_level = 65
maximum_level = 65

[[encounter.slots]]
category = "grass"
type = "doubles"
slot = 5
chance = 10
species = "SPECIES_MUNNA"
form = 0
minimum_level = 66
maximum_level = 66

[[encounter.slots]]
category = "grass"
type = "doubles"
slot = 6
chance = 5
species = "SPECIES_GOLBAT"
form = 0
minimum_level = 65
maximum_level = 65

[[encounter.slots]]
category = "grass"
type = "doubles"
slot = 7
chance = 5
species = "SPECIES_GOLBAT"
form = 0
minimum_level = 66
maximum_level = 66

[[encounter.slots]]
category = "grass"
type = "doubles"
slot = 8
chance = 4
species = "SPECIES_WATCHOG"
form = 0
minimum_level = 67
maximum_level = 67

[[encounter.slots]]
category = "grass"
type = "doubles"
slot = 9
chance = 4
species = "SPECIES_LIEPARD"
form = 0
minimum_level = 67
maximum_level = 67

[[encounter.slots]]
category = "grass"
type = "doubles"
slot = 10
chance = 1
species = "SPECIES_WATCHOG"
form = 0
minimum_level = 67
maximum_level = 67

[[encounter.slots]]
category = "grass"
type = "doubles"
slot = 11
chance = 1
species = "SPECIES_LIEPARD"
form = 0
minimum_level = 67
maximum_level = 67

[[encounter.slots]]
category = "grass"
type = "special"
slot = 0
chance = 20
species = "SPECIES_AUDINO"
form = 0
minimum_level = 56
maximum_level = 56

[[encounter.slots]]
category = "grass"
type = "special"
slot = 1
chance = 20
species = "SPECIES_AUDINO"
form = 0
minimum_level = 56
maximum_level = 56

[[encounter.slots]]
category = "grass"
type = "special"
slot = 2
chance = 10
species = "SPECIES_AUDINO"
form = 0
minimum_level = 57
maximum_level = 57

[[encounter.slots]]
category = "grass"
type = "special"
slot = 3
chance = 10
species = "SPECIES_DUNSPARCE"
form = 0
minimum_level = 57
maximum_level = 57

[[encounter.slots]]
category = "grass"
type = "special"
slot = 4
chance = 10
species = "SPECIES_AUDINO"
form = 0
minimum_level = 58
maximum_level = 58

[[encounter.slots]]
category = "grass"
type = "special"
slot = 5
chance = 10
species = "SPECIES_AUDINO"
form = 0
minimum_level = 58
maximum_level = 58

[[encounter.slots]]
category = "grass"
type = "special"
slot = 6
chance = 5
species = "SPECIES_AUDINO"
form = 0
minimum_level = 59
maximum_level = 59

[[encounter.slots]]
category = "grass"
type = "special"
slot = 7
chance = 5
species = "SPECIES_WIGGLYTUFF"
form = 0
minimum_level = 59
maximum_level = 59

[[encounter.slots]]
category = "grass"
type = "special"
slot = 8
chance = 4
species = "SPECIES_CROBAT"
form = 0
minimum_level = 59
maximum_level = 59

[[encounter.slots]]
category = "grass"
type = "special"
slot = 9
chance = 4
species = "SPECIES_MUSHARNA"
form = 0
minimum_level = 59
maximum_level = 59

[[encounter.slots]]
category = "grass"
type = "special"
slot = 10
chance = 1
species = "SPECIES_CROBAT"
form = 0
minimum_level = 59
maximum_level = 59

[[encounter.slots]]
category = "grass"
type = "special"
slot = 11
chance = 1
species = "SPECIES_MUSHARNA"
form = 0
minimum_level = 59
maximum_level = 59

[[encounter.slots]]
category = "surf"
type = "singles"
slot = 0
chance = 60
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "surf"
type = "singles"
slot = 1
chance = 30
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "surf"
type = "singles"
slot = 2
chance = 5
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "surf"
type = "singles"
slot = 3
chance = 4
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "surf"
type = "singles"
slot = 4
chance = 1
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "surf"
type = "special"
slot = 0
chance = 60
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "surf"
type = "special"
slot = 1
chance = 30
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "surf"
type = "special"
slot = 2
chance = 5
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "surf"
type = "special"
slot = 3
chance = 4
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "surf"
type = "special"
slot = 4
chance = 1
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "fish"
type = "singles"
slot = 0
chance = 60
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "fish"
type = "singles"
slot = 1
chance = 30
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "fish"
type = "singles"
slot = 2
chance = 5
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "fish"
type = "singles"
slot = 3
chance = 4
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "fish"
type = "singles"
slot = 4
chance = 1
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "fish"
type = "special"
slot = 0
chance = 60
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "fish"
type = "special"
slot = 1
chance = 30
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "fish"
type = "special"
slot = 2
chance = 5
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "fish"
type = "special"
slot = 3
chance = 4
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "fish"
type = "special"
slot = 4
chance = 1
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0
