[encounter]
index = 59

[encounter.rates]
grass_singles = 7
grass_doubles = 0
grass_special = 1
surf_singles = 0
surf_special = 0
fish_singles = 0
fish_special = 0
unknown = 1

[[encounter.slots]]
category = "grass"
type = "singles"
slot = 0
chance = 20
species = "SPECIES_NUMEL"
form = 0
minimum_level = 31
maximum_level = 31

[[encounter.slots]]
category = "grass"
type = "singles"
slot = 1
chance = 20
species = "SPECIES_WOOBAT"
form = 0
minimum_level = 32
maximum_level = 32

[[encounter.slots]]
category = "grass"
type = "singles"
slot = 2
chance = 10
species = "SPECIES_BOLDORE"
form = 0
minimum_level = 32
maximum_level = 32

[[encounter.slots]]
category = "grass"
type = "singles"
slot = 3
chance = 10
species = "SPECIES_SKORUPI"
form = 0
minimum_level = 33
maximum_level = 33

[[encounter.slots]]
category = "grass"
type = "singles"
slot = 4
chance = 10
species = "SPECIES_BOLDORE"
form = 0
minimum_level = 34
maximum_level = 34

[[encounter.slots]]
category = "grass"
type = "singles"
slot = 5
chance = 10
species = "SPECIES_WOOBAT"
form = 0
minimum_level = 34
maximum_level = 34

[[encounter.slots]]
category = "grass"
type = "singles"
slot = 6
chance = 5
species = "SPECIES_CAMERUPT"
form = 0
minimum_level = 35
maximum_level = 35

[[encounter.slots]]
category = "grass"
type = "singles"
slot = 7
chance = 5
species = "SPECIES_SKORUPI"
form = 0
minimum_level = 35
maximum_level = 35

[[encounter.slots]]
category = "grass"
type = "singles"
slot = 8
chance = 4
species = "SPECIES_WOOBAT"
form = 0
minimum_level = 35
maximum_level = 35

[[encounter.slots]]
category = "grass"
type = "singles"
slot = 9
chance = 4
species = "SPECIES_BOLDORE"
form = 0
minimum_level = 35
maximum_level = 35

[[encounter.slots]]
category = "grass"
type = "singles"
slot = 10
chance = 1
species = "SPECIES_WOOBAT"
form = 0
minimum_level = 35
maximum_level = 35

[[encounter.slots]]
category = "grass"
type = "singles"
slot = 11
chance = 1
species = "SPECIES_BOLDORE"
form = 0
minimum_level = 35
maximum_level = 35

[[encounter.slots]]
category = "grass"
type = "doubles"
slot = 0
chance = 20
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "grass"
type = "doubles"
slot = 1
chance = 20
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "grass"
type = "doubles"
slot = 2
chance = 10
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "grass"
type = "doubles"
slot = 3
chance = 10
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "grass"
type = "doubles"
slot = 4
chance = 10
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "grass"
type = "doubles"
slot = 5
chance = 10
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "grass"
type = "doubles"
slot = 6
chance = 5
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "grass"
type = "doubles"
slot = 7
chance = 5
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "grass"
type = "doubles"
slot = 8
chance = 4
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "grass"
type = "doubles"
slot = 9
chance = 4
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "grass"
type = "doubles"
slot = 10
chance = 1
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "grass"
type = "doubles"
slot = 11
chance = 1
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "grass"
type = "special"
slot = 0
chance = 20
species = "SPECIES_EXCADRILL"
form = 0
minimum_level = 32
maximum_level = 32

[[encounter.slots]]
category = "grass"
type = "special"
slot = 1
chance = 20
species = "SPECIES_EXCADRILL"
form = 0
minimum_level = 32
maximum_level = 32

[[encounter.slots]]
category = "grass"
type = "special"
slot = 2
chance = 10
species = "SPECIES_EXCADRILL"
form = 0
minimum_level = 33
maximum_level = 33

[[encounter.slots]]
category = "grass"
type = "special"
slot = 3
chance = 10
species = "SPECIES_EXCADRILL"
form = 0
minimum_level = 33
maximum_level = 33

[[encounter.slots]]
category = "grass"
type = "special"
slot = 4
chance = 10
species = "SPECIES_EXCADRILL"
form = 0
minimum_level = 34
maximum_level = 34

[[encounter.slots]]
category = "grass"
type = "special"
slot = 5
chance = 10
species = "SPECIES_EXCADRILL"
form = 0
minimum_level = 34
maximum_level = 34

[[encounter.slots]]
category = "grass"
type = "special"
slot = 6
chance = 5
species = "SPECIES_EXCADRILL"
form = 0
minimum_level = 35
maximum_level = 35

[[encounter.slots]]
category = "grass"
type = "special"
slot = 7
chance = 5
species = "SPECIES_EXCADRILL"
form = 0
minimum_level = 35
maximum_level = 35

[[encounter.slots]]
category = "grass"
type = "special"
slot = 8
chance = 4
species = "SPECIES_EXCADRILL"
form = 0
minimum_level = 35
maximum_level = 35

[[encounter.slots]]
category = "grass"
type = "special"
slot = 9
chance = 4
species = "SPECIES_EXCADRILL"
form = 0
minimum_level = 35
maximum_level = 35

[[encounter.slots]]
category = "grass"
type = "special"
slot = 10
chance = 1
species = "SPECIES_EXCADRILL"
form = 0
minimum_level = 35
maximum_level = 35

[[encounter.slots]]
category = "grass"
type = "special"
slot = 11
chance = 1
species = "SPECIES_EXCADRILL"
form = 0
minimum_level = 35
maximum_level = 35

[[encounter.slots]]
category = "surf"
type = "singles"
slot = 0
chance = 60
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "surf"
type = "singles"
slot = 1
chance = 30
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "surf"
type = "singles"
slot = 2
chance = 5
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "surf"
type = "singles"
slot = 3
chance = 4
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "surf"
type = "singles"
slot = 4
chance = 1
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "surf"
type = "special"
slot = 0
chance = 60
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "surf"
type = "special"
slot = 1
chance = 30
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "surf"
type = "special"
slot = 2
chance = 5
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "surf"
type = "special"
slot = 3
chance = 4
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "surf"
type = "special"
slot = 4
chance = 1
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "fish"
type = "singles"
slot = 0
chance = 60
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "fish"
type = "singles"
slot = 1
chance = 30
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "fish"
type = "singles"
slot = 2
chance = 5
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "fish"
type = "singles"
slot = 3
chance = 4
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "fish"
type = "singles"
slot = 4
chance = 1
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "fish"
type = "special"
slot = 0
chance = 60
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "fish"
type = "special"
slot = 1
chance = 30
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "fish"
type = "special"
slot = 2
chance = 5
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "fish"
type = "special"
slot = 3
chance = 4
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "fish"
type = "special"
slot = 4
chance = 1
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0
