[encounter]
index = 71

[encounter.rates]
grass_singles = 7
grass_doubles = 0
grass_special = 0
surf_singles = 10
surf_special = 1
fish_singles = 50
fish_special = 1
unknown = 0

[[encounter.slots]]
category = "grass"
type = "singles"
slot = 0
chance = 20
species = "SPECIES_BANETTE"
form = 0
minimum_level = 47
maximum_level = 47

[[encounter.slots]]
category = "grass"
type = "singles"
slot = 1
chance = 20
species = "SPECIES_BANETTE"
form = 0
minimum_level = 47
maximum_level = 47

[[encounter.slots]]
category = "grass"
type = "singles"
slot = 2
chance = 10
species = "SPECIES_BANETTE"
form = 0
minimum_level = 48
maximum_level = 48

[[encounter.slots]]
category = "grass"
type = "singles"
slot = 3
chance = 10
species = "SPECIES_GOLURK"
form = 0
minimum_level = 48
maximum_level = 48

[[encounter.slots]]
category = "grass"
type = "singles"
slot = 4
chance = 10
species = "SPECIES_BANETTE"
form = 0
minimum_level = 49
maximum_level = 49

[[encounter.slots]]
category = "grass"
type = "singles"
slot = 5
chance = 10
species = "SPECIES_GOLURK"
form = 0
minimum_level = 49
maximum_level = 49

[[encounter.slots]]
category = "grass"
type = "singles"
slot = 6
chance = 5
species = "SPECIES_BANETTE"
form = 0
minimum_level = 50
maximum_level = 50

[[encounter.slots]]
category = "grass"
type = "singles"
slot = 7
chance = 5
species = "SPECIES_GOLURK"
form = 0
minimum_level = 50
maximum_level = 50

[[encounter.slots]]
category = "grass"
type = "singles"
slot = 8
chance = 4
species = "SPECIES_BANETTE"
form = 0
minimum_level = 50
maximum_level = 50

[[encounter.slots]]
category = "grass"
type = "singles"
slot = 9
chance = 4
species = "SPECIES_GOLURK"
form = 0
minimum_level = 50
maximum_level = 50

[[encounter.slots]]
category = "grass"
type = "singles"
slot = 10
chance = 1
species = "SPECIES_BANETTE"
form = 0
minimum_level = 50
maximum_level = 50

[[encounter.slots]]
category = "grass"
type = "singles"
slot = 11
chance = 1
species = "SPECIES_GOLURK"
form = 0
minimum_level = 50
maximum_level = 50

[[encounter.slots]]
category = "grass"
type = "doubles"
slot = 0
chance = 20
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "grass"
type = "doubles"
slot = 1
chance = 20
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "grass"
type = "doubles"
slot = 2
chance = 10
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "grass"
type = "doubles"
slot = 3
chance = 10
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "grass"
type = "doubles"
slot = 4
chance = 10
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "grass"
type = "doubles"
slot = 5
chance = 10
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "grass"
type = "doubles"
slot = 6
chance = 5
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "grass"
type = "doubles"
slot = 7
chance = 5
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "grass"
type = "doubles"
slot = 8
chance = 4
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "grass"
type = "doubles"
slot = 9
chance = 4
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "grass"
type = "doubles"
slot = 10
chance = 1
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "grass"
type = "doubles"
slot = 11
chance = 1
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "grass"
type = "special"
slot = 0
chance = 20
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "grass"
type = "special"
slot = 1
chance = 20
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "grass"
type = "special"
slot = 2
chance = 10
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "grass"
type = "special"
slot = 3
chance = 10
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "grass"
type = "special"
slot = 4
chance = 10
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "grass"
type = "special"
slot = 5
chance = 10
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "grass"
type = "special"
slot = 6
chance = 5
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "grass"
type = "special"
slot = 7
chance = 5
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "grass"
type = "special"
slot = 8
chance = 4
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "grass"
type = "special"
slot = 9
chance = 4
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "grass"
type = "special"
slot = 10
chance = 1
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "grass"
type = "special"
slot = 11
chance = 1
species = "SPECIES_NONE"
form = 0
minimum_level = 0
maximum_level = 0

[[encounter.slots]]
category = "surf"
type = "singles"
slot = 0
chance = 60
species = "SPECIES_BASCULIN"
form = 1
minimum_level = 35
maximum_level = 50

[[encounter.slots]]
category = "surf"
type = "singles"
slot = 1
chance = 30
species = "SPECIES_MARILL"
form = 0
minimum_level = 35
maximum_level = 50

[[encounter.slots]]
category = "surf"
type = "singles"
slot = 2
chance = 5
species = "SPECIES_BASCULIN"
form = 1
minimum_level = 40
maximum_level = 50

[[encounter.slots]]
category = "surf"
type = "singles"
slot = 3
chance = 4
species = "SPECIES_BASCULIN"
form = 1
minimum_level = 40
maximum_level = 50

[[encounter.slots]]
category = "surf"
type = "singles"
slot = 4
chance = 1
species = "SPECIES_BASCULIN"
form = 1
minimum_level = 40
maximum_level = 50

[[encounter.slots]]
category = "surf"
type = "special"
slot = 0
chance = 60
species = "SPECIES_MARILL"
form = 0
minimum_level = 35
maximum_level = 50

[[encounter.slots]]
category = "surf"
type = "special"
slot = 1
chance = 30
species = "SPECIES_BASCULIN"
form = 0
minimum_level = 35
maximum_level = 50

[[encounter.slots]]
category = "surf"
type = "special"
slot = 2
chance = 5
species = "SPECIES_BASCULIN"
form = 0
minimum_level = 40
maximum_level = 50

[[encounter.slots]]
category = "surf"
type = "special"
slot = 3
chance = 4
species = "SPECIES_AZUMARILL"
form = 0
minimum_level = 40
maximum_level = 50

[[encounter.slots]]
category = "surf"
type = "special"
slot = 4
chance = 1
species = "SPECIES_AZUMARILL"
form = 0
minimum_level = 40
maximum_level = 50

[[encounter.slots]]
category = "fish"
type = "singles"
slot = 0
chance = 60
species = "SPECIES_POLIWAG"
form = 0
minimum_level = 40
maximum_level = 55

[[encounter.slots]]
category = "fish"
type = "singles"
slot = 1
chance = 30
species = "SPECIES_BASCULIN"
form = 1
minimum_level = 40
maximum_level = 55

[[encounter.slots]]
category = "fish"
type = "singles"
slot = 2
chance = 5
species = "SPECIES_POLIWAG"
form = 0
minimum_level = 50
maximum_level = 55

[[encounter.slots]]
category = "fish"
type = "singles"
slot = 3
chance = 4
species = "SPECIES_POLIWAG"
form = 0
minimum_level = 50
maximum_level = 55

[[encounter.slots]]
category = "fish"
type = "singles"
slot = 4
chance = 1
species = "SPECIES_POLIWAG"
form = 0
minimum_level = 50
maximum_level = 55

[[encounter.slots]]
category = "fish"
type = "special"
slot = 0
chance = 60
species = "SPECIES_POLIWHIRL"
form = 0
minimum_level = 40
maximum_level = 60

[[encounter.slots]]
category = "fish"
type = "special"
slot = 1
chance = 30
species = "SPECIES_BASCULIN"
form = 0
minimum_level = 40
maximum_level = 60

[[encounter.slots]]
category = "fish"
type = "special"
slot = 2
chance = 5
species = "SPECIES_POLIWHIRL"
form = 0
minimum_level = 50
maximum_level = 60

[[encounter.slots]]
category = "fish"
type = "special"
slot = 3
chance = 4
species = "SPECIES_POLIWRATH"
form = 0
minimum_level = 50
maximum_level = 60

[[encounter.slots]]
category = "fish"
type = "special"
slot = 4
chance = 1
species = "SPECIES_POLIWRATH"
form = 0
minimum_level = 50
maximum_level = 60
