trainers = [
  '0.yml', '1.yml', '2.yml', '3.yml', '4.yml', '5.yml', '6.yml', '7.yml', '8.yml', '9.yml',
  '10.yml', '11.yml', '12.yml', '13.yml', '14.yml', '15.yml', '16.yml', '17.yml', '18.yml', '19.yml',
  '20.yml', '21.yml', '22.yml', '23.yml', '24.yml', '25.yml', '26.yml', '27.yml', '28.yml', '29.yml',
  '30.yml', '31.yml', '32.yml', '33.yml', '34.yml', '35.yml', '36.yml', '37.yml', '38.yml', '39.yml',
  '40.yml', '41.yml', '42.yml', '43.yml', '44.yml', '45.yml', '46.yml', '47.yml', '48.yml', '49.yml',
  '50.yml', '51.yml', '52.yml', '53.yml', '54.yml', '55.yml', '56.yml', '57.yml', '58.yml', '59.yml',
  '60.yml', '61.yml', '62.yml', '63.yml', '64.yml', '65.yml', '66.yml', '67.yml', '68.yml', '69.yml',
  '70.yml', '71.yml', '72.yml', '73.yml', '74.yml', '75.yml', '76.yml', '77.yml', '78.yml', '79.yml',
  '80.yml', '81.yml', '82.yml', '83.yml', '84.yml', '85.yml', '86.yml', '87.yml', '88.yml', '89.yml',
  '90.yml', '91.yml', '92.yml', '93.yml', '94.yml', '95.yml', '96.yml', '97.yml', '98.yml', '99.yml',
  '100.yml', '101.yml', '102.yml', '103.yml', '104.yml', '105.yml', '106.yml', '107.yml', '108.yml', '109.yml',
  '110.yml', '111.yml', '112.yml', '113.yml', '114.yml', '115.yml', '116.yml', '117.yml', '118.yml', '119.yml',
  '120.yml', '121.yml', '122.yml', '123.yml', '124.yml', '125.yml', '126.yml', '127.yml', '128.yml', '129.yml',
  '130.yml', '131.yml', '132.yml', '133.yml', '134.yml', '135.yml', '136.yml', '137.yml', '138.yml', '139.yml',
  '140.yml', '141.yml', '142.yml', '143.yml', '144.yml', '145.yml', '146.yml', '147.yml', '148.yml', '149.yml',
  '150.yml', '151.yml', '152.yml', '153.yml', '154.yml', '155.yml', '156.yml', '157.yml', '158.yml', '159.yml',
  '160.yml', '161.yml', '162.yml', '163.yml', '164.yml', '165.yml', '166.yml', '167.yml', '168.yml', '169.yml',
  '170.yml', '171.yml', '172.yml', '173.yml', '174.yml', '175.yml', '176.yml', '177.yml', '178.yml', '179.yml',
  '180.yml', '181.yml', '182.yml', '183.yml', '184.yml', '185.yml', '186.yml', '187.yml', '188.yml', '189.yml',
  '190.yml', '191.yml', '192.yml', '193.yml', '194.yml', '195.yml', '196.yml', '197.yml', '198.yml', '199.yml',
  '200.yml', '201.yml', '202.yml', '203.yml', '204.yml', '205.yml', '206.yml', '207.yml', '208.yml', '209.yml',
  '210.yml', '211.yml', '212.yml', '213.yml', '214.yml', '215.yml', '216.yml', '217.yml', '218.yml', '219.yml',
  '220.yml', '221.yml', '222.yml', '223.yml', '224.yml', '225.yml', '226.yml', '227.yml', '228.yml', '229.yml',
  '230.yml', '231.yml', '232.yml', '233.yml', '234.yml', '235.yml', '236.yml', '237.yml', '238.yml', '239.yml',
  '240.yml', '241.yml', '242.yml', '243.yml', '244.yml', '245.yml', '246.yml', '247.yml', '248.yml', '249.yml',
  '250.yml', '251.yml', '252.yml', '253.yml', '254.yml', '255.yml', '256.yml', '257.yml', '258.yml', '259.yml',
  '260.yml', '261.yml', '262.yml', '263.yml', '264.yml', '265.yml', '266.yml', '267.yml', '268.yml', '269.yml',
  '270.yml', '271.yml', '272.yml', '273.yml', '274.yml', '275.yml', '276.yml', '277.yml', '278.yml', '279.yml',
  '280.yml', '281.yml', '282.yml', '283.yml', '284.yml', '285.yml', '286.yml', '287.yml', '288.yml', '289.yml',
  '290.yml', '291.yml', '292.yml', '293.yml', '294.yml', '295.yml', '296.yml', '297.yml', '298.yml', '299.yml',
  '300.yml', '301.yml', '302.yml', '303.yml', '304.yml', '305.yml', '306.yml', '307.yml', '308.yml', '309.yml',
  '310.yml', '311.yml', '312.yml', '313.yml', '314.yml', '315.yml', '316.yml', '317.yml', '318.yml', '319.yml',
  '320.yml', '321.yml', '322.yml', '323.yml', '324.yml', '325.yml', '326.yml', '327.yml', '328.yml', '329.yml',
  '330.yml', '331.yml', '332.yml', '333.yml', '334.yml', '335.yml', '336.yml', '337.yml', '338.yml', '339.yml',
  '340.yml', '341.yml', '342.yml', '343.yml', '344.yml', '345.yml', '346.yml', '347.yml', '348.yml', '349.yml',
  '350.yml', '351.yml', '352.yml', '353.yml', '354.yml', '355.yml', '356.yml', '357.yml', '358.yml', '359.yml',
  '360.yml', '361.yml', '362.yml', '363.yml', '364.yml', '365.yml', '366.yml', '367.yml', '368.yml', '369.yml',
  '370.yml', '371.yml', '372.yml', '373.yml', '374.yml', '375.yml', '376.yml', '377.yml', '378.yml', '379.yml',
  '380.yml', '381.yml', '382.yml', '383.yml', '384.yml', '385.yml', '386.yml', '387.yml', '388.yml', '389.yml',
  '390.yml', '391.yml', '392.yml', '393.yml', '394.yml', '395.yml', '396.yml', '397.yml', '398.yml', '399.yml',
  '400.yml', '401.yml', '402.yml', '403.yml', '404.yml', '405.yml', '406.yml', '407.yml', '408.yml', '409.yml',
  '410.yml', '411.yml', '412.yml', '413.yml', '414.yml', '415.yml', '416.yml', '417.yml', '418.yml', '419.yml',
  '420.yml', '421.yml', '422.yml', '423.yml', '424.yml', '425.yml', '426.yml', '427.yml', '428.yml', '429.yml',
  '430.yml', '431.yml', '432.yml', '433.yml', '434.yml', '435.yml', '436.yml', '437.yml', '438.yml', '439.yml',
  '440.yml', '441.yml', '442.yml', '443.yml', '444.yml', '445.yml', '446.yml', '447.yml', '448.yml', '449.yml',
  '450.yml', '451.yml', '452.yml', '453.yml', '454.yml', '455.yml', '456.yml', '457.yml', '458.yml', '459.yml',
  '460.yml', '461.yml', '462.yml', '463.yml', '464.yml', '465.yml', '466.yml', '467.yml', '468.yml', '469.yml',
  '470.yml', '471.yml', '472.yml', '473.yml', '474.yml', '475.yml', '476.yml', '477.yml', '478.yml', '479.yml',
  '480.yml', '481.yml', '482.yml', '483.yml', '484.yml', '485.yml', '486.yml', '487.yml', '488.yml', '489.yml',
  '490.yml', '491.yml', '492.yml', '493.yml', '494.yml', '495.yml', '496.yml', '497.yml', '498.yml', '499.yml',
  '500.yml', '501.yml', '502.yml', '503.yml', '504.yml', '505.yml', '506.yml', '507.yml', '508.yml', '509.yml',
  '510.yml', '511.yml', '512.yml', '513.yml', '514.yml', '515.yml', '516.yml', '517.yml', '518.yml', '519.yml',
  '520.yml', '521.yml', '522.yml', '523.yml', '524.yml', '525.yml', '526.yml', '527.yml', '528.yml', '529.yml',
  '530.yml', '531.yml', '532.yml', '533.yml', '534.yml', '535.yml', '536.yml', '537.yml', '538.yml', '539.yml',
  '540.yml', '541.yml', '542.yml', '543.yml', '544.yml', '545.yml', '546.yml', '547.yml', '548.yml', '549.yml',
  '550.yml', '551.yml', '552.yml', '553.yml', '554.yml', '555.yml', '556.yml', '557.yml', '558.yml', '559.yml',
  '560.yml', '561.yml', '562.yml', '563.yml', '564.yml', '565.yml', '566.yml', '567.yml', '568.yml', '569.yml',
  '570.yml', '571.yml', '572.yml', '573.yml', '574.yml', '575.yml', '576.yml', '577.yml', '578.yml', '579.yml',
  '580.yml', '581.yml', '582.yml', '583.yml', '584.yml', '585.yml', '586.yml', '587.yml', '588.yml', '589.yml',
  '590.yml', '591.yml', '592.yml', '593.yml', '594.yml', '595.yml', '596.yml', '597.yml', '598.yml', '599.yml',
  '600.yml', '601.yml', '602.yml', '603.yml', '604.yml', '605.yml', '606.yml', '607.yml', '608.yml', '609.yml',
  '610.yml', '611.yml', '612.yml', '613.yml', '614.yml', '615.yml', '616.yml', '617.yml', '618.yml', '619.yml',
  '620.yml', '621.yml', '622.yml', '623.yml', '624.yml', '625.yml', '626.yml', '627.yml', '628.yml', '629.yml',
  '630.yml', '631.yml', '632.yml', '633.yml', '634.yml', '635.yml', '636.yml', '637.yml', '638.yml', '639.yml',
  '640.yml', '641.yml', '642.yml', '643.yml', '644.yml', '645.yml', '646.yml', '647.yml', '648.yml', '649.yml',
  '650.yml', '651.yml', '652.yml', '653.yml', '654.yml', '655.yml', '656.yml', '657.yml', '658.yml', '659.yml',
  '660.yml', '661.yml', '662.yml', '663.yml', '664.yml', '665.yml', '666.yml', '667.yml', '668.yml', '669.yml',
  '670.yml', '671.yml', '672.yml', '673.yml', '674.yml', '675.yml', '676.yml', '677.yml', '678.yml', '679.yml',
  '680.yml', '681.yml', '682.yml', '683.yml', '684.yml', '685.yml', '686.yml', '687.yml', '688.yml', '689.yml',
  '690.yml', '691.yml', '692.yml', '693.yml', '694.yml', '695.yml', '696.yml', '697.yml', '698.yml', '699.yml',
  '700.yml', '701.yml', '702.yml', '703.yml', '704.yml', '705.yml', '706.yml', '707.yml', '708.yml', '709.yml',
  '710.yml', '711.yml', '712.yml', '713.yml', '714.yml', '715.yml', '716.yml', '717.yml', '718.yml', '719.yml',
  '720.yml', '721.yml', '722.yml', '723.yml', '724.yml', '725.yml', '726.yml', '727.yml', '728.yml', '729.yml',
  '730.yml', '731.yml', '732.yml', '733.yml', '734.yml', '735.yml', '736.yml', '737.yml', '738.yml', '739.yml',
  '740.yml', '741.yml', '742.yml', '743.yml', '744.yml', '745.yml', '746.yml', '747.yml', '748.yml', '749.yml',
  '750.yml', '751.yml', '752.yml', '753.yml', '754.yml', '755.yml', '756.yml', '757.yml', '758.yml', '759.yml',
  '760.yml', '761.yml', '762.yml', '763.yml', '764.yml', '765.yml', '766.yml', '767.yml', '768.yml', '769.yml',
  '770.yml', '771.yml', '772.yml', '773.yml', '774.yml', '775.yml', '776.yml', '777.yml', '778.yml', '779.yml',
  '780.yml', '781.yml', '782.yml', '783.yml', '784.yml', '785.yml', '786.yml', '787.yml', '788.yml', '789.yml',
  '790.yml', '791.yml', '792.yml', '793.yml', '794.yml', '795.yml', '796.yml', '797.yml', '798.yml', '799.yml',
  '800.yml', '801.yml', '802.yml', '803.yml', '804.yml', '805.yml', '806.yml', '807.yml', '808.yml', '809.yml',
  '810.yml', '811.yml', '812.yml', '813.yml'
]

trdata_files = []
trpoke_files = []

# Build trdata.
foreach trainer : trainers
  tr_name = fs.replace_suffix(trainer, '')
  trdata_files += custom_target(
    'trdata_' + tr_name,
    input: trainer,
    output: 'trdata_' + tr_name,
    command: [python, 'tools/mkdata/mkdata.py', '-t', 'trdata', '-i', '@INPUT@', '-o', '@OUTPUT@'],
    install_dir : 'vfs/data/a/0/9/1'
  )
endforeach

# Build trpoke.
foreach trainer : trainers
  tr_name = fs.replace_suffix(trainer, '')
  trpoke_files += custom_target(
    'trpoke_' + tr_name,
    input: trainer,
    output: 'trpoke_' + tr_name,
    command: [python, 'tools/mkdata/mkdata.py', '-t', 'trpoke', '-i', '@INPUT@', '-o', '@OUTPUT@'],
    install_dir : 'vfs/data/a/0/9/2'
  )
endforeach