[trainer]
index = 0
party_format = 0
trainer_class = 0
battle_type = 0
party_count = 0
items = []
ai = 0
can_heal = 0
reward_money = 0
reward_item = 0
raw_size = 16

[trainer_party]
index = 0
party = []
