[trainer]
index = 20
party_format = 0
trainer_class = 67
battle_type = 0
party_count = 2
items = ["ITEM_NONE", "ITEM_NONE", "ITEM_NONE", "ITEM_NONE"]
ai = 5
can_heal = 0
reward_money = 20
reward_item = "ITEM_ULTRA_BALL"
raw_size = 20

[trainer_party]
index = 20

[[trainer_party.party]]
slot = 0
difficulty_value = 50
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 62
species = "SPECIES_PERSIAN"
form = 0

[[trainer_party.party]]
slot = 1
difficulty_value = 50
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 62
species = "SPECIES_HONCHKROW"
form = 0
