[trainer]
index = 47
party_format = 0
trainer_class = 3
battle_type = 0
party_count = 1
items = ["ITEM_NONE", "ITEM_NONE", "ITEM_NONE", "ITEM_NONE"]
ai = 0
can_heal = 0
reward_money = 4
reward_item = "ITEM_NONE"
raw_size = 20

[trainer_party]
index = 47

[[trainer_party.party]]
slot = 0
difficulty_value = 0
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 24
species = "SPECIES_LIEPARD"
form = 0
