[trainer]
index = 52
party_format = 0
trainer_class = 6
battle_type = 0
party_count = 2
items = ["ITEM_NONE", "ITEM_NONE", "ITEM_NONE", "ITEM_NONE"]
ai = 7
can_heal = 0
reward_money = 25
reward_item = "ITEM_ZINC"
raw_size = 20

[trainer_party]
index = 52

[[trainer_party.party]]
slot = 0
difficulty_value = 100
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 63
species = "SPECIES_WHIMSICOTT"
form = 0

[[trainer_party.party]]
slot = 1
difficulty_value = 100
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 63
species = "SPECIES_LILLIGANT"
form = 0
