[trainer]
index = 88
party_format = 0
trainer_class = 3
battle_type = 0
party_count = 3
items = ["ITEM_NONE", "ITEM_NONE", "ITEM_NONE", "ITEM_NONE"]
ai = 0
can_heal = 0
reward_money = 4
reward_item = "ITEM_ULTRA_BALL"
raw_size = 20

[trainer_party]
index = 88

[[trainer_party.party]]
slot = 0
difficulty_value = 0
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 60
species = "SPECIES_MISDREAVUS"
form = 0

[[trainer_party.party]]
slot = 1
difficulty_value = 0
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 60
species = "SPECIES_PACHIRISU"
form = 0

[[trainer_party.party]]
slot = 2
difficulty_value = 0
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 60
species = "SPECIES_DELCATTY"
form = 0
