[trainer]
index = 92
party_format = 0
trainer_class = 50
battle_type = 0
party_count = 3
items = ["ITEM_NONE", "ITEM_NONE", "ITEM_NONE", "ITEM_NONE"]
ai = 7
can_heal = 0
reward_money = 15
reward_item = "ITEM_PP_UP"
raw_size = 20

[trainer_party]
index = 92

[[trainer_party.party]]
slot = 0
difficulty_value = 100
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 63
species = "SPECIES_GALVANTULA"
form = 0

[[trainer_party.party]]
slot = 1
difficulty_value = 100
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 63
species = "SPECIES_TROPIUS"
form = 0

[[trainer_party.party]]
slot = 2
difficulty_value = 100
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 63
species = "SPECIES_MAMOSWINE"
form = 0
