[trainer]
index = 95
party_format = 0
trainer_class = 17
battle_type = 0
party_count = 6
items = ["ITEM_NONE", "ITEM_NONE", "ITEM_NONE", "ITEM_NONE"]
ai = 5
can_heal = 0
reward_money = 8
reward_item = "ITEM_RARE_CANDY"
raw_size = 20

[trainer_party]
index = 95

[[trainer_party.party]]
slot = 0
difficulty_value = 0
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 57
species = "SPECIES_BONSLY"
form = 0

[[trainer_party.party]]
slot = 1
difficulty_value = 0
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 57
species = "SPECIES_WOOPER"
form = 0

[[trainer_party.party]]
slot = 2
difficulty_value = 0
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 57
species = "SPECIES_MUNCHLAX"
form = 0

[[trainer_party.party]]
slot = 3
difficulty_value = 0
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 57
species = "SPECIES_SANDSHREW"
form = 0

[[trainer_party.party]]
slot = 4
difficulty_value = 0
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 57
species = "SPECIES_WYNAUT"
form = 0

[[trainer_party.party]]
slot = 5
difficulty_value = 0
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 57
species = "SPECIES_SPOINK"
form = 0
