[trainer]
index = 96
party_format = 0
trainer_class = 18
battle_type = 0
party_count = 6
items = ["ITEM_NONE", "ITEM_NONE", "ITEM_NONE", "ITEM_NONE"]
ai = 5
can_heal = 0
reward_money = 8
reward_item = "ITEM_RARE_CANDY"
raw_size = 20

[trainer_party]
index = 96

[[trainer_party.party]]
slot = 0
difficulty_value = 0
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 57
species = "SPECIES_SWINUB"
form = 0

[[trainer_party.party]]
slot = 1
difficulty_value = 0
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 57
species = "SPECIES_POLIWAG"
form = 0

[[trainer_party.party]]
slot = 2
difficulty_value = 0
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 57
species = "SPECIES_CLEFFA"
form = 0

[[trainer_party.party]]
slot = 3
difficulty_value = 0
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 57
species = "SPECIES_GIBLE"
form = 0

[[trainer_party.party]]
slot = 4
difficulty_value = 0
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 57
species = "SPECIES_IGGLYBUFF"
form = 0

[[trainer_party.party]]
slot = 5
difficulty_value = 0
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 57
species = "SPECIES_LARVITAR"
form = 0
