[trainer]
index = 99
party_format = 0
trainer_class = 52
battle_type = 0
party_count = 2
items = ["ITEM_X_DEFENSE", "ITEM_NONE", "ITEM_NONE", "ITEM_NONE"]
ai = 5
can_heal = 0
reward_money = 12
reward_item = "ITEM_ETHER"
raw_size = 20

[trainer_party]
index = 99

[[trainer_party.party]]
slot = 0
difficulty_value = 0
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 61
species = "SPECIES_STUNKY"
form = 0

[[trainer_party.party]]
slot = 1
difficulty_value = 0
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 61
species = "SPECIES_MUK"
form = 0
