[trainer]
index = 102
party_format = 0
trainer_class = 41
battle_type = 0
party_count = 1
items = ["ITEM_NONE", "ITEM_NONE", "ITEM_NONE", "ITEM_NONE"]
ai = 1
can_heal = 0
reward_money = 40
reward_item = "ITEM_STARDUST"
raw_size = 20

[trainer_party]
index = 102

[[trainer_party.party]]
slot = 0
difficulty_value = 0
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 62
species = "SPECIES_VOLBEAT"
form = 0
