[trainer]
index = 103
party_format = 0
trainer_class = 75
battle_type = 0
party_count = 2
items = ["ITEM_FULL_RESTORE", "ITEM_NONE", "ITEM_NONE", "ITEM_NONE"]
ai = 1
can_heal = 0
reward_money = 50
reward_item = "ITEM_BIG_PEARL"
raw_size = 20

[trainer_party]
index = 103

[[trainer_party.party]]
slot = 0
difficulty_value = 0
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 61
species = "SPECIES_SABLEYE"
form = 0

[[trainer_party.party]]
slot = 1
difficulty_value = 0
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 61
species = "SPECIES_LIEPARD"
form = 0
