[trainer]
index = 126
party_format = 1
trainer_class = 33
battle_type = 0
party_count = 1
items = ["ITEM_NONE", "ITEM_NONE", "ITEM_NONE", "ITEM_NONE"]
ai = 1
can_heal = 0
reward_money = 12
reward_item = "ITEM_ULTRA_BALL"
raw_size = 20

[trainer_party]
index = 126

[[trainer_party.party]]
slot = 0
difficulty_value = 0
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 62
species = "SPECIES_SMEARGLE"
form = 0
moves = ["MOVE_FIRE_BLAST", "MOVE_BLIZZARD", "MOVE_THUNDER", "MOVE_HURRICANE"]
