[trainer]
index = 127
party_format = 0
trainer_class = 86
battle_type = 0
party_count = 2
items = ["ITEM_NONE", "ITEM_NONE", "ITEM_NONE", "ITEM_NONE"]
ai = 7
can_heal = 0
reward_money = 10
reward_item = "ITEM_ULTRA_BALL"
raw_size = 20

[trainer_party]
index = 127

[[trainer_party.party]]
slot = 0
difficulty_value = 0
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 61
species = "SPECIES_ARCANINE"
form = 0

[[trainer_party.party]]
slot = 1
difficulty_value = 0
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 61
species = "SPECIES_MIENSHAO"
form = 0
