[trainer]
index = 163
party_format = 0
trainer_class = 145
battle_type = 0
party_count = 1
items = ["ITEM_NONE", "ITEM_NONE", "ITEM_NONE", "ITEM_NONE"]
ai = 16
can_heal = 0
reward_money = 25
reward_item = "ITEM_NONE"
raw_size = 20

[trainer_party]
index = 163

[[trainer_party.party]]
slot = 0
difficulty_value = 0
ability = "BATTLE_ABILITY_PRIMARY"
gender = "GENDER_RANDOM"
level = 5
species = "SPECIES_SNIVY"
form = 0
