[trainer]
index = 186
party_format = 3
trainer_class = 150
battle_type = 0
party_count = 3
items = ["ITEM_NONE", "ITEM_NONE", "ITEM_NONE", "ITEM_NONE"]
ai = 7
can_heal = 0
reward_money = 50
reward_item = "ITEM_NONE"
raw_size = 20

[trainer_party]
index = 186

[[trainer_party.party]]
slot = 0
difficulty_value = 64
ability = "BATTLE_ABILITY_SECONDARY"
gender = "GENDER_RANDOM"
level = 56
species = "SPECIES_WATCHOG"
form = 0
held_item = "ITEM_SHELL_BELL"
moves = ["MOVE_CRUNCH", "MOVE_HYPER_FANG", "MOVE_LOW_KICK", "MOVE_HYPNOSIS"]

[[trainer_party.party]]
slot = 1
difficulty_value = 64
ability = "BATTLE_ABILITY_PRIMARY"
gender = "GENDER_RANDOM"
level = 56
species = "SPECIES_SWOOBAT"
form = 0
held_item = "ITEM_WISE_GLASSES"
moves = ["MOVE_PSYCHIC", "MOVE_AIR_SLASH", "MOVE_UTURN", "MOVE_THUNDER_WAVE"]

[[trainer_party.party]]
slot = 2
difficulty_value = 64
ability = "BATTLE_ABILITY_PRIMARY"
gender = "GENDER_RANDOM"
level = 56
species = "SPECIES_BASCULIN"
form = 0
held_item = "ITEM_MYSTIC_WATER"
moves = ["MOVE_AQUA_JET", "MOVE_DOUBLEEDGE", "MOVE_ICE_BEAM", "MOVE_SWAGGER"]
