[trainer]
index = 213
party_format = 1
trainer_class = 27
battle_type = 0
party_count = 2
items = ["ITEM_NONE", "ITEM_NONE", "ITEM_NONE", "ITEM_NONE"]
ai = 1
can_heal = 0
reward_money = 6
reward_item = "ITEM_NONE"
raw_size = 20

[trainer_party]
index = 213

[[trainer_party.party]]
slot = 0
difficulty_value = 0
ability = "BATTLE_ABILITY_SECONDARY"
gender = "GENDER_RANDOM"
level = 16
species = "SPECIES_SANDILE"
form = 0
moves = ["MOVE_BITE", "MOVE_SAND_TOMB", "MOVE_TORMENT", "MOVE_RAGE"]

[[trainer_party.party]]
slot = 1
difficulty_value = 0
ability = "BATTLE_ABILITY_SECONDARY"
gender = "GENDER_RANDOM"
level = 16
species = "SPECIES_HERDIER"
form = 0
moves = ["MOVE_TACKLE", "MOVE_BITE", "MOVE_ODOR_SLEUTH", "MOVE_WORK_UP"]
