[trainer]
index = 262
party_format = 0
trainer_class = 83
battle_type = 0
party_count = 1
items = ["ITEM_NONE", "ITEM_NONE", "ITEM_NONE", "ITEM_NONE"]
ai = 1
can_heal = 0
reward_money = 10
reward_item = "ITEM_NONE"
raw_size = 20

[trainer_party]
index = 262

[[trainer_party.party]]
slot = 0
difficulty_value = 0
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 25
species = "SPECIES_DRILBUR"
form = 0
