[trainer]
index = 304
party_format = 0
trainer_class = 25
battle_type = 0
party_count = 3
items = ["ITEM_NONE", "ITEM_NONE", "ITEM_NONE", "ITEM_NONE"]
ai = 7
can_heal = 0
reward_money = 15
reward_item = "ITEM_ASPEAR_BERRY"
raw_size = 20

[trainer_party]
index = 304

[[trainer_party.party]]
slot = 0
difficulty_value = 50
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 52
species = "SPECIES_SIMISAGE"
form = 0

[[trainer_party.party]]
slot = 1
difficulty_value = 50
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 52
species = "SPECIES_SIMISEAR"
form = 0

[[trainer_party.party]]
slot = 2
difficulty_value = 50
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 52
species = "SPECIES_SIMIPOUR"
form = 0
