[trainer]
index = 333
party_format = 0
trainer_class = 17
battle_type = 0
party_count = 2
items = ["ITEM_NONE", "ITEM_NONE", "ITEM_NONE", "ITEM_NONE"]
ai = 5
can_heal = 0
reward_money = 8
reward_item = "ITEM_NONE"
raw_size = 20

[trainer_party]
index = 333

[[trainer_party.party]]
slot = 0
difficulty_value = 0
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 45
species = "SPECIES_CAMERUPT"
form = 0

[[trainer_party.party]]
slot = 1
difficulty_value = 0
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 45
species = "SPECIES_GRUMPIG"
form = 0
