[trainer]
index = 345
party_format = 3
trainer_class = 189
battle_type = 0
party_count = 6
items = ["ITEM_FULL_RESTORE", "ITEM_NONE", "ITEM_NONE", "ITEM_NONE"]
ai = 7
can_heal = 0
reward_money = 45
reward_item = "ITEM_NONE"
raw_size = 20

[trainer_party]
index = 345

[[trainer_party.party]]
slot = 0
difficulty_value = 200
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 50
species = "SPECIES_COFAGRIGUS"
form = 0
held_item = "ITEM_LEFTOVERS"
moves = ["MOVE_PROTECT", "MOVE_SHADOW_BALL", "MOVE_TOXIC", "MOVE_PSYCHIC"]

[[trainer_party.party]]
slot = 1
difficulty_value = 200
ability = "BATTLE_ABILITY_SECONDARY"
gender = "GENDER_RANDOM"
level = 50
species = "SPECIES_SEISMITOAD"
form = 0
held_item = "ITEM_NONE"
moves = ["MOVE_MUDDY_WATER", "MOVE_SLUDGE_WAVE", "MOVE_EARTHQUAKE", "MOVE_DRAIN_PUNCH"]

[[trainer_party.party]]
slot = 2
difficulty_value = 200
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 50
species = "SPECIES_EELEKTROSS"
form = 0
held_item = "ITEM_NONE"
moves = ["MOVE_THUNDERBOLT", "MOVE_CRUNCH", "MOVE_FLAMETHROWER", "MOVE_ACROBATICS"]

[[trainer_party.party]]
slot = 3
difficulty_value = 250
ability = "BATTLE_ABILITY_SECONDARY"
gender = "GENDER_RANDOM"
level = 50
species = "SPECIES_DRAPION"
form = 0
held_item = "ITEM_NONE"
moves = ["MOVE_NIGHT_SLASH", "MOVE_EARTHQUAKE", "MOVE_POISON_FANG", "MOVE_XSCISSOR"]

[[trainer_party.party]]
slot = 4
difficulty_value = 250
ability = "BATTLE_ABILITY_PRIMARY"
gender = "GENDER_RANDOM"
level = 50
species = "SPECIES_TOXICROAK"
form = 0
held_item = "ITEM_NONE"
moves = ["MOVE_POISON_JAB", "MOVE_SUCKER_PUNCH", "MOVE_SHADOW_BALL", "MOVE_BRICK_BREAK"]

[[trainer_party.party]]
slot = 5
difficulty_value = 250
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 52
species = "SPECIES_HYDREIGON"
form = 0
held_item = "ITEM_LIFE_ORB"
moves = ["MOVE_DRAGON_RUSH", "MOVE_CRUNCH", "MOVE_ROCK_SLIDE", "MOVE_FRUSTRATION"]
