[trainer]
index = 389
party_format = 0
trainer_class = 25
battle_type = 0
party_count = 1
items = ["ITEM_NONE", "ITEM_NONE", "ITEM_NONE", "ITEM_NONE"]
ai = 7
can_heal = 0
reward_money = 15
reward_item = "ITEM_LEPPA_BERRY"
raw_size = 20

[trainer_party]
index = 389

[[trainer_party.party]]
slot = 0
difficulty_value = 50
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 33
species = "SPECIES_ARCANINE"
form = 0
