[trainer]
index = 491
party_format = 0
trainer_class = 26
battle_type = 0
party_count = 3
items = ["ITEM_NONE", "ITEM_NONE", "ITEM_NONE", "ITEM_NONE"]
ai = 1
can_heal = 0
reward_money = 10
reward_item = "ITEM_NONE"
raw_size = 20

[trainer_party]
index = 491

[[trainer_party.party]]
slot = 0
difficulty_value = 0
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 60
species = "SPECIES_EXCADRILL"
form = 0

[[trainer_party.party]]
slot = 1
difficulty_value = 0
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 60
species = "SPECIES_NIDOKING"
form = 0

[[trainer_party.party]]
slot = 2
difficulty_value = 0
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 60
species = "SPECIES_RHYDON"
form = 0
