[trainer]
index = 580
party_format = 2
trainer_class = 51
battle_type = 0
party_count = 4
items = ["ITEM_NONE", "ITEM_NONE", "ITEM_NONE", "ITEM_NONE"]
ai = 3
can_heal = 0
reward_money = 8
reward_item = "ITEM_NONE"
raw_size = 20

[trainer_party]
index = 580

[[trainer_party.party]]
slot = 0
difficulty_value = 50
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 44
species = "SPECIES_ROGGENROLA"
form = 0
held_item = "ITEM_HARD_STONE"

[[trainer_party.party]]
slot = 1
difficulty_value = 50
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 44
species = "SPECIES_ROGGENROLA"
form = 0
held_item = "ITEM_HARD_STONE"

[[trainer_party.party]]
slot = 2
difficulty_value = 50
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 44
species = "SPECIES_ROGGENROLA"
form = 0
held_item = "ITEM_HARD_STONE"

[[trainer_party.party]]
slot = 3
difficulty_value = 50
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 44
species = "SPECIES_ROGGENROLA"
form = 0
held_item = "ITEM_HARD_STONE"
