[trainer]
index = 582
party_format = 3
trainer_class = 89
battle_type = 0
party_count = 6
items = ["ITEM_FULL_RESTORE", "ITEM_FULL_RESTORE", "ITEM_NONE", "ITEM_NONE"]
ai = 7
can_heal = 0
reward_money = 50
reward_item = "ITEM_NONE"
raw_size = 20

[trainer_party]
index = 582

[[trainer_party.party]]
slot = 0
difficulty_value = 250
ability = "BATTLE_ABILITY_SECONDARY"
gender = "GENDER_RANDOM"
level = 60
species = "SPECIES_ACCELGOR"
form = 0
held_item = "ITEM_NONE"
moves = ["MOVE_BUG_BUZZ", "MOVE_FOCUS_BLAST", "MOVE_GIGA_DRAIN", "MOVE_ACID_SPRAY"]

[[trainer_party.party]]
slot = 1
difficulty_value = 250
ability = "BATTLE_ABILITY_SECONDARY"
gender = "GENDER_RANDOM"
level = 60
species = "SPECIES_ESCAVALIER"
form = 0
held_item = "ITEM_NONE"
moves = ["MOVE_XSCISSOR", "MOVE_IRON_HEAD", "MOVE_REVERSAL", "MOVE_SWORDS_DANCE"]

[[trainer_party.party]]
slot = 2
difficulty_value = 250
ability = "BATTLE_ABILITY_PRIMARY"
gender = "GENDER_RANDOM"
level = 60
species = "SPECIES_BOUFFALANT"
form = 0
held_item = "ITEM_NONE"
moves = ["MOVE_HEAD_CHARGE", "MOVE_MEGAHORN", "MOVE_EARTHQUAKE", "MOVE_WILD_CHARGE"]

[[trainer_party.party]]
slot = 3
difficulty_value = 250
ability = "BATTLE_ABILITY_PRIMARY"
gender = "GENDER_RANDOM"
level = 60
species = "SPECIES_CONKELDURR"
form = 0
held_item = "ITEM_NONE"
moves = ["MOVE_SUPERPOWER", "MOVE_STONE_EDGE", "MOVE_POISON_JAB", "MOVE_EARTHQUAKE"]

[[trainer_party.party]]
slot = 4
difficulty_value = 250
ability = "BATTLE_ABILITY_PRIMARY"
gender = "GENDER_RANDOM"
level = 60
species = "SPECIES_BRAVIARY"
form = 0
held_item = "ITEM_NONE"
moves = ["MOVE_CRUSH_CLAW", "MOVE_SUPERPOWER", "MOVE_AERIAL_ACE", "MOVE_ROCK_SLIDE"]

[[trainer_party.party]]
slot = 5
difficulty_value = 250
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 62
species = "SPECIES_VOLCARONA"
form = 0
held_item = "ITEM_SITRUS_BERRY"
moves = ["MOVE_HEAT_WAVE", "MOVE_QUIVER_DANCE", "MOVE_SILVER_WIND", "MOVE_PSYCHIC"]
