[trainer]
index = 588
party_format = 2
trainer_class = 145
battle_type = 0
party_count = 2
items = ["ITEM_NONE", "ITEM_NONE", "ITEM_NONE", "ITEM_NONE"]
ai = 135
can_heal = 0
reward_money = 25
reward_item = "ITEM_NONE"
raw_size = 20

[trainer_party]
index = 588

[[trainer_party.party]]
slot = 0
difficulty_value = 250
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 20
species = "SPECIES_PIGNITE"
form = 0
held_item = "ITEM_CHARCOAL"

[[trainer_party.party]]
slot = 1
difficulty_value = 250
ability = "BATTLE_ABILITY_PRIMARY"
gender = "GENDER_RANDOM"
level = 18
species = "SPECIES_PIDOVE"
form = 0
held_item = "ITEM_NONE"
