[trainer]
index = 610
party_format = 1
trainer_class = 50
battle_type = 0
party_count = 2
items = ["ITEM_NONE", "ITEM_NONE", "ITEM_NONE", "ITEM_NONE"]
ai = 7
can_heal = 0
reward_money = 15
reward_item = "ITEM_NONE"
raw_size = 20

[trainer_party]
index = 610

[[trainer_party.party]]
slot = 0
difficulty_value = 100
ability = "BATTLE_ABILITY_SECONDARY"
gender = "GENDER_RANDOM"
level = 55
species = "SPECIES_SWANNA"
form = 0
moves = ["MOVE_BRAVE_BIRD", "MOVE_SCALD", "MOVE_ROOST", "MOVE_RAIN_DANCE"]

[[trainer_party.party]]
slot = 1
difficulty_value = 100
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 55
species = "SPECIES_AMPHAROS"
form = 0
moves = ["MOVE_THUNDER", "MOVE_BULLDOZE", "MOVE_BRICK_BREAK", "MOVE_COTTON_GUARD"]
