[trainer]
index = 631
party_format = 0
trainer_class = 87
battle_type = 0
party_count = 1
items = ["ITEM_NONE", "ITEM_NONE", "ITEM_NONE", "ITEM_NONE"]
ai = 1
can_heal = 0
reward_money = 10
reward_item = "ITEM_NONE"
raw_size = 20

[trainer_party]
index = 631

[[trainer_party.party]]
slot = 0
difficulty_value = 0
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 17
species = "SPECIES_ELEKID"
form = 0
