[trainer]
index = 644
party_format = 1
trainer_class = 71
battle_type = 0
party_count = 3
items = ["ITEM_NONE", "ITEM_NONE", "ITEM_NONE", "ITEM_NONE"]
ai = 135
can_heal = 0
reward_money = 20
reward_item = "ITEM_NONE"
raw_size = 20

[trainer_party]
index = 644

[[trainer_party.party]]
slot = 0
difficulty_value = 200
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 64
species = "SPECIES_CROBAT"
form = 0
moves = ["MOVE_CROSS_POISON", "MOVE_UTURN", "MOVE_RAIN_DANCE", "MOVE_SUNNY_DAY"]

[[trainer_party.party]]
slot = 1
difficulty_value = 200
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 64
species = "SPECIES_MAGMORTAR"
form = 0
moves = ["MOVE_FLARE_BLITZ", "MOVE_PSYCHIC", "MOVE_THUNDERBOLT", "MOVE_WILLOWISP"]

[[trainer_party.party]]
slot = 2
difficulty_value = 200
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 64
species = "SPECIES_LEAFEON"
form = 0
moves = ["MOVE_LEAF_BLADE", "MOVE_XSCISSOR", "MOVE_QUICK_ATTACK", "MOVE_SWORDS_DANCE"]
