[trainer]
index = 651
party_format = 0
trainer_class = 16
battle_type = 1
party_count = 2
items = ["ITEM_NONE", "ITEM_NONE", "ITEM_NONE", "ITEM_NONE"]
ai = 128
can_heal = 0
reward_money = 4
reward_item = "ITEM_NONE"
raw_size = 20

[trainer_party]
index = 651

[[trainer_party.party]]
slot = 0
difficulty_value = 0
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 60
species = "SPECIES_PLUSLE"
form = 0

[[trainer_party.party]]
slot = 1
difficulty_value = 0
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 60
species = "SPECIES_MINUN"
form = 0
