[trainer]
index = 671
party_format = 0
trainer_class = 61
battle_type = 0
party_count = 2
items = ["ITEM_FULL_HEAL", "ITEM_HYPER_POTION", "ITEM_NONE", "ITEM_NONE"]
ai = 7
can_heal = 1
reward_money = 15
reward_item = "ITEM_NONE"
raw_size = 20

[trainer_party]
index = 671

[[trainer_party.party]]
slot = 0
difficulty_value = 0
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 32
species = "SPECIES_SOLOSIS"
form = 0

[[trainer_party.party]]
slot = 1
difficulty_value = 0
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 32
species = "SPECIES_GOTHITA"
form = 0
