[trainer]
index = 712
party_format = 0
trainer_class = 51
battle_type = 0
party_count = 1
items = ["ITEM_NONE", "ITEM_NONE", "ITEM_NONE", "ITEM_NONE"]
ai = 3
can_heal = 0
reward_money = 8
reward_item = "ITEM_NONE"
raw_size = 20

[trainer_party]
index = 712

[[trainer_party.party]]
slot = 0
difficulty_value = 50
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 15
species = "SPECIES_RIOLU"
form = 0
