[trainer]
index = 720
party_format = 0
trainer_class = 49
battle_type = 0
party_count = 1
items = ["ITEM_NONE", "ITEM_NONE", "ITEM_NONE", "ITEM_NONE"]
ai = 7
can_heal = 0
reward_money = 15
reward_item = "ITEM_NONE"
raw_size = 20

[trainer_party]
index = 720

[[trainer_party.party]]
slot = 0
difficulty_value = 100
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 40
species = "SPECIES_SAWSBUCK"
form = 0
