[trainer]
index = 729
party_format = 0
trainer_class = 45
battle_type = 2
party_count = 3
items = ["ITEM_NONE", "ITEM_NONE", "ITEM_NONE", "ITEM_NONE"]
ai = 135
can_heal = 0
reward_money = 25
reward_item = "ITEM_NONE"
raw_size = 20

[trainer_party]
index = 729

[[trainer_party.party]]
slot = 0
difficulty_value = 100
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 42
species = "SPECIES_MAGBY"
form = 0

[[trainer_party.party]]
slot = 1
difficulty_value = 100
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 42
species = "SPECIES_MAGMAR"
form = 0

[[trainer_party.party]]
slot = 2
difficulty_value = 100
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 42
species = "SPECIES_MAGBY"
form = 0
