[trainer]
index = 774
party_format = 3
trainer_class = 79
battle_type = 0
party_count = 5
items = ["ITEM_FULL_RESTORE", "ITEM_NONE", "ITEM_NONE", "ITEM_NONE"]
ai = 7
can_heal = 0
reward_money = 30
reward_item = "ITEM_NONE"
raw_size = 20

[trainer_party]
index = 774

[[trainer_party.party]]
slot = 0
difficulty_value = 250
ability = "BATTLE_ABILITY_PRIMARY"
gender = "GENDER_RANDOM"
level = 56
species = "SPECIES_THROH"
form = 0
held_item = "ITEM_LEFTOVERS"
moves = ["MOVE_STORM_THROW", "MOVE_BULLDOZE", "MOVE_ROCK_TOMB", "MOVE_PAYBACK"]

[[trainer_party.party]]
slot = 1
difficulty_value = 250
ability = "BATTLE_ABILITY_PRIMARY"
gender = "GENDER_RANDOM"
level = 56
species = "SPECIES_SAWK"
form = 0
held_item = "ITEM_MUSCLE_BAND"
moves = ["MOVE_BRICK_BREAK", "MOVE_RETALIATE", "MOVE_ROCK_SLIDE", "MOVE_PAYBACK"]

[[trainer_party.party]]
slot = 2
difficulty_value = 250
ability = "BATTLE_ABILITY_SECONDARY"
gender = "GENDER_RANDOM"
level = 56
species = "SPECIES_MIENSHAO"
form = 0
held_item = "ITEM_EXPERT_BELT"
moves = ["MOVE_HI_JUMP_KICK", "MOVE_UTURN", "MOVE_BOUNCE", "MOVE_RETALIATE"]

[[trainer_party.party]]
slot = 3
difficulty_value = 250
ability = "BATTLE_ABILITY_SECONDARY"
gender = "GENDER_RANDOM"
level = 56
species = "SPECIES_LUCARIO"
form = 0
held_item = "ITEM_WISE_GLASSES"
moves = ["MOVE_AURA_SPHERE", "MOVE_SHADOW_BALL", "MOVE_PSYCHIC", "MOVE_CALM_MIND"]

[[trainer_party.party]]
slot = 4
difficulty_value = 250
ability = "BATTLE_ABILITY_PRIMARY"
gender = "GENDER_RANDOM"
level = 58
species = "SPECIES_CONKELDURR"
form = 0
held_item = "ITEM_FLAME_ORB"
moves = ["MOVE_HAMMER_ARM", "MOVE_BULK_UP", "MOVE_STONE_EDGE", "MOVE_EARTHQUAKE"]
