[trainer]
index = 797
party_format = 0
trainer_class = 187
battle_type = 0
party_count = 3
items = ["ITEM_NONE", "ITEM_NONE", "ITEM_NONE", "ITEM_NONE"]
ai = 129
can_heal = 0
reward_money = 10
reward_item = "ITEM_NONE"
raw_size = 20

[trainer_party]
index = 797

[[trainer_party.party]]
slot = 0
difficulty_value = 0
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 45
species = "SPECIES_LIEPARD"
form = 0

[[trainer_party.party]]
slot = 1
difficulty_value = 0
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 45
species = "SPECIES_WATCHOG"
form = 0

[[trainer_party.party]]
slot = 2
difficulty_value = 0
ability = "BATTLE_ABILITY_RANDOM"
gender = "GENDER_RANDOM"
level = 45
species = "SPECIES_SCOLIPEDE"
form = 0
