items = [
  'none.toml',
  'master_ball.toml',
  'ultra_ball.toml',
  'great_ball.toml',
  'poke_ball.toml',
  'safari_ball.toml',
  'net_ball.toml',
  'dive_ball.toml',
  'nest_ball.toml',
  'repeat_ball.toml',
  'timer_ball.toml',
  'luxury_ball.toml',
  'premier_ball.toml',
  'dusk_ball.toml',
  'heal_ball.toml',
  'quick_ball.toml',
  'cherish_ball.toml',
  'potion.toml',
  'antidote.toml',
  'burn_heal.toml',
  'ice_heal.toml',
  'awakening.toml',
  'parlyz_heal.toml',
  'full_restore.toml',
  'max_potion.toml',
  'hyper_potion.toml',
  'super_potion.toml',
  'full_heal.toml',
  'revive.toml',
  'max_revive.toml',
  'fresh_water.toml',
  'soda_pop.toml',
  'lemonade.toml',
  'moomoo_milk.toml',
  'energypowder.toml',
  'energy_root.toml',
  'heal_powder.toml',
  'revival_herb.toml',
  'ether.toml',
  'max_ether.toml',
  'elixir.toml',
  'max_elixir.toml',
  'lava_cookie.toml',
  'berry_juice.toml',
  'sacred_ash.toml',
  'hp_up.toml',
  'protein.toml',
  'iron.toml',
  'carbos.toml',
  'calcium.toml',
  'rare_candy.toml',
  'pp_up.toml',
  'zinc.toml',
  'pp_max.toml',
  'old_gateau.toml',
  'guard_spec.toml',
  'dire_hit.toml',
  'x_attack.toml',
  'x_defend.toml',
  'x_speed.toml',
  'x_accuracy.toml',
  'x_special.toml',
  'x_sp_def.toml',
  'poke_doll.toml',
  'fluffy_tail.toml',
  'blue_flute.toml',
  'yellow_flute.toml',
  'red_flute.toml',
  'black_flute.toml',
  'white_flute.toml',
  'shoal_salt.toml',
  'shoal_shell.toml',
  'red_shard.toml',
  'blue_shard.toml',
  'yellow_shard.toml',
  'green_shard.toml',
  'super_repel.toml',
  'max_repel.toml',
  'escape_rope.toml',
  'repel.toml',
  'sun_stone.toml',
  'moon_stone.toml',
  'fire_stone.toml',
  'thunderstone.toml',
  'water_stone.toml',
  'leaf_stone.toml',
  'tinymushroom.toml',
  'big_mushroom.toml',
  'pearl.toml',
  'big_pearl.toml',
  'stardust.toml',
  'star_piece.toml',
  'nugget.toml',
  'heart_scale.toml',
  'honey.toml',
  'growth_mulch.toml',
  'damp_mulch.toml',
  'stable_mulch.toml',
  'gooey_mulch.toml',
  'root_fossil.toml',
  'claw_fossil.toml',
  'helix_fossil.toml',
  'dome_fossil.toml',
  'old_amber.toml',
  'armor_fossil.toml',
  'skull_fossil.toml',
  'rare_bone.toml',
  'shiny_stone.toml',
  'dusk_stone.toml',
  'dawn_stone.toml',
  'oval_stone.toml',
  'odd_keystone.toml',
  'griseous_orb.toml',
  'unknown.toml',
  'unknown_114.toml',
  'unknown_115.toml',
  'douse_drive.toml',
  'shock_drive.toml',
  'burn_drive.toml',
  'chill_drive.toml',
  'unknown_120.toml',
  'unknown_121.toml',
  'unknown_122.toml',
  'unknown_123.toml',
  'unknown_124.toml',
  'unknown_125.toml',
  'unknown_126.toml',
  'unknown_127.toml',
  'unknown_128.toml',
  'unknown_129.toml',
  'unknown_130.toml',
  'unknown_131.toml',
  'unknown_132.toml',
  'unknown_133.toml',
  'sweet_heart.toml',
  'adamant_orb.toml',
  'lustrous_orb.toml',
  'greet_mail.toml',
  'favored_mail.toml',
  'rsvp_mail.toml',
  'thanks_mail.toml',
  'inquiry_mail.toml',
  'like_mail.toml',
  'reply_mail.toml',
  'bridgemail_s.toml',
  'bridgemail_d.toml',
  'bridgemail_t.toml',
  'bridgemail_v.toml',
  'bridgemail_m.toml',
  'cheri_berry.toml',
  'chesto_berry.toml',
  'pecha_berry.toml',
  'rawst_berry.toml',
  'aspear_berry.toml',
  'leppa_berry.toml',
  'oran_berry.toml',
  'persim_berry.toml',
  'lum_berry.toml',
  'sitrus_berry.toml',
  'figy_berry.toml',
  'wiki_berry.toml',
  'mago_berry.toml',
  'aguav_berry.toml',
  'iapapa_berry.toml',
  'razz_berry.toml',
  'bluk_berry.toml',
  'nanab_berry.toml',
  'wepear_berry.toml',
  'pinap_berry.toml',
  'pomeg_berry.toml',
  'kelpsy_berry.toml',
  'qualot_berry.toml',
  'hondew_berry.toml',
  'grepa_berry.toml',
  'tamato_berry.toml',
  'cornn_berry.toml',
  'magost_berry.toml',
  'rabuta_berry.toml',
  'nomel_berry.toml',
  'spelon_berry.toml',
  'pamtre_berry.toml',
  'watmel_berry.toml',
  'durin_berry.toml',
  'belue_berry.toml',
  'occa_berry.toml',
  'passho_berry.toml',
  'wacan_berry.toml',
  'rindo_berry.toml',
  'yache_berry.toml',
  'chople_berry.toml',
  'kebia_berry.toml',
  'shuca_berry.toml',
  'coba_berry.toml',
  'payapa_berry.toml',
  'tanga_berry.toml',
  'charti_berry.toml',
  'kasib_berry.toml',
  'haban_berry.toml',
  'colbur_berry.toml',
  'babiri_berry.toml',
  'chilan_berry.toml',
  'liechi_berry.toml',
  'ganlon_berry.toml',
  'salac_berry.toml',
  'petaya_berry.toml',
  'apicot_berry.toml',
  'lansat_berry.toml',
  'starf_berry.toml',
  'enigma_berry.toml',
  'micle_berry.toml',
  'custap_berry.toml',
  'jaboca_berry.toml',
  'rowap_berry.toml',
  'brightpowder.toml',
  'white_herb.toml',
  'macho_brace.toml',
  'exp_share.toml',
  'quick_claw.toml',
  'soothe_bell.toml',
  'mental_herb.toml',
  'choice_band.toml',
  'kings_rock.toml',
  'silverpowder.toml',
  'amulet_coin.toml',
  'cleanse_tag.toml',
  'soul_dew.toml',
  'deepseatooth.toml',
  'deepseascale.toml',
  'smoke_ball.toml',
  'everstone.toml',
  'focus_band.toml',
  'lucky_egg.toml',
  'scope_lens.toml',
  'metal_coat.toml',
  'leftovers.toml',
  'dragon_scale.toml',
  'light_ball.toml',
  'soft_sand.toml',
  'hard_stone.toml',
  'miracle_seed.toml',
  'blackglasses.toml',
  'black_belt.toml',
  'magnet.toml',
  'mystic_water.toml',
  'sharp_beak.toml',
  'poison_barb.toml',
  'nevermeltice.toml',
  'spell_tag.toml',
  'twistedspoon.toml',
  'charcoal.toml',
  'dragon_fang.toml',
  'silk_scarf.toml',
  'up_grade.toml',
  'shell_bell.toml',
  'sea_incense.toml',
  'lax_incense.toml',
  'lucky_punch.toml',
  'metal_powder.toml',
  'thick_club.toml',
  'stick.toml',
  'red_scarf.toml',
  'blue_scarf.toml',
  'pink_scarf.toml',
  'green_scarf.toml',
  'yellow_scarf.toml',
  'wide_lens.toml',
  'muscle_band.toml',
  'wise_glasses.toml',
  'expert_belt.toml',
  'light_clay.toml',
  'life_orb.toml',
  'power_herb.toml',
  'toxic_orb.toml',
  'flame_orb.toml',
  'quick_powder.toml',
  'focus_sash.toml',
  'zoom_lens.toml',
  'metronome.toml',
  'iron_ball.toml',
  'lagging_tail.toml',
  'destiny_knot.toml',
  'black_sludge.toml',
  'icy_rock.toml',
  'smooth_rock.toml',
  'heat_rock.toml',
  'damp_rock.toml',
  'grip_claw.toml',
  'choice_scarf.toml',
  'sticky_barb.toml',
  'power_bracer.toml',
  'power_belt.toml',
  'power_lens.toml',
  'power_band.toml',
  'power_anklet.toml',
  'power_weight.toml',
  'shed_shell.toml',
  'big_root.toml',
  'choice_specs.toml',
  'flame_plate.toml',
  'splash_plate.toml',
  'zap_plate.toml',
  'meadow_plate.toml',
  'icicle_plate.toml',
  'fist_plate.toml',
  'toxic_plate.toml',
  'earth_plate.toml',
  'sky_plate.toml',
  'mind_plate.toml',
  'insect_plate.toml',
  'stone_plate.toml',
  'spooky_plate.toml',
  'draco_plate.toml',
  'dread_plate.toml',
  'iron_plate.toml',
  'odd_incense.toml',
  'rock_incense.toml',
  'full_incense.toml',
  'wave_incense.toml',
  'rose_incense.toml',
  'luck_incense.toml',
  'pure_incense.toml',
  'protector.toml',
  'electirizer.toml',
  'magmarizer.toml',
  'dubious_disc.toml',
  'reaper_cloth.toml',
  'razor_claw.toml',
  'razor_fang.toml',
  'tm01.toml',
  'tm02.toml',
  'tm03.toml',
  'tm04.toml',
  'tm05.toml',
  'tm06.toml',
  'tm07.toml',
  'tm08.toml',
  'tm09.toml',
  'tm10.toml',
  'tm11.toml',
  'tm12.toml',
  'tm13.toml',
  'tm14.toml',
  'tm15.toml',
  'tm16.toml',
  'tm17.toml',
  'tm18.toml',
  'tm19.toml',
  'tm20.toml',
  'tm21.toml',
  'tm22.toml',
  'tm23.toml',
  'tm24.toml',
  'tm25.toml',
  'tm26.toml',
  'tm27.toml',
  'tm28.toml',
  'tm29.toml',
  'tm30.toml',
  'tm31.toml',
  'tm32.toml',
  'tm33.toml',
  'tm34.toml',
  'tm35.toml',
  'tm36.toml',
  'tm37.toml',
  'tm38.toml',
  'tm39.toml',
  'tm40.toml',
  'tm41.toml',
  'tm42.toml',
  'tm43.toml',
  'tm44.toml',
  'tm45.toml',
  'tm46.toml',
  'tm47.toml',
  'tm48.toml',
  'tm49.toml',
  'tm50.toml',
  'tm51.toml',
  'tm52.toml',
  'tm53.toml',
  'tm54.toml',
  'tm55.toml',
  'tm56.toml',
  'tm57.toml',
  'tm58.toml',
  'tm59.toml',
  'tm60.toml',
  'tm61.toml',
  'tm62.toml',
  'tm63.toml',
  'tm64.toml',
  'tm65.toml',
  'tm66.toml',
  'tm67.toml',
  'tm68.toml',
  'tm69.toml',
  'tm70.toml',
  'tm71.toml',
  'tm72.toml',
  'tm73.toml',
  'tm74.toml',
  'tm75.toml',
  'tm76.toml',
  'tm77.toml',
  'tm78.toml',
  'tm79.toml',
  'tm80.toml',
  'tm81.toml',
  'tm82.toml',
  'tm83.toml',
  'tm84.toml',
  'tm85.toml',
  'tm86.toml',
  'tm87.toml',
  'tm88.toml',
  'tm89.toml',
  'tm90.toml',
  'tm91.toml',
  'tm92.toml',
  'hm01.toml',
  'hm02.toml',
  'hm03.toml',
  'hm04.toml',
  'hm05.toml',
  'hm06.toml',
  'unknown_426.toml',
  'unknown_427.toml',
  'explorer_kit.toml',
  'loot_sack.toml',
  'rule_book.toml',
  'poke_radar.toml',
  'point_card.toml',
  'journal.toml',
  'seal_case.toml',
  'fashion_case.toml',
  'seal_bag.toml',
  'pal_pad.toml',
  'works_key.toml',
  'old_charm.toml',
  'galactic_key.toml',
  'red_chain.toml',
  'town_map.toml',
  'vs_seeker.toml',
  'coin_case.toml',
  'old_rod.toml',
  'good_rod.toml',
  'super_rod.toml',
  'sprayduck.toml',
  'poffin_case.toml',
  'bicycle.toml',
  'suite_key.toml',
  'oaks_letter.toml',
  'lunar_wing.toml',
  'member_card.toml',
  'azure_flute.toml',
  's_s_ticket.toml',
  'contest_pass.toml',
  'magma_stone.toml',
  'parcel.toml',
  'coupon_1.toml',
  'coupon_2.toml',
  'coupon_3.toml',
  'storage_key.toml',
  'secretpotion.toml',
  'vs_recorder.toml',
  'gracidea.toml',
  'secret_key.toml',
  'apricorn_box.toml',
  'unown_report.toml',
  'berry_pots.toml',
  'dowsing_mchn.toml',
  'blue_card.toml',
  'slowpoketail.toml',
  'clear_bell.toml',
  'card_key.toml',
  'basement_key.toml',
  'squirtbottle.toml',
  'red_scale.toml',
  'lost_item.toml',
  'pass.toml',
  'machine_part.toml',
  'silver_wing.toml',
  'rainbow_wing.toml',
  'mystery_egg.toml',
  'red_apricorn.toml',
  'blu_apricorn.toml',
  'ylw_apricorn.toml',
  'grn_apricorn.toml',
  'pnk_apricorn.toml',
  'wht_apricorn.toml',
  'blk_apricorn.toml',
  'fast_ball.toml',
  'level_ball.toml',
  'lure_ball.toml',
  'heavy_ball.toml',
  'love_ball.toml',
  'friend_ball.toml',
  'moon_ball.toml',
  'sport_ball.toml',
  'park_ball.toml',
  'photo_album.toml',
  'gb_sounds.toml',
  'tidal_bell.toml',
  'ragecandybar.toml',
  'data_card_01.toml',
  'data_card_02.toml',
  'data_card_03.toml',
  'data_card_04.toml',
  'data_card_05.toml',
  'data_card_06.toml',
  'data_card_07.toml',
  'data_card_08.toml',
  'data_card_09.toml',
  'data_card_10.toml',
  'data_card_11.toml',
  'data_card_12.toml',
  'data_card_13.toml',
  'data_card_14.toml',
  'data_card_15.toml',
  'data_card_16.toml',
  'data_card_17.toml',
  'data_card_18.toml',
  'data_card_19.toml',
  'data_card_20.toml',
  'data_card_21.toml',
  'data_card_22.toml',
  'data_card_23.toml',
  'data_card_24.toml',
  'data_card_25.toml',
  'data_card_26.toml',
  'data_card_27.toml',
  'jade_orb.toml',
  'lock_capsule.toml',
  'red_orb.toml',
  'blue_orb.toml',
  'enigma_stone.toml',
  'prism_scale.toml',
  'eviolite.toml',
  'float_stone.toml',
  'rocky_helmet.toml',
  'air_balloon.toml',
  'red_card.toml',
  'ring_target.toml',
  'binding_band.toml',
  'absorb_bulb.toml',
  'cell_battery.toml',
  'eject_button.toml',
  'fire_gem.toml',
  'water_gem.toml',
  'electric_gem.toml',
  'grass_gem.toml',
  'ice_gem.toml',
  'fighting_gem.toml',
  'poison_gem.toml',
  'ground_gem.toml',
  'flying_gem.toml',
  'psychic_gem.toml',
  'bug_gem.toml',
  'rock_gem.toml',
  'ghost_gem.toml',
  'dragon_gem.toml',
  'dark_gem.toml',
  'steel_gem.toml',
  'normal_gem.toml',
  'health_wing.toml',
  'muscle_wing.toml',
  'resist_wing.toml',
  'genius_wing.toml',
  'clever_wing.toml',
  'swift_wing.toml',
  'pretty_wing.toml',
  'cover_fossil.toml',
  'plume_fossil.toml',
  'liberty_pass.toml',
  'pass_orb.toml',
  'dream_ball.toml',
  'poke_toy.toml',
  'prop_case.toml',
  'dragon_skull.toml',
  'balmmushroom.toml',
  'big_nugget.toml',
  'pearl_string.toml',
  'comet_shard.toml',
  'relic_copper.toml',
  'relic_silver.toml',
  'relic_gold.toml',
  'relic_vase.toml',
  'relic_band.toml',
  'relic_statue.toml',
  'relic_crown.toml',
  'casteliacone.toml',
  'dire_hit_2.toml',
  'x_speed_2.toml',
  'x_special_2.toml',
  'x_sp_def_2.toml',
  'x_defend_2.toml',
  'x_attack_2.toml',
  'x_accuracy_2.toml',
  'x_speed_3.toml',
  'x_special_3.toml',
  'x_sp_def_3.toml',
  'x_defend_3.toml',
  'x_attack_3.toml',
  'x_accuracy_3.toml',
  'x_speed_6.toml',
  'x_special_6.toml',
  'x_sp_def_6.toml',
  'x_defend_6.toml',
  'x_attack_6.toml',
  'x_accuracy_6.toml',
  'ability_urge.toml',
  'item_drop.toml',
  'item_urge.toml',
  'reset_urge.toml',
  'dire_hit_3.toml',
  'light_stone.toml',
  'dark_stone.toml',
  'tm93.toml',
  'tm94.toml',
  'tm95.toml',
  'xtransceiver.toml',
  'unknown_622.toml',
  'gram_1.toml',
  'gram_2.toml',
  'gram_3.toml',
  'xtransceiver_626.toml',
  'medal_box.toml',
  'dna_splicers.toml',
  'dna_splicers_629.toml',
  'permit.toml',
  'oval_charm.toml',
  'shiny_charm.toml',
  'plasma_card.toml',
  'grubby_hanky.toml',
  'colress_mchn.toml',
  'dropped_item.toml',
  'dropped_item_637.toml',
  'reveal_glass.toml',
]

# Items (/a/0/2/4)
items_arc = 'a' / '0' / '2' / '4'
item_files = []
foreach item_index : range(items.length())
  item_files += custom_target(
    'item_' + item_index.to_string(),
    input: meson.current_source_dir() / items[item_index],
    output: 'item_' + item_index.to_string(),
    command: [mkdata_py, 'generic', '@INPUT@', meson.project_build_root() / '@OUTPUT@', 'format', 'items'],
  )
endforeach

vfs_files += custom_target(
  'pack_items_narc',
  input: item_files,
  output: 'pack_items_narc.stamp',
  command: [pack_narc_py, '@OUTPUT@', meson.project_source_root() / 'vfs' / 'data' / items_arc, '@INPUT@'],
)
