[personal]
index = 4
species = "SPECIES_CHARMANDER"
capture_rate = 45
evolution_stage = 1
ev_yield = 64
gender_probability = 31
egg_happiness = 20
base_happiness = 70
experience_group = 3
egg_groups = [1, 14]
escape_rate = 0
color = 0
base_experience = 62
height_cm = 6
weight_cg = 85

[personal.base_stats]
hp = 39
attack = 52
defense = 43
speed = 65
special_attack = 60
special_defense = 50

[personal.typing]
primary = "TYPE_FIRE"
secondary = "TYPE_FIRE"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 66
secondary = "BATTLE_ABILITY_RANDOM"
hidden = 94

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-871299549, 344170212, -1572830207, 4]
type_tutors = 2
special_tutors = [12288, 65536, 18, 8704]
