[personal]
index = 15
species = "SPECIES_BEEDRILL"
capture_rate = 45
evolution_stage = 3
ev_yield = 1032
gender_probability = 127
egg_happiness = 15
base_happiness = 70
experience_group = 0
egg_groups = [3, 3]
escape_rate = 0
color = 2
base_experience = 173
height_cm = 10
weight_cg = 295

[personal.base_stats]
hp = 65
attack = 80
defense = 40
speed = 75
special_attack = 45
special_defense = 80

[personal.typing]
primary = "TYPE_BUG"
secondary = "TYPE_POISON"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_POISON_BARB"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 68
secondary = "BATTLE_ABILITY_RANDOM"
hidden = 97

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-1003403488, 539015816, -1555493846, 0]
type_tutors = 0
special_tutors = [129, 512, 5254, 8448]
