[personal]
index = 25
species = "SPECIES_PIKACHU"
capture_rate = 190
evolution_stage = 2
ev_yield = 128
gender_probability = 127
egg_happiness = 10
base_happiness = 70
experience_group = 0
egg_groups = [5, 6]
escape_rate = 0
color = 2
base_experience = 105
height_cm = 4
weight_cg = 60

[personal.base_stats]
hp = 35
attack = 55
defense = 30
speed = 90
special_attack = 50
special_defense = 40

[personal.typing]
primary = "TYPE_ELECTRIC"
secondary = "TYPE_ELECTRIC"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_LIGHT_BALL"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 9
secondary = "BATTLE_ABILITY_RANDOM"
hidden = 31

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-845970912, 25270784, 845152672, 4]
type_tutors = 0
special_tutors = [4114, 65568, 6, 8208]
