[personal]
index = 32
species = "SPECIES_NIDORAN_F"
capture_rate = 235
evolution_stage = 1
ev_yield = 4
gender_probability = 0
egg_happiness = 20
base_happiness = 70
experience_group = 3
egg_groups = [1, 5]
escape_rate = 90
color = 6
base_experience = 55
height_cm = 5
weight_cg = 90

[personal.base_stats]
hp = 46
attack = 57
defense = 40
speed = 50
special_attack = 40
special_defense = 40

[personal.typing]
primary = "TYPE_POISON"
secondary = "TYPE_POISON"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 38
secondary = 79
hidden = 55

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-1919731935, 113160, -1572339711, 4]
type_tutors = 0
special_tutors = [132, 65536, 2, 8208]
