[personal]
index = 33
species = "SPECIES_NIDORINO"
capture_rate = 120
evolution_stage = 2
ev_yield = 8
gender_probability = 0
egg_happiness = 20
base_happiness = 70
experience_group = 3
egg_groups = [1, 5]
escape_rate = 60
color = 6
base_experience = 128
height_cm = 9
weight_cg = 195

[personal.base_stats]
hp = 61
attack = 72
defense = 57
speed = 65
special_attack = 55
special_defense = 55

[personal.typing]
primary = "TYPE_POISON"
secondary = "TYPE_POISON"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 38
secondary = 79
hidden = 55

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-1919731935, 113160, -1572339711, 4]
type_tutors = 0
special_tutors = [132, 65536, 2, 8208]
