[personal]
index = 34
species = "SPECIES_NIDOKING"
capture_rate = 45
evolution_stage = 3
ev_yield = 12
gender_probability = 0
egg_happiness = 20
base_happiness = 70
experience_group = 3
egg_groups = [1, 5]
escape_rate = 0
color = 6
base_experience = 223
height_cm = 14
weight_cg = 620

[personal.base_stats]
hp = 81
attack = 92
defense = 77
speed = 85
special_attack = 85
special_defense = 75

[personal.typing]
primary = "TYPE_POISON"
secondary = "TYPE_GROUND"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 38
secondary = 79
hidden = 125

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-271352015, 210353022, -1572167607, 6]
type_tutors = 0
special_tutors = [30852, 85252, 2, 12816]
