[personal]
index = 40
species = "SPECIES_WIGGLYTUFF"
capture_rate = 50
evolution_stage = 3
ev_yield = 3
gender_probability = 191
egg_happiness = 10
base_happiness = 70
experience_group = 4
egg_groups = [6, 6]
escape_rate = 0
color = 73
base_experience = 191
height_cm = 10
weight_cg = 120

[personal.base_stats]
hp = 140
attack = 70
defense = 45
speed = 45
special_attack = 75
special_defense = 50

[personal.typing]
primary = "TYPE_NORMAL"
secondary = "TYPE_NORMAL"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 56
secondary = "BATTLE_ABILITY_RANDOM"
hidden = 119

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-38013408, 92903973, 309596972, 4]
type_tutors = 0
special_tutors = [28930, 33937, 2662, 15696]
