[personal]
index = 45
species = "SPECIES_VILEPLUME"
capture_rate = 45
evolution_stage = 3
ev_yield = 768
gender_probability = 127
egg_happiness = 20
base_happiness = 70
experience_group = 3
egg_groups = [7, 7]
escape_rate = 0
color = 0
base_experience = 216
height_cm = 12
weight_cg = 186

[personal.base_stats]
hp = 75
attack = 80
defense = 85
speed = 50
special_attack = 100
special_defense = 90

[personal.typing]
primary = "TYPE_GRASS"
secondary = "TYPE_POISON"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 34
secondary = "BATTLE_ABILITY_RANDOM"
hidden = 27

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-2077145312, 9476616, -2107636696, 0]
type_tutors = 0
special_tutors = [64, 0, 3082, 8203]
