[personal]
index = 58
species = "SPECIES_GROWLITHE"
capture_rate = 190
evolution_stage = 1
ev_yield = 4
gender_probability = 63
egg_happiness = 20
base_happiness = 70
experience_group = 5
egg_groups = [5, 5]
escape_rate = 0
color = 5
base_experience = 70
height_cm = 7
weight_cg = 190

[personal.base_stats]
hp = 55
attack = 70
defense = 45
speed = 60
special_attack = 70
special_defense = 50

[personal.typing]
primary = "TYPE_FIRE"
secondary = "TYPE_FIRE"

[personal.wild_items]
common_50 = "ITEM_RAWST_BERRY"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 22
secondary = 18
hidden = 154

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-1944517072, 335724196, 1916796932, 4]
type_tutors = 0
special_tutors = [2, 65536, 18, 8720]
