[personal]
index = 67
species = "SPECIES_MACHOKE"
capture_rate = 90
evolution_stage = 2
ev_yield = 8
gender_probability = 63
egg_happiness = 20
base_happiness = 70
experience_group = 3
egg_groups = [8, 8]
escape_rate = 60
color = 71
base_experience = 142
height_cm = 15
weight_cg = 705

[personal.base_stats]
hp = 80
attack = 100
defense = 70
speed = 45
special_attack = 50
special_defense = 60

[personal.typing]
primary = "TYPE_FIGHTING"
secondary = "TYPE_FIGHTING"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 62
secondary = 99
hidden = 80

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-833386848, 76085860, 575447046, 4]
type_tutors = 0
special_tutors = [29192, 256, 38, 8208]
