[personal]
index = 70
species = "SPECIES_WEEPINBELL"
capture_rate = 120
evolution_stage = 2
ev_yield = 8
gender_probability = 127
egg_happiness = 20
base_happiness = 70
experience_group = 3
egg_groups = [7, 7]
escape_rate = 60
color = 3
base_experience = 137
height_cm = 10
weight_cg = 64

[personal.base_stats]
hp = 65
attack = 90
defense = 50
speed = 55
special_attack = 85
special_defense = 45

[personal.typing]
primary = "TYPE_GRASS"
secondary = "TYPE_POISON"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 34
secondary = "BATTLE_ABILITY_RANDOM"
hidden = 82

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-2077161696, 1096201, -2107636704, 0]
type_tutors = 0
special_tutors = [65, 0, 1039, 8195]
