[personal]
index = 72
species = "SPECIES_TENTACOOL"
capture_rate = 190
evolution_stage = 1
ev_yield = 1024
gender_probability = 127
egg_happiness = 20
base_happiness = 70
experience_group = 5
egg_groups = [9, 9]
escape_rate = 0
color = 1
base_experience = 67
height_cm = 9
weight_cg = 455

[personal.base_stats]
hp = 40
attack = 40
defense = 35
speed = 70
special_attack = 50
special_defense = 100

[personal.typing]
primary = "TYPE_WATER"
secondary = "TYPE_POISON"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_POISON_BARB"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 29
secondary = 64
hidden = 44

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-2078592160, 4241930, -2109209598, 26]
type_tutors = 0
special_tutors = [0, 1025, 1031, 8192]
