[personal]
index = 88
species = "SPECIES_GRIMER"
capture_rate = 190
evolution_stage = 1
ev_yield = 1
gender_probability = 127
egg_happiness = 20
base_happiness = 70
experience_group = 0
egg_groups = [11, 11]
escape_rate = 60
color = 6
base_experience = 65
height_cm = 9
weight_cg = 300

[personal.base_stats]
hp = 80
attack = 80
defense = 50
speed = 25
special_attack = 40
special_defense = 50

[personal.typing]
primary = "TYPE_POISON"
secondary = "TYPE_POISON"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_BLACK_SLUDGE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = "BATTLE_ABILITY_PRIMARY"
secondary = 60
hidden = 143

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-1382871264, -2071938194, 38305794, 4]
type_tutors = 0
special_tutors = [29696, 0, 1538, 8192]
