[personal]
index = 99
species = "SPECIES_KINGLER"
capture_rate = 60
evolution_stage = 2
ev_yield = 8
gender_probability = 127
egg_happiness = 20
base_happiness = 70
experience_group = 0
egg_groups = [9, 9]
escape_rate = 60
color = 64
base_experience = 166
height_cm = 13
weight_cg = 600

[personal.base_stats]
hp = 55
attack = 130
defense = 115
speed = 75
special_attack = 50
special_defense = 50

[personal.typing]
primary = "TYPE_WATER"
secondary = "TYPE_WATER"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 52
secondary = 75
hidden = 125

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-871140767, 148945472, -1572764664, 22]
type_tutors = 0
special_tutors = [0, 1344, 6, 8192]
