[personal]
index = 100
species = "SPECIES_VOLTORB"
capture_rate = 190
evolution_stage = 1
ev_yield = 64
gender_probability = 255
egg_happiness = 20
base_happiness = 70
experience_group = 0
egg_groups = [10, 10]
escape_rate = 120
color = 0
base_experience = 66
height_cm = 5
weight_cg = 104

[personal.base_stats]
hp = 40
attack = 30
defense = 50
speed = 100
special_attack = 55
special_defense = 55

[personal.typing]
primary = "TYPE_ELECTRIC"
secondary = "TYPE_ELECTRIC"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 43
secondary = 9
hidden = 106

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-2053928416, -2130662656, 306185120, 0]
type_tutors = 0
special_tutors = [16, 41, 2, 8192]
