[personal]
index = 108
species = "SPECIES_LICKITUNG"
capture_rate = 45
evolution_stage = 1
ev_yield = 2
gender_probability = 127
egg_happiness = 20
base_happiness = 70
experience_group = 0
egg_groups = [1, 1]
escape_rate = 60
color = 9
base_experience = 77
height_cm = 12
weight_cg = 655

[personal.base_stats]
hp = 90
attack = 55
defense = 75
speed = 30
special_attack = 60
special_defense = 75

[personal.typing]
primary = "TYPE_NORMAL"
secondary = "TYPE_NORMAL"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_LAGGING_TAIL"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 20
secondary = 12
hidden = 13

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-273451488, 75545204, -1571376116, 6]
type_tutors = 0
special_tutors = [28672, 76800, 7, 8192]
