[personal]
index = 122
species = "SPECIES_MR_MIME"
capture_rate = 45
evolution_stage = 2
ev_yield = 2048
gender_probability = 127
egg_happiness = 25
base_happiness = 70
experience_group = 0
egg_groups = [8, 8]
escape_rate = 90
color = 9
base_experience = 161
height_cm = 13
weight_cg = 545

[personal.base_stats]
hp = 40
attack = 45
defense = 65
speed = 90
special_attack = 100
special_defense = 120

[personal.typing]
primary = "TYPE_PSYCHIC"
secondary = "TYPE_PSYCHIC"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 43
secondary = 111
hidden = 101

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-171979220, 26786689, 175116586, 0]
type_tutors = 0
special_tutors = [28690, 9289, 2082, 27888]
