[personal]
index = 125
species = "SPECIES_ELECTABUZZ"
capture_rate = 45
evolution_stage = 2
ev_yield = 128
gender_probability = 63
egg_happiness = 25
base_happiness = 70
experience_group = 0
egg_groups = [8, 8]
escape_rate = 120
color = 66
base_experience = 172
height_cm = 11
weight_cg = 300

[personal.base_stats]
hp = 65
attack = 83
defense = 57
speed = 105
special_attack = 95
special_defense = 85

[personal.typing]
primary = "TYPE_ELECTRIC"
secondary = "TYPE_ELECTRIC"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 9
secondary = "BATTLE_ABILITY_RANDOM"
hidden = 72

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-711736800, 25754112, 843055528, 4]
type_tutors = 0
special_tutors = [29210, 66080, 2, 8208]
