[personal]
index = 127
species = "SPECIES_PINSIR"
capture_rate = 45
evolution_stage = 2
ev_yield = 8
gender_probability = 127
egg_happiness = 25
base_happiness = 70
experience_group = 5
egg_groups = [3, 3]
escape_rate = 0
color = 5
base_experience = 175
height_cm = 15
weight_cg = 550

[personal.base_stats]
hp = 65
attack = 125
defense = 100
speed = 85
special_attack = 55
special_defense = 70

[personal.typing]
primary = "TYPE_BUG"
secondary = "TYPE_BUG"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 52
secondary = 104
hidden = 153

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-833403232, 11057728, -1572754360, 4]
type_tutors = 0
special_tutors = [1, 320, 7, 12288]
