[personal]
index = 132
species = "SPECIES_DITTO"
capture_rate = 35
evolution_stage = 2
ev_yield = 1
gender_probability = 255
egg_happiness = 20
base_happiness = 70
experience_group = 0
egg_groups = [13, 13]
escape_rate = 90
color = 6
base_experience = 101
height_cm = 3
weight_cg = 40

[personal.base_stats]
hp = 48
attack = 48
defense = 48
speed = 48
special_attack = 48
special_defense = 48

[personal.typing]
primary = "TYPE_NORMAL"
secondary = "TYPE_NORMAL"

[personal.wild_items]
common_50 = "ITEM_QUICK_POWDER"
rare_5 = "ITEM_METAL_POWDER"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 7
secondary = "BATTLE_ABILITY_RANDOM"
hidden = 150

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [0, 0, 0, 0]
type_tutors = 0
special_tutors = [0, 0, 0, 0]
