[personal]
index = 133
species = "SPECIES_EEVEE"
capture_rate = 45
evolution_stage = 1
ev_yield = 1024
gender_probability = 31
egg_happiness = 35
base_happiness = 70
experience_group = 0
egg_groups = [5, 5]
escape_rate = 0
color = 5
base_experience = 65
height_cm = 3
weight_cg = 65

[personal.base_stats]
hp = 55
attack = 55
defense = 50
speed = 55
special_attack = 45
special_defense = 65

[personal.typing]
primary = "TYPE_NORMAL"
secondary = "TYPE_NORMAL"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 50
secondary = 91
hidden = 107

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-1408039392, 104960, 38010884, 0]
type_tutors = 0
special_tutors = [2, 98432, 66, 8208]
