[personal]
index = 134
species = "SPECIES_VAPOREON"
capture_rate = 45
evolution_stage = 2
ev_yield = 2
gender_probability = 31
egg_happiness = 35
base_happiness = 70
experience_group = 0
egg_groups = [5, 5]
escape_rate = 0
color = 1
base_experience = 184
height_cm = 10
weight_cg = 290

[personal.base_stats]
hp = 130
attack = 65
defense = 60
speed = 65
special_attack = 110
special_defense = 95

[personal.typing]
primary = "TYPE_WATER"
secondary = "TYPE_WATER"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 11
secondary = 11
hidden = 93

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-1408010640, 4299264, 574881804, 30]
type_tutors = 0
special_tutors = [18, 101504, 66, 8208]
