[personal]
index = 140
species = "SPECIES_KABUTO"
capture_rate = 45
evolution_stage = 1
ev_yield = 16
gender_probability = 31
egg_happiness = 30
base_happiness = 70
experience_group = 0
egg_groups = [2, 9]
escape_rate = 0
color = 5
base_experience = 71
height_cm = 5
weight_cg = 115

[personal.base_stats]
hp = 30
attack = 80
defense = 90
speed = 55
special_attack = 55
special_defense = 45

[personal.typing]
primary = "TYPE_ROCK"
secondary = "TYPE_WATER"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 33
secondary = 4
hidden = 133

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-1940704671, 4242000, 574652432, 10]
type_tutors = 0
special_tutors = [0, 1092, 1030, 12288]
