[personal]
index = 148
species = "SPECIES_DRAGONAIR"
capture_rate = 45
evolution_stage = 2
ev_yield = 8
gender_probability = 127
egg_happiness = 40
base_happiness = 35
experience_group = 5
egg_groups = [2, 14]
escape_rate = 90
color = 1
base_experience = 147
height_cm = 40
weight_cg = 165

[personal.base_stats]
hp = 61
attack = 84
defense = 65
speed = 70
special_attack = 70
special_defense = 70

[personal.typing]
primary = "TYPE_DRAGON"
secondary = "TYPE_DRAGON"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_DRAGON_SCALE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 61
secondary = "BATTLE_ABILITY_RANDOM"
hidden = 63

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-2053376416, 67148324, 37880064, 10]
type_tutors = 64
special_tutors = [0, 84992, 3, 8704]
