[personal]
index = 150
species = "SPECIES_MEWTWO"
capture_rate = 3
evolution_stage = 3
ev_yield = 768
gender_probability = 255
egg_happiness = 120
base_happiness = 0
experience_group = 5
egg_groups = [15, 15]
escape_rate = 0
color = 6
base_experience = 306
height_cm = 20
weight_cg = 1220

[personal.base_stats]
hp = 106
attack = 110
defense = 90
speed = 130
special_attack = 154
special_defense = 90

[personal.typing]
primary = "TYPE_PSYCHIC"
secondary = "TYPE_PSYCHIC"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 46
secondary = "BATTLE_ABILITY_RANDOM"
hidden = 127

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-138412308, 1436077045, 712552808, 4]
type_tutors = 0
special_tutors = [29200, 76825, 2082, 27872]
