[personal]
index = 156
species = "SPECIES_QUILAVA"
capture_rate = 45
evolution_stage = 2
ev_yield = 320
gender_probability = 31
egg_happiness = 20
base_happiness = 70
experience_group = 3
egg_groups = [5, 5]
escape_rate = 0
color = 2
base_experience = 142
height_cm = 9
weight_cg = 190

[personal.base_stats]
hp = 58
attack = 64
defense = 58
speed = 80
special_attack = 80
special_defense = 65

[personal.typing]
primary = "TYPE_FIRE"
secondary = "TYPE_FIRE"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 66
secondary = "BATTLE_ABILITY_RANDOM"
hidden = 18

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-871299536, 335716004, -1304428544, 4]
type_tutors = 2
special_tutors = [2, 0, 18, 8192]
