[personal]
index = 176
species = "SPECIES_TOGETIC"
capture_rate = 75
evolution_stage = 2
ev_yield = 2048
gender_probability = 31
egg_happiness = 10
base_happiness = 70
experience_group = 4
egg_groups = [4, 6]
escape_rate = 0
color = 8
base_experience = 142
height_cm = 6
weight_cg = 32

[personal.base_stats]
hp = 55
attack = 40
defense = 85
speed = 40
special_attack = 80
special_defense = 105

[personal.typing]
primary = "TYPE_NORMAL"
secondary = "TYPE_FLYING"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 55
secondary = 32
hidden = 105

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-197147100, 75602597, 578031916, 1]
type_tutors = 0
special_tutors = [18, 41089, 6354, 8488]
