[personal]
index = 193
species = "SPECIES_YANMA"
capture_rate = 75
evolution_stage = 1
ev_yield = 64
gender_probability = 127
egg_happiness = 20
base_happiness = 70
experience_group = 0
egg_groups = [3, 3]
escape_rate = 120
color = 0
base_experience = 78
height_cm = 12
weight_cg = 380

[personal.base_stats]
hp = 65
attack = 65
defense = 45
speed = 95
special_attack = 75
special_defense = 45

[personal.typing]
primary = "TYPE_BUG"
secondary = "TYPE_FLYING"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_WIDE_LENS"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = "BATTLE_ABILITY_HIDDEN"
secondary = 14
hidden = 119

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-1271855584, 47744, 55574560, 0]
type_tutors = 0
special_tutors = [2065, 0, 5250, 8192]
