[personal]
index = 197
species = "SPECIES_UMBREON"
capture_rate = 45
evolution_stage = 2
ev_yield = 2048
gender_probability = 31
egg_happiness = 35
base_happiness = 35
experience_group = 0
egg_groups = [5, 5]
escape_rate = 0
color = 4
base_experience = 184
height_cm = 10
weight_cg = 270

[personal.base_stats]
hp = 95
attack = 65
defense = 110
speed = 65
special_attack = 60
special_defense = 130

[personal.typing]
primary = "TYPE_DARK"
secondary = "TYPE_DARK"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 28
secondary = 28
hidden = 39

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-1139585504, 105216, -1034678226, 0]
type_tutors = 0
special_tutors = [2, 102536, 66, 10388]
