[personal]
index = 220
species = "SPECIES_SWINUB"
capture_rate = 225
evolution_stage = 1
ev_yield = 4
gender_probability = 127
egg_happiness = 20
base_happiness = 70
experience_group = 5
egg_groups = [5, 5]
escape_rate = 0
color = 5
base_experience = 50
height_cm = 4
weight_cg = 65

[personal.base_stats]
hp = 50
attack = 50
defense = 40
speed = 50
special_attack = 30
special_defense = 30

[personal.typing]
primary = "TYPE_ICE"
secondary = "TYPE_GROUND"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 12
secondary = 81
hidden = 47

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-1911311760, 39505, 574660608, 4]
type_tutors = 0
special_tutors = [0, 1284, 2, 12544]
