[personal]
index = 224
species = "SPECIES_OCTILLERY"
capture_rate = 75
evolution_stage = 2
ev_yield = 260
gender_probability = 127
egg_happiness = 20
base_happiness = 70
experience_group = 0
egg_groups = [2, 12]
escape_rate = 0
color = 0
base_experience = 168
height_cm = 9
weight_cg = 285

[personal.base_stats]
hp = 75
attack = 105
defense = 75
speed = 45
special_attack = 105
special_defense = 75

[personal.typing]
primary = "TYPE_WATER"
secondary = "TYPE_WATER"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 21
secondary = 97
hidden = 141

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-1806469600, 89176622, 104857866, 26]
type_tutors = 0
special_tutors = [1360, 1024, 3, 8192]
