[personal]
index = 241
species = "SPECIES_MILTANK"
capture_rate = 45
evolution_stage = 2
ev_yield = 32
gender_probability = 254
egg_happiness = 20
base_happiness = 70
experience_group = 5
egg_groups = [5, 5]
escape_rate = 0
color = 9
base_experience = 172
height_cm = 12
weight_cg = 755

[personal.base_stats]
hp = 95
attack = 80
defense = 105
speed = 100
special_attack = 40
special_defense = 70

[personal.typing]
primary = "TYPE_NORMAL"
secondary = "TYPE_NORMAL"

[personal.wild_items]
common_50 = "ITEM_MOOMOO_MILK"
rare_5 = "ITEM_MOOMOO_MILK"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 47
secondary = 113
hidden = 157

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-407669216, 9017936, 574927628, 6]
type_tutors = 0
special_tutors = [28704, 74754, 66, 12312]
