[personal]
index = 242
species = "SPECIES_BLISSEY"
capture_rate = 30
evolution_stage = 3
ev_yield = 3
gender_probability = 254
egg_happiness = 40
base_happiness = 140
experience_group = 4
egg_groups = [6, 6]
escape_rate = 0
color = 9
base_experience = 608
height_cm = 15
weight_cg = 468

[personal.base_stats]
hp = 255
attack = 10
defense = 10
speed = 55
special_attack = 75
special_defense = 135

[personal.typing]
primary = "TYPE_NORMAL"
secondary = "TYPE_NORMAL"

[personal.wild_items]
common_50 = "ITEM_LUCKY_EGG"
rare_5 = "ITEM_LUCKY_EGG"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 30
secondary = 32
hidden = 131

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-138676632, 92904052, 846508332, 4]
type_tutors = 0
special_tutors = [28674, 107666, 2114, 32016]
