[personal]
index = 247
species = "SPECIES_PUPITAR"
capture_rate = 45
evolution_stage = 2
ev_yield = 8
gender_probability = 127
egg_happiness = 40
base_happiness = 35
experience_group = 5
egg_groups = [1, 1]
escape_rate = 0
color = 7
base_experience = 144
height_cm = 12
weight_cg = 1520

[personal.base_stats]
hp = 70
attack = 84
defense = 70
speed = 51
special_attack = 65
special_defense = 70

[personal.typing]
primary = "TYPE_ROCK"
secondary = "TYPE_GROUND"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 61
secondary = "BATTLE_ABILITY_RANDOM"
hidden = 61

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-833401312, 39760, 1648402518, 0]
type_tutors = 0
special_tutors = [2080, 69956, 2, 12804]
