[personal]
index = 262
species = "SPECIES_MIGHTYENA"
capture_rate = 127
evolution_stage = 2
ev_yield = 8
gender_probability = 127
egg_happiness = 15
base_happiness = 70
experience_group = 0
egg_groups = [5, 5]
escape_rate = 0
color = 7
base_experience = 147
height_cm = 10
weight_cg = 370

[personal.base_stats]
hp = 70
attack = 90
defense = 70
speed = 70
special_attack = 60
special_defense = 60

[personal.typing]
primary = "TYPE_DARK"
secondary = "TYPE_DARK"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_PECHA_BERRY"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 22
secondary = 95
hidden = 153

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-1408020944, 1140898560, 1648361486, 4]
type_tutors = 0
special_tutors = [2054, 102408, 2, 10244]
