[personal]
index = 267
species = "SPECIES_BEAUTIFLY"
capture_rate = 45
evolution_stage = 3
ev_yield = 768
gender_probability = 127
egg_happiness = 15
base_happiness = 70
experience_group = 0
egg_groups = [3, 3]
escape_rate = 0
color = 2
base_experience = 173
height_cm = 10
weight_cg = 284

[personal.base_stats]
hp = 60
attack = 70
defense = 50
speed = 65
special_attack = 90
special_defense = 50

[personal.typing]
primary = "TYPE_BUG"
secondary = "TYPE_FLYING"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_SHED_SHELL"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 68
secondary = "BATTLE_ABILITY_RANDOM"
hidden = 79

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-1271314656, 537967232, 54528040, 0]
type_tutors = 0
special_tutors = [17, 512, 5250, 8192]
