[personal]
index = 272
species = "SPECIES_LUDICOLO"
capture_rate = 45
evolution_stage = 3
ev_yield = 3072
gender_probability = 127
egg_happiness = 15
base_happiness = 70
experience_group = 3
egg_groups = [2, 7]
escape_rate = 0
color = 3
base_experience = 216
height_cm = 15
weight_cg = 550

[personal.base_stats]
hp = 80
attack = 70
defense = 70
speed = 70
special_attack = 90
special_defense = 100

[personal.typing]
primary = "TYPE_WATER"
secondary = "TYPE_GRASS"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 33
secondary = 44
hidden = 20

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-1003260319, 14268928, 576717864, 30]
type_tutors = 0
special_tutors = [30784, 41984, 3082, 8192]
