[personal]
index = 282
species = "SPECIES_GARDEVOIR"
capture_rate = 45
evolution_stage = 3
ev_yield = 768
gender_probability = 127
egg_happiness = 20
base_happiness = 35
experience_group = 5
egg_groups = [11, 11]
escape_rate = 0
color = 8
base_experience = 233
height_cm = 16
weight_cg = 484

[personal.base_stats]
hp = 68
attack = 65
defense = 65
speed = 80
special_attack = 125
special_defense = 115

[personal.typing]
primary = "TYPE_PSYCHIC"
secondary = "TYPE_PSYCHIC"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 28
secondary = 36
hidden = 140

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-1264595412, 295549697, 175116584, 0]
type_tutors = 0
special_tutors = [28688, 41985, 578, 27888]
