[personal]
index = 293
species = "SPECIES_WHISMUR"
capture_rate = 190
evolution_stage = 1
ev_yield = 1
gender_probability = 127
egg_happiness = 20
base_happiness = 70
experience_group = 3
egg_groups = [1, 5]
escape_rate = 0
color = 9
base_experience = 48
height_cm = 6
weight_cg = 163

[personal.base_stats]
hp = 64
attack = 51
defense = 23
speed = 28
special_attack = 51
special_defense = 23

[personal.typing]
primary = "TYPE_NORMAL"
secondary = "TYPE_NORMAL"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_CHESTO_BERRY"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 43
secondary = "BATTLE_ABILITY_RANDOM"
hidden = 155

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-1540147664, 75602468, 38010884, 0]
type_tutors = 0
special_tutors = [30720, 41984, 2, 8448]
