[personal]
index = 323
species = "SPECIES_CAMERUPT"
capture_rate = 150
evolution_stage = 2
ev_yield = 260
gender_probability = 127
egg_happiness = 20
base_happiness = 70
experience_group = 0
egg_groups = [5, 5]
escape_rate = 0
color = 0
base_experience = 161
height_cm = 19
weight_cg = 2200

[personal.base_stats]
hp = 70
attack = 100
defense = 70
speed = 40
special_attack = 105
special_defense = 75

[personal.typing]
primary = "TYPE_FIRE"
secondary = "TYPE_GROUND"

[personal.wild_items]
common_50 = "ITEM_RAWST_BERRY"
rare_5 = "ITEM_RAWST_BERRY"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 40
secondary = 116
hidden = 83

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-1909373392, -1811702156, 641769560, 4]
type_tutors = 0
special_tutors = [32, 4, 18, 12296]
