[personal]
index = 328
species = "SPECIES_TRAPINCH"
capture_rate = 255
evolution_stage = 1
ev_yield = 4
gender_probability = 127
egg_happiness = 20
base_happiness = 70
experience_group = 3
egg_groups = [3, 3]
escape_rate = 120
color = 5
base_experience = 58
height_cm = 7
weight_cg = 150

[personal.base_stats]
hp = 45
attack = 100
defense = 45
speed = 10
special_attack = 45
special_defense = 45

[personal.typing]
primary = "TYPE_GROUND"
secondary = "TYPE_GROUND"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_SOFT_SAND"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 52
secondary = 71
hidden = 125

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-1909373408, 39504, 574662656, 4]
type_tutors = 0
special_tutors = [17, 260, 1026, 8192]
