[personal]
index = 329
species = "SPECIES_VIBRAVA"
capture_rate = 120
evolution_stage = 2
ev_yield = 68
gender_probability = 127
egg_happiness = 20
base_happiness = 70
experience_group = 3
egg_groups = [3, 3]
escape_rate = 90
color = 3
base_experience = 119
height_cm = 11
weight_cg = 153

[personal.base_stats]
hp = 50
attack = 70
defense = 50
speed = 70
special_attack = 50
special_defense = 50

[personal.typing]
primary = "TYPE_GROUND"
secondary = "TYPE_DRAGON"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 26
secondary = 26
hidden = 26

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-1909373408, 39504, 591439872, 5]
type_tutors = 64
special_tutors = [17, 16644, 5266, 8704]
