[personal]
index = 335
species = "SPECIES_ZANGOOSE"
capture_rate = 90
evolution_stage = 2
ev_yield = 8
gender_probability = 127
egg_happiness = 20
base_happiness = 70
experience_group = 1
egg_groups = [5, 5]
escape_rate = 90
color = 72
base_experience = 160
height_cm = 13
weight_cg = 403

[personal.base_stats]
hp = 73
attack = 115
defense = 60
speed = 90
special_attack = 60
special_defense = 60

[personal.typing]
primary = "TYPE_NORMAL"
secondary = "TYPE_NORMAL"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_QUICK_CLAW"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 17
secondary = "BATTLE_ABILITY_RANDOM"
hidden = 137

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-307020239, 1151908580, 575505415, 4]
type_tutors = 0
special_tutors = [29184, 66688, 1030, 8448]
