[personal]
index = 342
species = "SPECIES_CRAWDAUNT"
capture_rate = 155
evolution_stage = 2
ev_yield = 8
gender_probability = 127
egg_happiness = 15
base_happiness = 70
experience_group = 2
egg_groups = [2, 9]
escape_rate = 0
color = 0
base_experience = 164
height_cm = 11
weight_cg = 328

[personal.base_stats]
hp = 63
attack = 120
defense = 85
speed = 55
special_attack = 90
special_defense = 55

[personal.typing]
primary = "TYPE_WATER"
secondary = "TYPE_DARK"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 52
secondary = 75
hidden = 91

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-871138719, 14719690, -499022834, 30]
type_tutors = 0
special_tutors = [0, 5440, 6, 8452]
