[personal]
index = 345
species = "SPECIES_LILEEP"
capture_rate = 45
evolution_stage = 1
ev_yield = 1024
gender_probability = 31
egg_happiness = 30
base_happiness = 70
experience_group = 1
egg_groups = [9, 9]
escape_rate = 0
color = 6
base_experience = 71
height_cm = 10
weight_cg = 238

[personal.base_stats]
hp = 66
attack = 41
defense = 77
speed = 23
special_attack = 61
special_defense = 87

[personal.typing]
primary = "TYPE_ROCK"
secondary = "TYPE_GRASS"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_BIG_ROOT"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 21
secondary = "BATTLE_ABILITY_RANDOM"
hidden = 114

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-2072967648, 1088088, 39879728, 0]
type_tutors = 0
special_tutors = [64, 4, 1547, 12291]
