[personal]
index = 352
species = "SPECIES_KECLEON"
capture_rate = 200
evolution_stage = 2
ev_yield = 1024
gender_probability = 127
egg_happiness = 20
base_happiness = 70
experience_group = 3
egg_groups = [5, 5]
escape_rate = 120
color = 3
base_experience = 154
height_cm = 10
weight_cg = 220

[personal.base_stats]
hp = 60
attack = 90
defense = 70
speed = 40
special_attack = 60
special_defense = 120

[personal.typing]
primary = "TYPE_NORMAL"
secondary = "TYPE_NORMAL"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_PERSIM_BERRY"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 16
secondary = "BATTLE_ABILITY_RANDOM"
hidden = "BATTLE_ABILITY_RANDOM"

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-307022303, 92322532, -1436249819, 4]
type_tutors = 0
special_tutors = [29184, 68745, 2087, 31912]
