[personal]
index = 354
species = "SPECIES_BANETTE"
capture_rate = 45
evolution_stage = 2
ev_yield = 8
gender_probability = 127
egg_happiness = 25
base_happiness = 35
experience_group = 4
egg_groups = [11, 11]
escape_rate = 90
color = 4
base_experience = 159
height_cm = 11
weight_cg = 125

[personal.base_stats]
hp = 64
attack = 115
defense = 65
speed = 65
special_attack = 83
special_defense = 63

[personal.typing]
primary = "TYPE_GHOST"
secondary = "TYPE_GHOST"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_SPELL_TAG"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 15
secondary = 119
hidden = 130

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-1248375256, 1367390976, 173019435, 0]
type_tutors = 0
special_tutors = [0, 5129, 548, 26724]
