[personal]
index = 357
species = "SPECIES_TROPIUS"
capture_rate = 200
evolution_stage = 2
ev_yield = 2
gender_probability = 127
egg_happiness = 25
base_happiness = 70
experience_group = 5
egg_groups = [1, 7]
escape_rate = 60
color = 3
base_experience = 161
height_cm = 20
weight_cg = 1000

[personal.base_stats]
hp = 99
attack = 68
defense = 83
speed = 51
special_attack = 72
special_defense = 87

[personal.typing]
primary = "TYPE_GRASS"
secondary = "TYPE_FLYING"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 34
secondary = 94
hidden = 139

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-2043066832, 1088128, -1570757592, 5]
type_tutors = 0
special_tutors = [64, 16384, 5258, 8706]
