[personal]
index = 365
species = "SPECIES_WALREIN"
capture_rate = 45
evolution_stage = 3
ev_yield = 3
gender_probability = 127
egg_happiness = 20
base_happiness = 70
experience_group = 3
egg_groups = [2, 5]
escape_rate = 0
color = 1
base_experience = 239
height_cm = 14
weight_cg = 1506

[personal.base_stats]
hp = 110
attack = 80
defense = 90
speed = 65
special_attack = 95
special_defense = 90

[personal.typing]
primary = "TYPE_ICE"
secondary = "TYPE_WATER"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 47
secondary = 115
hidden = 12

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-2045545872, 105024, 574677000, 30]
type_tutors = 0
special_tutors = [52, 68610, 2, 8192]
