[personal]
index = 369
species = "SPECIES_RELICANTH"
capture_rate = 25
evolution_stage = 2
ev_yield = 17
gender_probability = 31
egg_happiness = 40
base_happiness = 70
experience_group = 5
egg_groups = [2, 12]
escape_rate = 0
color = 7
base_experience = 170
height_cm = 10
weight_cg = 234

[personal.base_stats]
hp = 100
attack = 90
defense = 130
speed = 55
special_attack = 45
special_defense = 65

[personal.typing]
primary = "TYPE_WATER"
secondary = "TYPE_ROCK"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_DEEP_SEA_SCALE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 33
secondary = 69
hidden = 5

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-2040827288, 4233808, 574664792, 26]
type_tutors = 0
special_tutors = [256, 11268, 2, 12288]
