[personal]
index = 373
species = "SPECIES_SALAMENCE"
capture_rate = 45
evolution_stage = 3
ev_yield = 12
gender_probability = 127
egg_happiness = 40
base_happiness = 35
experience_group = 5
egg_groups = [14, 14]
escape_rate = 0
color = 1
base_experience = 270
height_cm = 15
weight_cg = 1026

[personal.base_stats]
hp = 95
attack = 135
defense = 80
speed = 100
special_attack = 110
special_defense = 80

[personal.typing]
primary = "TYPE_DRAGON"
secondary = "TYPE_FLYING"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_DRAGON_FANG"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 22
secondary = "BATTLE_ABILITY_RANDOM"
hidden = 153

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-971815373, 67148516, -1572691895, 5]
type_tutors = 64
special_tutors = [0, 124928, 4242, 8704]
