[personal]
index = 376
species = "SPECIES_METAGROSS"
capture_rate = 3
evolution_stage = 3
ev_yield = 48
gender_probability = 255
egg_happiness = 40
base_happiness = 35
experience_group = 5
egg_groups = [10, 10]
escape_rate = 0
color = 1
base_experience = 270
height_cm = 16
weight_cg = 5500

[personal.base_stats]
hp = 80
attack = 135
defense = 130
speed = 70
special_attack = 95
special_defense = 90

[personal.typing]
primary = "TYPE_STEEL"
secondary = "TYPE_PSYCHIC"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_METAL_COAT"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 29
secondary = "BATTLE_ABILITY_RANDOM"
hidden = 135

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-166214107, -2147448103, -1503612360, 4]
type_tutors = 0
special_tutors = [20528, 9330, 2, 12320]
