[personal]
index = 384
species = "SPECIES_RAYQUAZA"
capture_rate = 3
evolution_stage = 3
ev_yield = 264
gender_probability = 255
egg_happiness = 120
base_happiness = 0
experience_group = 5
egg_groups = [15, 15]
escape_rate = 0
color = 3
base_experience = 306
height_cm = 70
weight_cg = 2065

[personal.base_stats]
hp = 105
attack = 150
defense = 90
speed = 95
special_attack = 150
special_defense = 90

[personal.typing]
primary = "TYPE_DRAGON"
secondary = "TYPE_FLYING"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 76
secondary = "BATTLE_ABILITY_RANDOM"
hidden = "BATTLE_ABILITY_RANDOM"

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-944539981, 110856948, 574797641, 31]
type_tutors = 64
special_tutors = [2080, 117764, 131, 8704]
