[personal]
index = 389
species = "SPECIES_TORTERRA"
capture_rate = 45
evolution_stage = 3
ev_yield = 24
gender_probability = 31
egg_happiness = 20
base_happiness = 70
experience_group = 3
egg_groups = [1, 7]
escape_rate = 0
color = 67
base_experience = 236
height_cm = 22
weight_cg = 3100

[personal.base_stats]
hp = 95
attack = 109
defense = 105
speed = 56
special_attack = 75
special_defense = 85

[personal.typing]
primary = "TYPE_GRASS"
secondary = "TYPE_GROUND"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 65
secondary = "BATTLE_ABILITY_RANDOM"
hidden = 75

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-2043034064, 1088081, -1570724744, 4]
type_tutors = 9
special_tutors = [96, 65798, 1034, 12802]
