[personal]
index = 390
species = "SPECIES_CHIMCHAR"
capture_rate = 45
evolution_stage = 1
ev_yield = 64
gender_probability = 31
egg_happiness = 20
base_happiness = 70
experience_group = 3
egg_groups = [5, 8]
escape_rate = 0
color = 69
base_experience = 62
height_cm = 5
weight_cg = 62

[personal.base_stats]
hp = 44
attack = 58
defense = 44
speed = 61
special_attack = 58
special_defense = 44

[personal.typing]
primary = "TYPE_FIRE"
secondary = "TYPE_FIRE"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 66
secondary = "BATTLE_ABILITY_RANDOM"
hidden = 89

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-871297375, 880992164, -1553988607, 4]
type_tutors = 2
special_tutors = [15874, 65536, 50, 12560]
