[personal]
index = 407
species = "SPECIES_ROSERADE"
capture_rate = 75
evolution_stage = 3
ev_yield = 768
gender_probability = 127
egg_happiness = 20
base_happiness = 70
experience_group = 3
egg_groups = [6, 7]
escape_rate = 0
color = 67
base_experience = 227
height_cm = 9
weight_cg = 145

[personal.base_stats]
hp = 60
attack = 70
defense = 55
speed = 90
special_attack = 125
special_defense = 105

[personal.typing]
primary = "TYPE_GRASS"
secondary = "TYPE_POISON"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_POISON_BARB"
rare_1 = "ITEM_ABSORB_BULB"

[personal.abilities]
primary = 30
secondary = 38
hidden = 101

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-1540143328, 1088008, -2107108312, 0]
type_tutors = 0
special_tutors = [66, 0, 1034, 8194]
