[personal]
index = 428
species = "SPECIES_LOPUNNY"
capture_rate = 60
evolution_stage = 2
ev_yield = 128
gender_probability = 127
egg_happiness = 20
base_happiness = 140
experience_group = 0
egg_groups = [5, 8]
escape_rate = 0
color = 5
base_experience = 168
height_cm = 12
weight_cg = 333

[personal.base_stats]
hp = 65
attack = 76
defense = 84
speed = 105
special_attack = 54
special_defense = 96

[personal.typing]
primary = "TYPE_NORMAL"
secondary = "TYPE_NORMAL"

[personal.wild_items]
common_50 = "ITEM_PECHA_BERRY"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 56
secondary = 103
hidden = 7

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-1380747744, 25745920, -1570504436, 4]
type_tutors = 0
special_tutors = [31490, 98433, 2114, 8472]
