[personal]
index = 435
species = "SPECIES_SKUNTANK"
capture_rate = 60
evolution_stage = 2
ev_yield = 2
gender_probability = 127
egg_happiness = 20
base_happiness = 70
experience_group = 0
egg_groups = [5, 5]
escape_rate = 0
color = 6
base_experience = 168
height_cm = 10
weight_cg = 380

[personal.base_stats]
hp = 103
attack = 93
defense = 67
speed = 84
special_attack = 71
special_defense = 61

[personal.typing]
primary = "TYPE_POISON"
secondary = "TYPE_DARK"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_PECHA_BERRY"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = "BATTLE_ABILITY_PRIMARY"
secondary = 106
hidden = 51

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-1408020687, -2080326868, -498597877, 4]
type_tutors = 0
special_tutors = [0, 69640, 2, 10240]
