[personal]
index = 436
species = "SPECIES_BRONZOR"
capture_rate = 255
evolution_stage = 1
ev_yield = 16
gender_probability = 255
egg_happiness = 20
base_happiness = 70
experience_group = 0
egg_groups = [10, 10]
escape_rate = 90
color = 3
base_experience = 60
height_cm = 5
weight_cg = 605

[personal.base_stats]
hp = 57
attack = 24
defense = 86
speed = 23
special_attack = 24
special_defense = 86

[personal.typing]
primary = "TYPE_STEEL"
secondary = "TYPE_PSYCHIC"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_METAL_COAT"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 26
secondary = 85
hidden = 134

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-1237350868, 16812625, 242266674, 0]
type_tutors = 0
special_tutors = [16, 80, 2, 29856]
