[personal]
index = 437
species = "SPECIES_BRONZONG"
capture_rate = 90
evolution_stage = 2
ev_yield = 1040
gender_probability = 255
egg_happiness = 20
base_happiness = 70
experience_group = 0
egg_groups = [10, 10]
escape_rate = 60
color = 3
base_experience = 175
height_cm = 13
weight_cg = 1870

[personal.base_stats]
hp = 67
attack = 89
defense = 116
speed = 33
special_attack = 79
special_defense = 116

[personal.typing]
primary = "TYPE_STEEL"
secondary = "TYPE_PSYCHIC"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_METAL_COAT"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 26
secondary = 85
hidden = 134

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-1237334484, -2130671023, 779137594, 4]
type_tutors = 0
special_tutors = [48, 8274, 2, 29856]
