[personal]
index = 452
species = "SPECIES_DRAPION"
capture_rate = 45
evolution_stage = 2
ev_yield = 32
gender_probability = 127
egg_happiness = 20
base_happiness = 70
experience_group = 5
egg_groups = [3, 9]
escape_rate = 60
color = 6
base_experience = 175
height_cm = 13
weight_cg = 615

[personal.base_stats]
hp = 70
attack = 90
defense = 110
speed = 95
special_attack = 60
special_defense = 75

[personal.typing]
primary = "TYPE_POISON"
secondary = "TYPE_DARK"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_POISON_BARB"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 4
secondary = 97
hidden = 51

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-300724431, 10533832, -498488274, 4]
type_tutors = 0
special_tutors = [1, 71680, 6, 8192]
