[personal]
index = 457
species = "SPECIES_LUMINEON"
capture_rate = 75
evolution_stage = 2
ev_yield = 128
gender_probability = 127
egg_happiness = 20
base_happiness = 70
experience_group = 1
egg_groups = [12, 12]
escape_rate = 0
color = 1
base_experience = 161
height_cm = 12
weight_cg = 240

[personal.base_stats]
hp = 69
attack = 69
defense = 76
speed = 91
special_attack = 69
special_defense = 86

[personal.typing]
primary = "TYPE_WATER"
secondary = "TYPE_WATER"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_RINDO_BERRY"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 33
secondary = 114
hidden = 41

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-2078576032, 4233728, 54530090, 26]
type_tutors = 0
special_tutors = [272, 3072, 130, 8192]
