[personal]
index = 478
species = "SPECIES_FROSLASS"
capture_rate = 75
evolution_stage = 2
ev_yield = 128
gender_probability = 254
egg_happiness = 20
base_happiness = 70
experience_group = 0
egg_groups = [6, 10]
escape_rate = 0
color = 8
base_experience = 168
height_cm = 13
weight_cg = 266

[personal.base_stats]
hp = 70
attack = 80
defense = 70
speed = 110
special_attack = 80
special_defense = 70

[personal.typing]
primary = "TYPE_ICE"
secondary = "TYPE_GHOST"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_BABIRI_BERRY"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 81
secondary = 81
hidden = 130

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-1247806880, 1082170112, 38818090, 0]
type_tutors = 0
special_tutors = [16400, 1026, 514, 10276]
