[personal]
index = 481
species = "SPECIES_MESPRIT"
capture_rate = 3
evolution_stage = 3
ev_yield = 1284
gender_probability = 255
egg_happiness = 80
base_happiness = 140
experience_group = 5
egg_groups = [15, 15]
escape_rate = 0
color = 9
base_experience = 261
height_cm = 3
weight_cg = 3

[personal.base_stats]
hp = 80
attack = 105
defense = 105
speed = 80
special_attack = 105
special_defense = 105

[personal.typing]
primary = "TYPE_PSYCHIC"
secondary = "TYPE_PSYCHIC"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 26
secondary = "BATTLE_ABILITY_RANDOM"
hidden = "BATTLE_ABILITY_RANDOM"

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-1247807956, 563120657, 191893800, 0]
type_tutors = 0
special_tutors = [28688, 73729, 38, 29936]
