[personal]
index = 496
species = "SPECIES_SERVINE"
capture_rate = 45
evolution_stage = 2
ev_yield = 128
gender_probability = 31
egg_happiness = 20
base_happiness = 70
experience_group = 3
egg_groups = [5, 7]
escape_rate = 0
color = 3
base_experience = 145
height_cm = 8
weight_cg = 160

[personal.base_stats]
hp = 60
attack = 60
defense = 75
speed = 83
special_attack = 60
special_defense = 75

[personal.typing]
primary = "TYPE_GRASS"
secondary = "TYPE_GRASS"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 65
secondary = 65
hidden = 126

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-2076602840, 1088385, -2107636704, 0]
type_tutors = 1
special_tutors = [64, 67584, 1039, 10243]
