[personal]
index = 505
species = "SPECIES_WATCHOG"
capture_rate = 255
evolution_stage = 2
ev_yield = 8
gender_probability = 127
egg_happiness = 20
base_happiness = 70
experience_group = 0
egg_groups = [5, 5]
escape_rate = 0
color = 5
base_experience = 147
height_cm = 11
weight_cg = 270

[personal.base_stats]
hp = 60
attack = 85
defense = 69
speed = 77
special_attack = 60
special_defense = 69

[personal.typing]
primary = "TYPE_NORMAL"
secondary = "TYPE_NORMAL"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 35
secondary = 51
hidden = 148

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-1382824416, 8952324, -1569450708, 4]
type_tutors = 0
special_tutors = [30294, 75904, 6, 8472]
