[personal]
index = 510
species = "SPECIES_LIEPARD"
capture_rate = 90
evolution_stage = 2
ev_yield = 128
gender_probability = 127
egg_happiness = 20
base_happiness = 70
experience_group = 0
egg_groups = [5, 5]
escape_rate = 0
color = 6
base_experience = 156
height_cm = 11
weight_cg = 375

[personal.base_stats]
hp = 64
attack = 88
defense = 50
speed = 106
special_attack = 88
special_defense = 50

[personal.typing]
primary = "TYPE_DARK"
secondary = "TYPE_DARK"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 7
secondary = 84
hidden = 158

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-1542238687, 1073855360, -479194869, 0]
type_tutors = 0
special_tutors = [1090, 102408, 38, 10276]
