[personal]
index = 512
species = "SPECIES_SIMISAGE"
capture_rate = 75
evolution_stage = 2
ev_yield = 128
gender_probability = 31
egg_happiness = 20
base_happiness = 70
experience_group = 0
egg_groups = [5, 5]
escape_rate = 0
color = 3
base_experience = 174
height_cm = 11
weight_cg = 305

[personal.base_stats]
hp = 75
attack = 98
defense = 63
speed = 101
special_attack = 98
special_defense = 63

[personal.typing]
primary = "TYPE_GRASS"
secondary = "TYPE_GRASS"

[personal.wild_items]
common_50 = "ITEM_ORAN_BERRY"
rare_5 = "ITEM_OCCA_BERRY"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 82
secondary = "BATTLE_ABILITY_RANDOM"
hidden = 65

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-869183967, 546896704, -1570471893, 0]
type_tutors = 0
special_tutors = [3650, 65792, 1070, 9490]
