[personal]
index = 527
species = "SPECIES_WOOBAT"
capture_rate = 190
evolution_stage = 1
ev_yield = 64
gender_probability = 127
egg_happiness = 15
base_happiness = 70
experience_group = 0
egg_groups = [5, 4]
escape_rate = 0
color = 1
base_experience = 63
height_cm = 4
weight_cg = 21

[personal.base_stats]
hp = 55
attack = 45
defense = 43
speed = 72
special_attack = 55
special_defense = 43

[personal.typing]
primary = "TYPE_PSYCHIC"
secondary = "TYPE_FLYING"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 109
secondary = 103
hidden = 86

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-1273001428, 1628486529, 198185760, 1]
type_tutors = 0
special_tutors = [2068, 8193, 5270, 24888]
