[personal]
index = 528
species = "SPECIES_SWOOBAT"
capture_rate = 45
evolution_stage = 2
ev_yield = 128
gender_probability = 127
egg_happiness = 15
base_happiness = 70
experience_group = 0
egg_groups = [5, 4]
escape_rate = 0
color = 1
base_experience = 149
height_cm = 9
weight_cg = 105

[personal.base_stats]
hp = 67
attack = 57
defense = 55
speed = 114
special_attack = 77
special_defense = 55

[personal.typing]
primary = "TYPE_PSYCHIC"
secondary = "TYPE_FLYING"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 109
secondary = 103
hidden = 86

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-1272985044, 1628486529, 198185768, 1]
type_tutors = 0
special_tutors = [2068, 8193, 5526, 24888]
