[personal]
index = 532
species = "SPECIES_TIMBURR"
capture_rate = 180
evolution_stage = 1
ev_yield = 4
gender_probability = 63
egg_happiness = 20
base_happiness = 70
experience_group = 3
egg_groups = [8, 8]
escape_rate = 0
color = 7
base_experience = 61
height_cm = 6
weight_cg = 125

[personal.base_stats]
hp = 75
attack = 80
defense = 55
speed = 35
special_attack = 25
special_defense = 35

[personal.typing]
primary = "TYPE_FIGHTING"
secondary = "TYPE_FIGHTING"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 62
secondary = 125
hidden = 89

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-866972000, 8968768, 577536070, 4]
type_tutors = 0
special_tutors = [29184, 258, 2054, 8208]
