[personal]
index = 536
species = "SPECIES_PALPITOAD"
capture_rate = 120
evolution_stage = 2
ev_yield = 2
gender_probability = 127
egg_happiness = 20
base_happiness = 70
experience_group = 3
egg_groups = [2, 2]
escape_rate = 0
color = 1
base_experience = 134
height_cm = 8
weight_cg = 170

[personal.base_stats]
hp = 75
attack = 65
defense = 55
speed = 69
special_attack = 65
special_defense = 55

[personal.typing]
primary = "TYPE_WATER"
secondary = "TYPE_GROUND"

[personal.wild_items]
common_50 = "ITEM_PECHA_BERRY"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 33
secondary = 93
hidden = 11

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-2079128992, 4299274, 574627840, 2]
type_tutors = 0
special_tutors = [2304, 33796, 2, 12545]
