[personal]
index = 538
species = "SPECIES_THROH"
capture_rate = 45
evolution_stage = 2
ev_yield = 2
gender_probability = 0
egg_happiness = 20
base_happiness = 70
experience_group = 0
egg_groups = [8, 8]
escape_rate = 0
color = 0
base_experience = 163
height_cm = 13
weight_cg = 555

[personal.base_stats]
hp = 120
attack = 100
defense = 85
speed = 45
special_attack = 30
special_defense = 85

[personal.typing]
primary = "TYPE_FIGHTING"
secondary = "TYPE_FIGHTING"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_BLACK_BELT"
rare_1 = "ITEM_EXPERT_BELT"

[personal.abilities]
primary = 62
secondary = 39
hidden = 104

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-837611872, 8968768, 577544270, 4]
type_tutors = 0
special_tutors = [29184, 258, 519, 8208]
