[personal]
index = 547
species = "SPECIES_WHIMSICOTT"
capture_rate = 75
evolution_stage = 2
ev_yield = 128
gender_probability = 127
egg_happiness = 20
base_happiness = 70
experience_group = 0
egg_groups = [7, 6]
escape_rate = 0
color = 3
base_experience = 168
height_cm = 7
weight_cg = 66

[personal.base_stats]
hp = 60
attack = 67
defense = 85
speed = 116
special_attack = 77
special_defense = 75

[personal.typing]
primary = "TYPE_GRASS"
secondary = "TYPE_GRASS"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 158
secondary = 151
hidden = 34

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-1271280096, 9484800, 191889448, 0]
type_tutors = 0
special_tutors = [66, 0, 1158, 8466]
