[personal]
index = 552
species = "SPECIES_KROKOROK"
capture_rate = 90
evolution_stage = 2
ev_yield = 8
gender_probability = 127
egg_happiness = 20
base_happiness = 70
experience_group = 3
egg_groups = [5, 5]
escape_rate = 0
color = 5
base_experience = 123
height_cm = 10
weight_cg = 334

[personal.base_stats]
hp = 60
attack = 82
defense = 45
speed = 74
special_attack = 45
special_defense = 45

[personal.typing]
primary = "TYPE_GROUND"
secondary = "TYPE_DARK"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 22
secondary = 153
hidden = 83

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-837744079, 1149303640, -496983993, 4]
type_tutors = 0
special_tutors = [2560, 71692, 6, 14340]
