[personal]
index = 567
species = "SPECIES_ARCHEOPS"
capture_rate = 45
evolution_stage = 2
ev_yield = 8
gender_probability = 31
egg_happiness = 30
base_happiness = 70
experience_group = 0
egg_groups = [4, 9]
escape_rate = 0
color = 2
base_experience = 177
height_cm = 14
weight_cg = 320

[personal.base_stats]
hp = 75
attack = 140
defense = 65
speed = 110
special_attack = 112
special_defense = 65

[personal.typing]
primary = "TYPE_ROCK"
secondary = "TYPE_FLYING"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 129
secondary = "BATTLE_ABILITY_RANDOM"
hidden = "BATTLE_ABILITY_RANDOM"

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-1907275213, 537435088, -1547526055, 1]
type_tutors = 0
special_tutors = [2304, 84036, 4498, 13056]
