[personal]
index = 568
species = "SPECIES_TRUBBISH"
capture_rate = 190
evolution_stage = 1
ev_yield = 64
gender_probability = 127
egg_happiness = 20
base_happiness = 70
experience_group = 0
egg_groups = [10, 10]
escape_rate = 0
color = 3
base_experience = 66
height_cm = 6
weight_cg = 310

[personal.base_stats]
hp = 50
attack = 50
defense = 62
speed = 65
special_attack = 40
special_defense = 62

[personal.typing]
primary = "TYPE_POISON"
secondary = "TYPE_POISON"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_BLACK_SLUDGE"
rare_1 = "ITEM_NUGGET"

[personal.abilities]
primary = "BATTLE_ABILITY_PRIMARY"
secondary = 60
hidden = 106

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-2079127776, -2147436022, 37748738, 0]
type_tutors = 0
special_tutors = [1088, 4096, 3586, 9220]
