[personal]
index = 612
species = "SPECIES_HAXORUS"
capture_rate = 45
evolution_stage = 3
ev_yield = 12
gender_probability = 127
egg_happiness = 40
base_happiness = 35
experience_group = 5
egg_groups = [1, 14]
escape_rate = 0
color = 2
base_experience = 243
height_cm = 18
weight_cg = 1055

[personal.base_stats]
hp = 76
attack = 147
defense = 90
speed = 97
special_attack = 60
special_defense = 70

[personal.typing]
primary = "TYPE_DRAGON"
secondary = "TYPE_DRAGON"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 79
secondary = 104
hidden = 127

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-837595597, 78158528, -1570003957, 6]
type_tutors = 64
special_tutors = [520, 84224, 2, 8960]
