[personal]
index = 615
species = "SPECIES_CRYOGONAL"
capture_rate = 25
evolution_stage = 2
ev_yield = 2048
gender_probability = 255
egg_happiness = 25
base_happiness = 70
experience_group = 0
egg_groups = [10, 10]
escape_rate = 0
color = 1
base_experience = 170
height_cm = 11
weight_cg = 1480

[personal.base_stats]
hp = 70
attack = 50
defense = 30
speed = 105
special_attack = 95
special_defense = 135

[personal.typing]
primary = "TYPE_ICE"
secondary = "TYPE_ICE"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NEVER-MELT_ICE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 26
secondary = "BATTLE_ABILITY_RANDOM"
hidden = "BATTLE_ABILITY_RANDOM"

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-2076970400, -1610573311, 105398272, 0]
type_tutors = 0
special_tutors = [16, 1089, 7, 8192]
