[personal]
index = 632
species = "SPECIES_DURANT"
capture_rate = 90
evolution_stage = 2
ev_yield = 32
gender_probability = 127
egg_happiness = 20
base_happiness = 70
experience_group = 0
egg_groups = [3, 3]
escape_rate = 0
color = 7
base_experience = 169
height_cm = 3
weight_cg = 330

[personal.base_stats]
hp = 58
attack = 109
defense = 112
speed = 109
special_attack = 48
special_defense = 48

[personal.typing]
primary = "TYPE_BUG"
secondary = "TYPE_STEEL"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 68
secondary = 55
hidden = 54

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-1945042399, 1088208, -1505654435, 4]
type_tutors = 0
special_tutors = [33, 320, 2, 8448]
