[personal]
index = 635
species = "SPECIES_HYDREIGON"
capture_rate = 45
evolution_stage = 3
ev_yield = 768
gender_probability = 127
egg_happiness = 40
base_happiness = 35
experience_group = 5
egg_groups = [14, 14]
escape_rate = 0
color = 1
base_experience = 270
height_cm = 18
weight_cg = 1600

[personal.base_stats]
hp = 92
attack = 105
defense = 90
speed = 98
special_attack = 125
special_defense = 90

[personal.typing]
primary = "TYPE_DARK"
secondary = "TYPE_DRAGON"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 26
secondary = "BATTLE_ABILITY_RANDOM"
hidden = "BATTLE_ABILITY_RANDOM"

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 1

[personal.compatibility]
tmhm = [-2045555152, 621394789, 658944330, 7]
type_tutors = 64
special_tutors = [2064, 129284, 4242, 8708]
