[personal]
index = 641
species = "SPECIES_TORNADUS"
capture_rate = 3
evolution_stage = 3
ev_yield = 12
gender_probability = 0
egg_happiness = 120
base_happiness = 90
experience_group = 5
egg_groups = [15, 15]
escape_rate = 0
color = 3
base_experience = 261
height_cm = 15
weight_cg = 630

[personal.base_stats]
hp = 79
attack = 115
defense = 70
speed = 111
special_attack = 125
special_defense = 80

[personal.typing]
primary = "TYPE_FLYING"
secondary = "TYPE_FLYING"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 158
secondary = "BATTLE_ABILITY_RANDOM"
hidden = 128

[personal.forms]
data_offset = 706
sprite_offset = 55
count = 2

[personal.compatibility]
tmhm = [-732738912, 1720236938, 593494026, 5]
type_tutors = 0
special_tutors = [2048, 70920, 182, 8192]
