[personal]
index = 707
species = "SPECIES_KLEFKI"
capture_rate = 3
evolution_stage = 3
ev_yield = 768
gender_probability = 0
egg_happiness = 120
base_happiness = 90
experience_group = 5
egg_groups = [15, 15]
escape_rate = 0
color = 1
base_experience = 261
height_cm = 30
weight_cg = 610

[personal.base_stats]
hp = 79
attack = 105
defense = 70
speed = 101
special_attack = 145
special_defense = 80

[personal.typing]
primary = "TYPE_ELECTRIC"
secondary = "TYPE_FLYING"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 10
secondary = "BATTLE_ABILITY_RANDOM"
hidden = 10

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 2

[personal.compatibility]
tmhm = [-707573088, 1200143114, 929038730, 5]
type_tutors = 0
special_tutors = [6144, 69896, 38, 8192]
