[personal]
index = 708
species = "SPECIES_PHANTUMP"
capture_rate = 3
evolution_stage = 3
ev_yield = 12
gender_probability = 0
egg_happiness = 120
base_happiness = 90
experience_group = 5
egg_groups = [15, 15]
escape_rate = 0
color = 5
base_experience = 270
height_cm = 13
weight_cg = 680

[personal.base_stats]
hp = 89
attack = 145
defense = 90
speed = 91
special_attack = 105
special_defense = 80

[personal.typing]
primary = "TYPE_GROUND"
secondary = "TYPE_FLYING"

[personal.wild_items]
common_50 = "ITEM_NONE"
rare_5 = "ITEM_NONE"
rare_1 = "ITEM_NONE"

[personal.abilities]
primary = 22
secondary = "BATTLE_ABILITY_RANDOM"
hidden = 22

[personal.forms]
data_offset = 0
sprite_offset = 0
count = 2

[personal.compatibility]
tmhm = [-565099864, -2138531238, 593536090, 5]
type_tutors = 0
special_tutors = [0, 65814, 38, 12800]
